// Norwegian texts — primary locale for nemtbudget.nu build (VITE_LOCALE=no)
// Complete set — no fallback to Danish needed
export const NO: Record<string, string> = {
  // Nav
  "nav.products": "Produkter",
  "nav.howItWorks": "Slik virker det",
  "nav.back": "Tilbake",
  "nav.budget": "Budsjett",
  "nav.coupleFinance": "Parøkonomi",
  "nav.childTax": "Barneskatteplanlegging",
  "nav.cockpit": "Cockpit",
  "nav.overview": "Oversikt",
  "nav.action": "Handling",
  "nav.future": "Fremtid",
  "nav.advanced": "Dybdegående",

  // Hero
  "hero.title": "Ta kontroll over",
  "hero.titleHighlight": "din privatøkonomi.",
  "hero.subtitle": "Finn skjulte utgifter, se hva du reelt har til overs og stå sterkt for fremtiden — gratis, privat og på 3 minutter.",
  "hero.cta": "Sjekk økonomien din gratis",
  "hero.imageAlt": "Personlig økonomi og budsjettoverikt",
  "hero.socialProof": "1.200+ nordmenn har allerede sjekket budsjettet sitt",

  // Trust
  "trust.danish": "Bygget for norsk økonomi",
  "trust.time": "Utfylt på 3 minutter",
  "trust.private": "100% privat · Data lagres lokalt",

  // How it works
  "howItWorks.title": "Få det fulle oversiktet på 3 minutter",
  "howItWorks.subtitle": "Ingen regneark. Svar ja/nei — vi tar resten.",

  // Stats
  "stats.3min": "3 min",
  "stats.fillIn": "Å fylle ut",
  "stats.avgSaving": "Gj.sn. besparelse/md.",
  "stats.freePrivate": "Privat & gratis",

  // Features
  "feature.findHidden": "Finn skjulte utgifter",
  "feature.findHiddenDesc": "Vi gjennomgår strømming, forsikring og transport — og viser hva som spiser budsjettet ditt.",
  "feature.aiInsight": "AI-innsikt",
  "feature.aiInsightDesc": "Analyse av tallene dine og utgiftsmønstre.",
  "feature.compare": "Sammenlign med andre",
  "feature.compareDesc": "Se økonomien din sammenlignet med andre i ditt område og din inntektsgruppe.",
  "feature.bankReport": "Bankmøte-rapport",
  "feature.bankReportDesc": "Ta med en profesjonell rapport til banken din.",
  "feature.stressTest": "Stress-test økonomien din",
  "feature.stressTestDesc": "Hva skjer ved jobbtap, renteøkning eller inflasjon? Se din motstandsdyktighet.",
  "feature.savings": "Spareplanlegger",
  "feature.savingsDesc": "Se når du når målene dine med nåværende sparerate.",

  // Testimonials
  "testimonials.title": "Hva andre sier",

  // Bottom CTA
  "bottomCta.title": "Klar til å komme i gang?",
  "bottomCta.subtitle": "Det tar bare 3 minutter — og koster ingenting.",
  "bottomCta.noLogin": "Ingen innlogging · Ingen data deles · Alt lagres lokalt",

  // Footer
  "footer.tagline": "Få et komplett oversikt over økonomien din. Gratis, privat og bygget for norske forhold.",
  "footer.product": "Produkt",
  "footer.budgetCalc": "Budsjettberegner",
  "footer.neighborComp": "Nabo-sammenligning",
  "footer.info": "Informasjon",
  "footer.privacy": "Personvern",
  "footer.terms": "Vilkår",
  "footer.contact": "Kontakt",
  "footer.about": "Om",
  "footer.private": "All data lagres lokalt i nettleseren din. Vi selger aldri dine data.",
  "footer.tools": "Verktøy",
  "footer.legal": "Juridisk",
  "footer.disclaimer": "NemtBudget er et budsjetteringsverktøy og gir ikke finansiell rådgivning. Snakk med banken din eller en rådgiver om konkrete økonomiske beslutninger.",
  "footer.based": "Beregnet på norske gjennomsnittstall 2026 · Data lagres lokalt",
  "footer.installApp": "Installer app",
  "footer.guides": "Guider & tips",

  // Onboarding — household
  "step.household.title": "Hvem er med i husstanden?",
  "step.household.subtitle": "Vi tilpasser alle estimater til situasjonen din.",
  "step.household.solo": "Bare meg",
  "step.household.soloSub": "Enslig husstand",
  "step.household.couple": "Vi er to",
  "step.household.coupleSub": "Par / samboende",

  // Onboarding — income
  "step.income.titleSolo": "Hva er inntekten din?",
  "step.income.titleCouple": "Hva er inntekten deres?",
  "step.income.subtitle": "Månedlig utbetalt etter skatt.",
  "step.income.myIncome": "Månedlig inntekt",
  "step.income.myIncomePar": "Din inntekt",
  "step.income.partnerIncome": "Partners inntekt",
  "step.income.otherIncome": "Øvrig inntekt",
  "step.income.placeholder": "F.eks. Bonus, dagpenger, barnetrygd",
  "step.income.amount": "Beløp",
  "step.income.addSource": "Legg til inntektskilde",
  "step.income.total": "Samlet inntekt",
  "step.income.tipSolo": "Gjennomsnittlig inntekt for enslige i Norge er ca. 32 000 kr./md. etter skatt.",
  "step.income.tipCouple": "Gjennomsnittlig husholdningsinntekt for par i Norge er ca. 62 000 kr./md. etter skatt.",
  "step.income.netTip": "Oppgi lønn etter skatt (netto — det du får utbetalt)",

  // Onboarding — housing
  "step.housing.title": "Boligsituasjon",
  "step.housing.subtitle": "Vi estimerer ut fra postnummer — juster fritt.",
  "step.housing.renter": "Leier",
  "step.housing.coop": "Borettslag",
  "step.housing.owner": "Selveier",
  "step.housing.postalCode": "Postnummer",
  "step.housing.postalPlaceholder": "F.eks. 0450",
  "step.housing.unknownPostal": "Ukjent postnummer — estimater kan ikke beregnes",
  "step.housing.rent": "Månedlig husleie",
  "step.housing.coopFee": "Månedlige felleskostnader",
  "step.housing.coopLoan": "Borettslånet (avdrag + renter)",
  "step.housing.mortgage": "Månedlig boligytelse",
  "step.housing.propertyValue": "Estimert boligverdi",
  "step.housing.interestRate": "Rente på lån",

  // Onboarding — children
  "step.children.titleSolo": "Har du barn?",
  "step.children.titleCouple": "Har dere barn?",
  "step.children.subtitle": "Vi finner barnehagepriser automatisk.",
  "step.children.no": "Ingen barn",
  "step.children.yes": "Ja, vi har barn",
  "step.children.age": "Alder for hvert barn:",
  "step.children.child": "Barn",
  "step.children.years": "år",
  "step.children.add": "Legg til barn",
  "step.children.tip": "Barnehagepriser er makspris 2025: 3 315 kr./md. (Utdanningsdirektoratet). SFO ca. 2 000 kr./md. Din kommune kan avvike — juster i dashboardet.",
  "step.children.benefitTitle": "Barnetrygd (automatisk inkludert)",
  "step.children.benefitTotal": "Total barnetrygd",

  // Onboarding — expenses
  "step.expenses.title": "Faste utgifter",
  "step.expenses.subtitle": "Velg det som passer — vi fyller inn prisene.",
  "step.expenses.streaming": "Streaming & musikk",
  "step.expenses.transport": "Transport",
  "step.expenses.car": "Bil",
  "step.expenses.carLoan": "Billån / leasing",
  "step.expenses.fuel": "Bensin / lading",
  "step.expenses.carInsurance": "Bilforsikring",
  "step.expenses.carTax": "Årsavgift / trafikkforsikring",
  "step.expenses.carService": "Service / verksted",
  "step.expenses.insuranceUnion": "Forsikring & fagforbund",
  "step.expenses.insurance": "Forsikringer",
  "step.expenses.insuranceSub": "Innbo, ulykke, etc.",
  "step.expenses.union": "Fagforbund & dagpengekasse",
  "step.expenses.fitness": "Fitness / sport",
  "step.expenses.petsLoans": "Kjæledyr, lån & sparing",
  "step.expenses.pet": "Kjæledyr",
  "step.expenses.petSub": "Fôr, veterinær, forsikring",
  "step.expenses.loan": "Lån",
  "step.expenses.loanSub": "Studielån, forbrukslån, billån",
  "step.expenses.savings": "Sparing / investering",
  "step.expenses.savingsSub": "Fast sparing per måned",
  "step.everyday.title": "Hverdagsutgifter",
  "step.everyday.subtitle": "Juster daglige utgifter — vi har fylt inn gjennomsnitt",
  "step.expenses.custom": "Egne utgifter",
  "step.expenses.customPlaceholder": "F.eks. Kontaktlinser",
  "step.expenses.seeOverview": "Se oversikt",
  "step.expenses.utilities": "Telefon, internett & forsyning",
  "step.expenses.internet": "Internett",
  "step.expenses.mobileSolo": "Mobil",
  "step.expenses.mobilePar": "Mobil (2 pers.)",
  "step.expenses.electricity": "Strøm",
  "step.expenses.heating": "Varme & vann",
  "step.expenses.drLicens": "NRK-lisens",
  "step.expenses.included": "(inkludert)",
  "step.expenses.utilitiesNote": "Disse utgiftene medregnes automatisk i budsjettet ditt.",

  // Onboarding — review
  "step.review.title": "Gjennomgå & juster",
  "step.review.subtitle": "Rett alle tall til før du går videre.",
  "step.review.disposable": "Disponibel inntekt per måned",
  "step.review.good": "God økonomi",
  "step.review.tight": "Slank margin",
  "step.review.warning": "Under anbefaling",
  "step.review.income": "Inntekt",
  "step.review.expenses": "Utgifter",
  "step.review.share": "Andel",
  "step.review.variableExpenses": "Variable utgifter — juster til ditt forbruk",
  "step.review.food": "Mat & dagligvarer",
  "step.review.restaurant": "Restaurant & takeaway",
  "step.review.leisure": "Fritid & opplevelser",
  "step.review.clothing": "Klær & personlig pleie",
  "step.review.health": "Helse (lege, tannlege)",
  "step.review.fixedExpenses": "Faste utgifter",
  "step.review.seeDashboard": "Se fullt dashboard",
  "step.review.zeroIncomeWarning": "Inntekten din er satt til 0 kr. Er det riktig?",

  // Dashboard
  "dash.title": "Ditt budsjett — NemtBudget",
  "dash.charts": "Diagrammer",
  "dash.chartsShort": "Grafer",
  "dash.report": "Rapport",
  "dash.newCalc": "Ny beregning",
  "dash.resetShort": "Nullstill",
  "dash.shareResult": "Del resultatet ditt",
  "dash.close": "Lukk",
  "dash.editInfo": "Rediger opplysninger",
  "dash.logOut": "Logg ut",
  "dash.logIn": "Logg inn",
  "dash.cloudSync": "Logg inn for å lagre budsjettet ditt på tvers av enheter",
  "dash.subscriptions": "Abonnementer",

  // Sections
  "section.cockpit": "Cockpit",
  "section.cockpitSub": "Ditt økonomiske oversikt — alt på ett sted.",
  "section.overview": "Oversikt",
  "section.overviewSub": "Hvor går pengene dine? Se det hele i ett blikk.",
  "section.action": "Handling",
  "section.actionSub": "Konkrete spareforslag basert på tallene dine.",
  "section.future": "Fremtid",
  "section.futureSub": "Se fremover — formue, mål og tidslinje.",
  "section.advanced": "Dybdegående",
  "section.advancedSub": "Avanserte analyser og simuleringer.",

  // Tabs
  "tab.cockpit": "Cockpit",
  "tab.forward": "Fremover",
  "tab.whatIf": "Hva hvis",
  "tab.stressTest": "Stress-test",
  "tab.calendar": "Årshjul",
  "tab.optimize": "Optimering",
  "tab.compare": "Sammenlign",
  "tab.history": "Historikk",
  "tab.coupleSplit": "Parsplit",

  // Health
  "health.freedom": "Frihetstall",
  "health.freedomSub": "Reelt til overs per md.",
  "health.baseline": "Grunnlinje",
  "health.baselineSub": "Faste utgifter per md.",
  "health.buffer": "Buffer",
  "health.bufferSub": "md. uten inntekt",

  // Frequencies
  "freq.monthly": "Månedlig",
  "freq.quarterly": "Kvartalsvis",
  "freq.biannual": "Halvårlig",
  "freq.annual": "Årlig",
  "freq.monthlyShort": "Md.",
  "freq.quarterShort": "Kvartal",
  "freq.halfYearShort": "Halvår",
  "freq.yearShort": "År",

  // Stress test
  "stress.resilience": "Motstandsdyktighet",
  "stress.resilienceGood": "Økonomien din kan motstå de fleste økonomiske sjokk. Sterk posisjon.",
  "stress.resilienceOk": "Økonomien din er sårbar for visse scenarioer. Vurder å styrke bufferen din.",
  "stress.resilienceBad": "Økonomien din er skjør. Selv små endringer kan skape problemer. Prioriter sparing.",
  "stress.inflation": "Inflasjon",
  "stress.inflationDesc": "Hva skjer hvis prisene stiger? Variable utgifter rammes hardest.",
  "stress.moderate": "Moderat",
  "stress.severe": "Alvorlig",
  "stress.extreme": "Ekstrem",
  "stress.newDisposable": "Nytt disponibelt beløp",
  "stress.impact": "Effekt",
  "stress.rateHike": "Renteøkning",
  "stress.rateHikeDesc": "Hva skjer hvis renten stiger? Påvirker boliglånet ditt direkte.",
  "stress.mortgageUp": "Boliglån øker",
  "stress.jobLoss": "Jobbtap",
  "stress.jobLossDesc": "Hva skjer hvis inntekten din faller? Vi beregner med og uten dagpenger.",
  "stress.withoutHelp": "Uten dagpenger",
  "stress.withDagpenge": "Med dagpenger",
  "stress.survivalTime": "Overlevelsestid",
  "stress.months": "måneder",
  "stress.monthsShort": "md.",
  "stress.withSavings": "med nåværende sparing",
  "stress.worstCase": "Worst case: Alt på én gang",
  "stress.worstCaseDesc": "Inflasjon + renteøkning + inntektsfall. Budsjettet ditt under maksimalt press.",
  "stress.disclaimer": "Stress-testen er et estimat. Kontakt banken din for nøyaktig beregning.",

  // Årshjul
  "wheel.annual": "Årlige utgifter",
  "wheel.annualSub": "Store utgifter du bør forberede deg på i løpet av året",
  "wheel.monthlyOverview": "Månedsoversikt",
  "wheel.upcoming": "Kommende utgifter",
  "wheel.fullYear": "Hele året",
  "wheel.now": "Nå",
  "wheel.carInsurance": "Bilforsikring",
  "wheel.carTax": "Årsavgift",
  "wheel.carService": "Bilservice",
  "wheel.propertyTax": "Eiendomsskatt",
  "wheel.insuranceRenewal": "Forsikring (fornyelse)",
  "wheel.christmas": "Jul & gaver",
  "wheel.summerVacation": "Sommerferie",
  "wheel.taxSettlement": "Restskatt / overskudd",
  "wheel.backToSchool": "Skolestart",
  "wheel.birthdays": "Fødselsdager",
  "wheel.disclaimer": "Beløpene er estimater basert på norske gjennomsnitt.",

  // Nudges
  "nudge.savingsAbove": "Spareraten din ({pct}) er over gjennomsnittet ({avg}) for lignende husholdninger 💪",
  "nudge.savingsBelow": "De fleste lignende husholdninger sparer minst {avg} av inntekten",
  "nudge.streaming": "Du har {count} strømmetjenester — 67% av norske husholdninger har maks 2",
  "nudge.foodAbove": "Matbudsjettet ditt er {pct}% over gjennomsnittet for lignende husholdninger",
  "nudge.foodBelow": "Matbudsjettet ditt er under gjennomsnittet — godt jobba! 🥗",
  "nudge.topPercentile": "Disponibelt beløp er i topp {pct}% blant lignende husholdninger",
  "nudge.housingHigh": "Boligutgiften utgjør {pct}% av inntekten — eksperter anbefaler maks 33%",
  "nudge.healthTop": "Helsescoren din er i topp 25 — du er bedre stilt enn de fleste",

  // Scenarios
  "scenario.buyHome.title": "Kjøp bolig",
  "scenario.buyHome.desc": "Hva skjer hvis du skifter fra leie til selveier?",
  "scenario.haveChild.title": "Få barn",
  "scenario.haveChild.desc": "Hvordan påvirker et barn økonomien din?",
  "scenario.newJob.title": "Bytt jobb",
  "scenario.newJob.desc": "Simuler en ny lønn og se effekten.",
  "scenario.intro": "Slå på scenarioer og se hvordan de påvirker økonomien din i sanntid.",
  "scenario.monthlyImpact": "Månedlig effekt",
  "scenario.newDisposable": "Nytt disponibelt beløp",
  "scenario.mortgagePayment": "Månedlig boligytelse",
  "scenario.salaryChange": "Lønnsendring",
  "scenario.before": "Før vs. etter",
  "scenario.now": "Nå",
  "scenario.label": "Scenario",
  "scenario.disposablePerMonth": "disponibelt pr. md.",
  "scenario.scoreLabel": "Score",

  // Page meta
  "page.lastUpdated": "Sist oppdatert",
  "page.updatedDate": "mars 2026",

  // Actions
  "action.goToDashboard": "Gå til budsjettet ditt",

  // Cookie
  "cookie.text": "Vi bruker informasjonskapsler for å lagre preferansene dine lokalt. Ingen data sendes til tredjeparter.",
  "cookie.readMore": "Les mer",
  "cookie.accept": "Aksepter",
  "cookie.decline": "Avvis",

  // Generic
  "continue": "Fortsett",
  "currency": "kr.",
  "perMonth": "kr./md.",
  "perYear": "kr./år",
  "perHalfYear": "kr./halvår",

  // Report
  "report.title": "Finansrapport",
  "report.solo": "Solobudsjett",
  "report.couple": "Parbudsjett",
  "report.postalCode": "Postnr.",
  "report.back": "Tilbake",
  "report.share": "Del",
  "report.print": "Print / PDF",
  "report.health": "Økonomisk helse",
  "report.buffer": "Buffer",
  "report.monthlyIncome": "Månedlig inntekt",
  "report.totalExpenses": "Samlede utgifter",
  "report.savingsRate": "Sparerate",
  "report.housingRatio": "Bolig-ratio",
  "report.expenseBreakdown": "Utgiftsspesifikasjon",
  "report.fixedExpenses": "Faste utgifter",
  "report.variableExpenses": "Variable utgifter",
  "report.incomeDist": "Inntektsfordeling",
  "report.you": "Deg",
  "report.partner": "Partner",
  "report.generated": "Generert {date} · Beregnet på norske gjennomsnittstall 2026",
  "report.disclaimer": "Budsjetteringsverktøy — ikke finansiell rådgivning",
  "report.bufferMonths": "{n} md.",

  // Cockpit
  "cockpit.income": "Inntekt",
  "cockpit.partner": "Partner",
  "cockpit.expenses": "Utgifter",
  "cockpit.disposable": "Til rådighet",
  "cockpit.total": "I alt",
  "cockpit.distribution": "Pengefordeling",
  "cockpit.savingsPotential": "Sparepotensial",
  "cockpit.seePlan": "Se plan ↓",
  "cockpit.insights": "Hvordan klarer du deg?",
  "cockpit.bucket.drift": "Drift",
  "cockpit.bucket.driftTip": "Faste utgifter: bolig, mat, transport, forsikring",
  "cockpit.bucket.frihed": "Frihet",
  "cockpit.bucket.frihedTip": "Til overs etter faste utgifter — ditt disponibelt beløp",
  "cockpit.bucket.fremtid": "Fremtid",
  "cockpit.bucket.fremtidTip": "Sparing og pensjonsinnskudd",
  "cockpit.bucket.risiko": "Risiko",
  "cockpit.bucket.risikoTip": "Gjeld og variable utgifter",
  "cockpit.alert.overBudget": "Du bruker {amount} kr. mer enn du tjener",
  "cockpit.alert.housingHigh": "Bolig utgjør {pct}% av inntekten — over anbefalte 35%",
  "cockpit.alert.streamingMany": "{count} strømmetjenester — gjennomsnittsnordmann har 2",
  "cockpit.alert.savingsStrong": "Sterk sparerate på {pct}%",
  "cockpit.live.electricity": "Strøm: {price} kr/kWh",
  "cockpit.live.rate": "Rente: {rate}%",
  "cockpit.live.income": "Gj.sn. inntekt: {amount} kr.",

  // Categories
  "cat.Bolig": "Bolig",
  "cat.Forsyning": "Forsyning",
  "cat.Transport": "Transport",
  "cat.Abonnementer": "Abonnementer",
  "cat.Forsikring": "Forsikring",
  "cat.Fagforening": "Fagforening",
  "cat.Børn": "Barn",
  "cat.Kæledyr": "Kjæledyr",
  "cat.Lån": "Lån",
  "cat.Fitness": "Fitness",
  "cat.Opsparing": "Sparing",
  "cat.Mad & dagligvarer": "Mat & dagligvarer",
  "cat.Fritid": "Fritid",
  "cat.Tøj": "Klær",
  "cat.Sundhed": "Helse",
  "cat.Restaurant": "Restaurant",
  "cat.Andet": "Annet",

  // Sankey / overview
  "sankey.incomeDistribution": "Inntekt fordelt på utgifter",
  "sankey.leftOver": "Til overs",
  "sankey.salary": "Lønn",
  "sankey.partner": "Partner",
  "sankey.otherIncome": "Øvrig",
  "sankey.income": "Inntekt",
  "sankey.expenses": "Utgifter",
  "sankey.whatIf": "Hva om?",
  "sankey.reset": "Tilbakestill",
  "sankey.perMonth": "kr./md.",
  "sankey.saved": "spart",
  "sankey.extra": "ekstra",
  // V2 features
  "sankey.privacy": "Privat",
  "sankey.privacyTip": "Skjul beløp — vis kun prosenter",
  "sankey.benchmark": "50/30/20",
  "sankey.benchmarkTip": "Sammenlign budsjettet ditt med tommelfingerregelen",
  "sankey.projection": "Sparemål",
  "sankey.projectionTip": "Hva kan du spare med dette budsjettet?",
  "sankey.share": "Del",
  "sankey.shareTip": "Kopier diagram som bilde",
  "sankey.needs": "Behov",
  "sankey.wants": "Ønsker",
  "sankey.savingsLabel": "Sparing",
  "sankey.recommended": "Anbefalt",
  "sankey.actual": "Faktisk",
  "sankey.projMonths": "{n} md.",
  "sankey.projSaved": "Sparepotensial",
  "sankey.projTotal": "Med dette budsjettet etter {n} md.",
  "sankey.projDisclaimer": "Basert på ditt nåværende budsjett — ikke historiske data",
  "sankey.ofIncome": "av inntekt",
  "sankey.dkAvg": "NO gns.",
  "sankey.items": "poster",
  "sankey.drillDown": "Klikk for detaljer",
  "sankey.collapse": "Lukk",
  "sankey.copied": "Kopiert!",
  "sankey.export": "Eksporter",
  "sankey.exportTip": "Lagre som bilde — perfekt for deling",
  "sankey.exportBrand": "nemtbudget.nu",
  "sankey.exportMadeWith": "Laget med",
  "sankey.milestone.saver": "Sterk sparer! Du sparer {pct}%",
  "sankey.milestone.balanced": "Balansert budsjett!",
  "sankey.insight.highHousing": "Bolig utgjør {pct}% — over anbefalt 30%",
  "sankey.insight.goodSavings": "Spareraten din på {pct}% er over gjennomsnittet",
  "sankey.insight.lowFree": "Bare {amount} til overs — vurder å redusere",
  "sankey.insight.streaming": "{count} strømmetjenester — vurder å samle",
  "sankey.insight.topCat": "{cat} er din største utgift ({pct}%)",

  // Dashboard misc
  "dash.startOver": "Start på nytt",
  "dash.reset": "Nullstill",
  "dash.disclaimer": "NemtBudget er et budsjetteringsverktøy — ikke finansiell rådgivning.",
  "dash.aiTitle": "La AI finne dine besparelser",
  "dash.aiSubtitle": "Guidet gjennomgang — du bestemmer hva du vil gjøre",
  "dash.useDefaults": "Bruk standardtall og se mitt resultat →",
  "dash.hideDetails": "Skjul detaljer",
  "dash.showCarDetails": "Fordel utgifter på bil",

  // Neighbor comparison
  "neighbor.comparedWith": "Sammenlignet med din inntektsgruppe",
  "neighbor.pair": "par",
  "neighbor.single": "enslig",
  "neighbor.housingCost": "Boligutgift:",
  "neighbor.categoryByCategory": "Kategori for kategori",
  "neighbor.onPar": "På nivå",
  "neighbor.savingsIfLowered": "Hvis du senker til typisk nivå, sparer du",
  "neighbor.food": "Mat & dagligvarer",
  "neighbor.restaurant": "Restaurant & takeaway",
  "neighbor.transportCar": "Transport (bil)",
  "neighbor.transport": "Transport",
  "neighbor.streaming": "Strømming & abonnementer",
  "neighbor.leisure": "Fritid & opplevelser",

  // Optimization
  "optimize.totalPotential": "Samlet potensial",
  "optimize.lookingGood": "Økonomien din ser sterk ut",
  "optimize.noSavings": "Vi fant ingen åpenbare besparelser — bra jobba!",
  "optimize.doItNow": "Gjør det nå — ",
  "optimize.dstBenchmark": "SSB-referanse",
  "optimize.dkAverage": "NO-gjennomsnitt",
  "optimize.yourDisposable": "Ditt disponibelt beløp",

  // Couple split
  "couple.incomeBasedSplit": "Inntektsfordelt",
  "couple.partnerIncome": "Partners inntekt",
  "couple.partnerPays": "Partner betaler",
  "couple.expenses": "Utgifter",
  "couple.remaining": "Rest",

  // Profile edit
  "profile.householdIncome": "Husstand & Inntekt",
  "profile.partnerIncomeNet": "Partners inntekt (netto)",
  "profile.housing": "Bolig",
  "profile.housingType": "Boligtype",
  "profile.food": "Mat & dagligvarer",
  "profile.leisure": "Fritid & opplevelser",
  "profile.clothing": "Klær & sko",

  // Forward view
  "forward.propertyValue": "Boligverdi",
  "forward.propertyEstimate": "Boligverdi er et estimat — juster i profilen din",
  "forward.emergencyBuffer": "Nødbuffer (3 mnd.)",
  "forward.savingsRate": "Sparerate",

  // Charts
  "charts.disposable": "Disponibelt beløp",
  "charts.average": "Gjennomsnitt",
  "charts.lowest": "Laveste",
  "charts.highest": "Høyeste",
  "charts.monthNames": "Jan,Feb,Mar,Apr,Mai,Jun,Jul,Aug,Sep,Okt,Nov,Des",
  "charts.seasonalTitle": "Forventet disponibelt beløp",
  "charts.seasonalSubtitle": "Estimert basert på sesongsvingninger i danske husholdninger",
  "charts.seasonalDisclaimer": "Basert på gjennomsnittlige sesongsvingninger — ikke dine faktiske tall",

  // AI chat
  "ai.askAbout": "Spør AI om økonomien din",
  "ai.askShort": "Spør AI",
  "ai.limitReached": "Månedlig grense nådd. Nullstilles automatisk neste måned.",

  // Guided saving
  "guided.title": "Guidet sparesession",
  "guided.found": "Funnet",
  "guided.totalFreed": "Totalt frigjort",

  // Share card
  "share.economyCheck": "Økonomi-sjekk",
  "share.freedomNumber": "Frihetstall",
  "share.savingsRate": "Sparerate",
  "share.buffer": "Buffer",
  "share.footer": "Beregnet med NemtBudget · 2026",

  // Subscriptions
  "subs.warning": "Over 2 000 kr/mnd. i abonnementer — vurder å kutte ned",
  "subs.foundInBudget": "Funnet i budsjettet ditt",

  // Profile edit (extra)
  "profile.title": "Rediger opplysningene dine",
  "profile.saved": "Endringer lagret",
  "profile.savedDesc": "Budsjettet ditt er oppdatert.",
  "profile.householdType": "Husstandstype",
  "profile.solo": "Enslig",
  "profile.couple": "Par",
  "profile.yourIncome": "Din inntekt (netto)",
  "profile.postalCode": "Postnummer",
  "profile.rentPayment": "Husleie/betaling",
  "profile.monthlyPayment": "Månedlig boligbetaling",
  "profile.interestRate": "Rente (%)",
  "profile.spending": "Forbruk",
  "profile.restaurantTakeaway": "Restaurant & takeaway",
  "profile.healthMedicine": "Helse & medisin",
  "profile.transport": "Transport",
  "profile.hasCar": "Har bil",
  "profile.carLoan": "Billån (mnd.)",
  "profile.carFuel": "Bensin/lading (mnd.)",
  "profile.carInsurance": "Bilforsikring (mnd.)",
  "profile.subscriptions": "Abonnementer",
  "profile.loansAndSavings": "Lån & Sparing",
  "profile.hasLoan": "Har lån",
  "profile.loanPayment": "Lånebetaling (mnd.)",
  "profile.savesUp": "Sparer",
  "profile.savingsMonthly": "Sparing (mnd.)",
  "profile.insurances": "Forsikringer",
  "profile.insuranceMonthly": "Forsikring (mnd.)",
  "profile.saveChanges": "Lagre endringer",

  // Subscriptions (extra)
  "subs.title": "Abonnementer",
  "subs.addedManually": "Lagt til manuelt",
  "subs.namePlaceholder": "Navn (f.eks. ChatGPT Plus)",
  "subs.pricePlaceholder": "Pris per måned",
  "subs.add": "Legg til",
  "subs.cancel": "Avbryt",
  "subs.addSubscription": "Legg til abonnement",

  // GuidedSaving (extra)
  "guided.goalReached": "Du nådde målet ditt!",
  "guided.goalReachedDesc": "Du frigjorde {amount} kr/mnd. totalt.",
  "guided.skipped": "Hoppet over: {label}",
  "guided.whatIsYourGoal": "Hva er målet ditt?",
  "guided.goalDesc": "Jeg gjennomgår budsjettet ditt og finner de enkleste besparelsene — du bestemmer hva du vil gjøre.",
  "guided.currentDisposable": "Ditt nåværende disponibelt beløp er {amount} kr/mnd.",
  "guided.skip": "Hopp over",
  "guided.apply": "Bruk",
  "guided.goalReachedTitle": "Mål nådd!",
  "guided.sessionDone": "Sesjonen er ferdig",
  "guided.reviewedAll": "Du har gjennomgått alle forslag.",
  "guided.acceptedChanges": "Godkjente endringer",
  "guided.noChanges": "Ingen endringer valgt.",
  "guided.seeUpdated": "Se oppdatert budsjett",
  "guided.undo": "Angre",
  "guided.undoLast": "Angre siste endring",
  "guided.undone": "Angret: {label}",
  "guided.noResponse": "Ingen respons",
  "guided.errorRetry": "Noe gikk galt. Prøv igjen.",
  "guided.goalExtra": "— med {amount} kr. mer vil du ha",
  "guided.findGoal": "Finn {amount}",
  "guided.progressLabel": "{found} / {goal}",
  "guided.withThis": "Med dette: {found} / {goal} funnet",

  // Forward view (extra)
  "forward.wealthProjection": "Formue-projeksjon",
  "forward.years": "år",
  "forward.estimatedWealth": "Estimert formue (bolig)",
  "forward.estDebt": "Est. gjeld (~70%)",
  "forward.netWorth": "Net worth",
  "forward.goalsProgress": "Mål & fremgang",
  "forward.rateShockSim": "Rentesjokk-simulator",
  "forward.vulnerableEconomy": "Sårbar økonomi",
  "forward.refinanceAdvice": "Refinansiering kan redusere eksponeringen deres.",
  "forward.timeline": "Tidslinje — neste 10 år",
  "forward.noEvents": "Ingen store hendelser funnet basert på profilen deres.",

  // ParSplit (extra)
  "couple.desc": "Se hvordan de felles utgiftene kan fordeles rettferdig.",
  "couple.yourIncome": "Din inntekt",
  "couple.expenseDistribution": "Utgiftsfordeling",
  "couple.youPay": "Du betaler",
  "couple.evenSplit": "Jevn fordeling — begge har omtrent like mye til rådighet",
  "couple.youHaveMore": "Du har {amount} kr mer til rådighet enn partneren din",
  "couple.partnerHasMore": "Partneren din har {amount} kr mer til rådighet enn deg",
  "couple.visualization": "Visualisering",
  "couple.tip": "Med inntektsfordelt modell betaler dere relativt til lønnen — prøv den!",

  // AI chat (extra)
  "ai.personalAdvisor": "Din personlige rådgiver",
  "ai.analyzing": "AI analyserer økonomien din...",
  "ai.usedFreeAnswers": "Du har brukt dine 5 gratis AI-svar",
  "ai.createAccount": "Opprett konto — følg med på premium",
  "ai.answersLeft": "AI-svar igjen denne måneden",
  "ai.placeholder": "Still et spørsmål om økonomien din...",

  // History
  "history.noHistory": "Ingen historikk ennå",
  "history.noHistoryDesc": "Historikken din vises her når du har brukt NemtBudget i mer enn en måned. Hver gang du oppdaterer budsjettet, lagrer vi et øyeblikksbilde — slik at du kan se utviklingen over tid.",
  "history.oneSnapshot": "1 øyeblikksbilde lagret · Oppdater budsjettet igjen for å se en graf",
  "history.disposableSinceStart": "Disponibelt beløp siden start",
  "history.healthSinceStart": "Helsescore siden start",
  "history.disposableOverTime": "Disponibelt beløp over tid",
  "history.healthOverTime": "Helsescore over tid",
  "history.calculationsSaved": "{count} beregninger lagret",
  "history.first": "Første",
  "history.latest": "Siste",

  // Editable amount
  "edit.clickToEdit": "Klikk for å redigere",
  "edit.cancel": "Avbryt",
  "edit.save": "Lagre",

  // Onboarding UI
  "onboarding.leftOver": "Til overs",
  "onboarding.seeOverview": "Se oversikt",
  "onboarding.stepOf": "Steg {current} av {total}",

  // Optimize (extra)
  "optimize.opensExternal": "Åpner ekstern side",
  "optimize.savePerMonth": "Spar {amount} kr/mnd.",

  // Auth page
  "auth.pageTitle": "Logg inn — NemtBudget",
  "auth.pageDesc": "Logg inn eller opprett en gratis konto for å synkronisere budsjettet ditt på tvers av enheter.",
  "auth.enterEmail": "Oppgi e-post",
  "auth.enterEmailDesc": "Skriv e-posten din ovenfor, så sender vi en lenke for tilbakestilling.",
  "auth.error": "Feil",
  "auth.checkEmail": "Sjekk e-posten din",
  "auth.checkEmailDesc": "Vi har sendt en lenke for tilbakestilling av passordet ditt.",
  "auth.loginSubtitle": "Logg inn for å synkronisere budsjettet ditt",
  "auth.signupSubtitle": "Opprett konto og lagre budsjettet ditt i skyen",
  "auth.emailPlaceholder": "E-post",
  "auth.passwordPlaceholder": "Passord",
  "auth.waiting": "Vent...",
  "auth.login": "Logg inn",
  "auth.signup": "Opprett konto",
  "auth.forgotPassword": "Glemt passord?",
  "auth.noAccount": "Har du ingen konto? Opprett gratis",
  "auth.hasAccount": "Har du allerede en konto? Logg inn",
  "auth.continueWithout": "← Fortsett uten innlogging",
  "auth.newPasswordSubtitle": "Velg et nytt passord",
  "auth.newPasswordPlaceholder": "Nytt passord",
  "auth.resetPassword": "Tilbakestill passord",
  "auth.passwordMinLength": "Passordet må være minst 6 tegn.",
  "auth.passwordResetSuccess": "Passord oppdatert",
  "auth.passwordResetSuccessDesc": "Passordet ditt er endret. Du kan nå logge inn.",
  "auth.sessionExpired": "Sesjon utløpt",
  "auth.sessionExpiredDesc": "Sesjonen din har utløpt. Logg inn igjen for å synkronisere.",

  // Install page
  "install.pageTitle": "Installer NemtBudget — Gratis budsjett-app",
  "install.pageDesc": "Installer NemtBudget som app på telefonen din — uten app store. Få raskt oversikt over budsjettet ditt.",
  "install.installed": "NemtBudget er installert!",
  "install.title": "Installer NemtBudget",
  "install.installedDesc": "Åpne appen fra hjemmeskjermen for den beste opplevelsen.",
  "install.desc": "Få NemtBudget som app på telefonen din — uten app store.",
  "install.goToApp": "Gå til NemtBudget →",
  "install.installNow": "Installer nå",
  "install.iosTitle": "Slik installerer du på iPhone:",
  "install.iosStep1": "Trykk på",
  "install.iosStep1Share": "Del ↑",
  "install.iosStep1Suffix": "i Safari",
  "install.iosStep2": "Velg \"Legg til på Hjem-skjerm\"",
  "install.iosStep3": "Trykk \"Legg til\"",
  "install.openInBrowser": "Åpne denne siden i Chrome eller Safari for å installere appen.",
  "install.back": "← Tilbake til NemtBudget",

  // NotFound page
  "notFound.title": "404",
  "notFound.message": "Oops! Siden ble ikke funnet",
  "notFound.link": "Tilbake til forsiden",

  // AI Welcome Insight
  "ai.insightLabel": "AI Innsikt",
  "ai.fallback": "Økonomien din er klar for analyse. Gå videre til dashbordet for full oversikt.",

  // NaboeffektView
  "neighbor.aheadOfAvgPar": "Dere er foran gjennomsnittet",
  "neighbor.aheadOfAvgSolo": "Du er foran gjennomsnittet",
  "neighbor.moreLeftPar": "Dere har",
  "neighbor.moreLeftSolo": "Du har",
  "neighbor.moreLeftSuffix": "kr. mer til overs enn andre med din profil.",
  "neighbor.potentialSaving": "Potensiell besparelse:",
  "neighbor.biggestOpportunity": "Største mulighet:",
  "neighbor.overTypical": "kr. over typisk",
  "neighbor.ofIncome": "av inntekten",
  "neighbor.expertsRecommend": "Eksperter anbefaler maks 33% —",
  "neighbor.youUsePar": "dere bruker",
  "neighbor.youUseSolo": "du bruker",
  "neighbor.percentPointMore": "prosentpoeng mer",
  "neighbor.adjustFood": "Juster matbudsjettet",
  "neighbor.seeSavings": "Se spareforslag",
  "neighbor.seeTransport": "Se transportoptimering",
  "neighbor.reviewSubs": "Gjennomgå abonnementer",
  "neighbor.seeLeisure": "Se fritidsbudsjett",
  "neighbor.optimize": "Optimer",
  "neighbor.youLabel": "Deg",
  "neighbor.youLabelPar": "Dere",
  "neighbor.typicalLabel": "Typisk",
  "neighbor.perYear": "kr. i året",
  "neighbor.benchmarkFootnote": "Benchmarks basert på SSB —",
  "neighbor.benchmarkSingles": "enslige",
  "neighbor.benchmarkCouples": "par",
  "neighbor.benchmarkSuffix": "i din inntektsgruppe · 2025",

  // ProfileEditSheet housing types
  "profile.housingLeje": "Leie",
  "profile.housingEjer": "Selveier",
  "profile.housingAndel": "Borettslag",
  "profile.housingUngdomsbolig": "Studentbolig",
  "profile.netflix": "Netflix (149 kr.)",
  "profile.spotify": "Spotify (109 kr.)",
  "profile.hboMax": "HBO Max (99 kr.)",
  "profile.viaplay": "Viaplay (99 kr.)",
  "profile.disneyPlus": "Disney+ (99 kr.)",
  "profile.appleTvPlus": "Apple TV+ (59 kr.)",
  "profile.amazonPrime": "Amazon Prime (89 kr.)",

  // FremadView extras
  "forward.expectedWealth": "Forventet formue",
  "forward.interestLabel": "Rente:",
  "forward.ofGoal": "av mål",
  "forward.goalLabel": "mål",
  "forward.exceedsRecommendation": "Du overstiger anbefalingen!",
  "forward.currentLabel": "Nåværende",
  "forward.leftAfter": "kr. igjen",
  "forward.mortgageSearch": "oliglån",
  "forward.seeRefinance": "Se hva refinansiering kan gjøre →",

  // ShareCard
  "share.brandName": "NemtBudget",
  "share.brandUrl": "nemtbudget.nu",
  "share.bucketDrift": "Drift",
  "share.bucketFrihed": "Frihet",
  "share.bucketFremtid": "Fremtid",
  "share.bucketRisiko": "Risiko",

  // Units (extra)
  "unit.krKwh": "kr/kWh",
  "unit.possible": "mulig",

  // LossAversionInsights
  "insights.heading": "Innsikt basert på tallene dine",
  "insights.incomeBadge": "Inntekt vs. nabolag",
  "insights.neighborLabel": "nabolaget",
  "insights.incomeBelow": "Du tjener {amount} kr./md. under gjennomsnittet i {postal}",
  "insights.incomeBelowValue": "−{amount} {unit}/år",
  "insights.incomeBelowSub": "Gjennomsnittsinntekten i {neighborLabel} er {avg} kr./md. etter skatt. Det er ikke nødvendigvis et problem — men det er verdt å vite. (Kilde: {source})",
  "insights.incomeAbove": "Du tjener {amount} kr./md. over gjennomsnittet i {postal}",
  "insights.incomeAboveValue": "+{amount} {unit}/år",
  "insights.incomeAboveSub": "Gjennomsnittsinntekten i {neighborLabel} er {avg} kr./md. etter skatt. Du er altså over midten — utnytter budsjettet ditt det fullt ut? (Kilde: {source})",
  "insights.subsBadge": "Abonnementer pr. år",
  "insights.subsTitle": "{count} strømmetjenester koster {amount} kr. i året",
  "insights.subsSub": "De fleste bruker 1-2 aktivt. Koster de hver for seg: Netflix {netflix}, Viaplay {viaplay}, HBO {hbo} kr./år. Roterer du, er det penger å spare.",
  "insights.savingsBadge": "Sparemulighet",
  "insights.savingsTitle": "Du har {amount} kr./md. til overs — men sparer ingenting",
  "insights.savingsSub": "{monthly} kr./md. i et globalt indeksfond (historisk ~7%/år) gir {total} kr. om 15 år med renters rente. For hver måned som går uten sparing mister du dette potensialet.",
  "insights.elCheapNowBadge": "Strøm billigst nå ⚡",
  "insights.elCheapBadge": "Billigste strøm i dag",
  "insights.elCheapNowTitle": "Strøm er billigst nå ({price} kr/kWh) — start oppvaskmaskinen og tørketrommelen",
  "insights.elScheduleTitle": "Start oppvaskmaskin og vaskemaskin kl. {hours}",
  "insights.elSavingSub": "{saving} kr/kWh billigere enn det dyreste tidspunktet i dag. Kjører du tørketrommel (2 kWh) til {cheap} vs {expensive} kr/kWh sparer du {total} kr. på én runde. (Live data: Energi Data Service)",
  "insights.elLiveSub": "Basert på live Elspot-data fra Energi Data Service, oppdatert i dag.",

  // B2B page
  "b2b.heroTag": "B2B Partnership",
  "b2b.heroTitle": "Gi kundene deres Norges smarteste",
  "b2b.heroTitleHighlight": "budsjettverktøy",
  "b2b.heroTitleSuffix": "— under deres eget merke",
  "b2b.heroSubtitle": "NemtBudget er en AI-drevet budsjettplattform klar for white-label. Integrer den i kundeopplevelsen på under 2 uker — ingen banktilkobling påkrevd.",
  "b2b.liveDemo": "Se live demo",
  "b2b.contactUs": "Kontakt oss",
  "b2b.whyTitle": "Hvorfor banker velger NemtBudget",
  "b2b.whiteLabelReady": "White-label klar",
  "b2b.whiteLabelDesc": "Deres logo, farger og merkevare. Kundene opplever det som deres eget produkt. Ingen synlig referanse til NemtBudget.",
  "b2b.aiPowered": "AI-drevet",
  "b2b.aiPoweredDesc": "Personlige anbefalinger, optimeringsforslag og intelligent chat. Powered by Claude — verdens mest avanserte AI.",
  "b2b.privacyFirst": "Privacy-first",
  "b2b.privacyFirstDesc": "Ingen banktilkobling nødvendig. Brukerne taster selv — full kontroll, ingen compliance-hodepine.",
  "b2b.featureTitle": "Alt kundene deres trenger",
  "b2b.featureSubtitle": "Cockpit-oversikt, Sankey-flyt, AI-optimering, fremtidsprojeksjon og mye mer.",
  "b2b.feat.cockpit": "Budsjett-cockpit",
  "b2b.feat.cockpitDesc": "Oversikt over inntekt, utgifter og disponibelt på ett dashboard.",
  "b2b.feat.sankey": "Sankey-diagram",
  "b2b.feat.sankeyDesc": "Visualiser pengestrømmer fra inntekt til utgifter.",
  "b2b.feat.aiOpt": "AI-optimering",
  "b2b.feat.aiOptDesc": "Personlige forslag til besparelser basert på brukerens profil.",
  "b2b.feat.projection": "Fremtidsprojeksjon",
  "b2b.feat.projectionDesc": "Se hvordan økonomien utvikler seg over 1-5 år.",
  "b2b.feat.stress": "Stress-test",
  "b2b.feat.stressDesc": "Hva skjer ved renteøkning eller jobbbytte?",
  "b2b.feat.neighbor": "Naboeffekten",
  "b2b.feat.neighborDesc": "Sammenlign med andre i samme postnummer.",
  "b2b.brandTitle": "Se det i deres merke",
  "b2b.brandSubtitle": "Prøv våre live demoer med Nordea og Danske Bank merkevare.",
  "b2b.pricingTitle": "Enkel og gjennomsiktig prising",
  "b2b.pricingSubtitle": "Alle planer inkluderer oppsett, white-label design, drift og support.",
  "b2b.mostPopular": "Mest populær",
  "b2b.getStarted": "Kom i gang",
  "b2b.starter.users": "Opptil 10 000 brukere",
  "b2b.starter.f1": "White-label design",
  "b2b.starter.f2": "Oppsett & onboarding",
  "b2b.starter.f3": "Drift & hosting",
  "b2b.starter.f4": "E-post-support",
  "b2b.starter.f5": "Månedlig rapport",
  "b2b.growth.users": "Opptil 50 000 brukere",
  "b2b.growth.f1": "Alt i Starter",
  "b2b.growth.f2": "AI-rådgivning",
  "b2b.growth.f3": "Prioritert support",
  "b2b.growth.f4": "Tilpassede integrasjoner",
  "b2b.growth.f5": "Kvartalsvise gjennomgangsmøter",
  "b2b.enterprise.price": "Kontakt oss",
  "b2b.enterprise.users": "Ubegrenset brukere",
  "b2b.enterprise.f1": "Alt i Growth",
  "b2b.enterprise.f2": "Dedikert kontaktperson",
  "b2b.enterprise.f3": "SLA-garanti",
  "b2b.enterprise.f4": "On-premise mulighet",
  "b2b.enterprise.f5": "API-tilgang",
  "b2b.testimonialTitle": "Hva partnerne våre sier",
  "b2b.testimonialQuote": "Vi er i gang med å onboarde våre første bankpartnere. Kontakt oss for referanser.",
  "b2b.testimonialLink": "Kontakt oss for referanser",
  "b2b.contactTitle": "Kontakt oss",
  "b2b.contactSubtitle": "Fyll ut skjemaet, så kommer vi tilbake innen 24 timer.",
  "b2b.thankYou": "Takk for henvendelsen!",
  "b2b.thankYouDesc": "E-postklienten din åpner nå med en forhåndsutfylt melding. Vi kommer tilbake så raskt som mulig.",
  "b2b.labelName": "Navn",
  "b2b.labelCompany": "Bedrift",
  "b2b.labelEmail": "E-post",
  "b2b.labelMessage": "Melding",
  "b2b.placeholderName": "Ditt navn",
  "b2b.placeholderCompany": "Bedriftens navn",
  "b2b.placeholderMessage": "Fortell oss om behovene deres...",
  "b2b.submit": "Send henvendelse",
  "b2b.emailSubject": "B2B-henvendelse fra {company}",

  // Partner page
  "partner.noToken": "Ingen token",
  "partner.invalidToken": "Ugyldig token",
  "partner.contactEmail": "Kontakt hej@nemtbudget.nu",
  "partner.noActivity": "Ingen aktivitet ennå",
  "partner.noEvents": "Ingen hendelser ennå",
  "partner.uniqueSessions": "Unike sesjoner",
  "partner.uniqueSessionsSub": "Unike brukere som har åpnet verktøyet",
  "partner.budgetsCreated": "Budsjetter opprettet",
  "partner.conversion": "{pct}% konvertering",
  "partner.aiQuestions": "AI-spørsmål",
  "partner.aiQuestionsSub": "Spørsmål til AI-rådgiveren",
  "partner.reports": "Rapporter",
  "partner.reportsSub": "Nedlastede finansrapporter",
  "partner.dailyActivity": "Daglig aktivitet — siste 30 dager",
  "partner.memberUsage": "Hva bruker medlemmene dine?",
  "partner.event.onboarding_start": "Startet onboarding",
  "partner.event.onboarding_complete": "Gjennomførte budsjettberegning",
  "partner.event.dashboard_view": "Åpnet dashboard",
  "partner.event.ai_chat_open": "Åpnet AI-rådgiveren",
  "partner.event.ai_message_sent": "Stilte spørsmål til AI",
  "partner.event.report_generated": "Genererte finansrapport",
  "partner.embedTitle": "Integrasjon — embed-kode",
  "partner.embedSub": "Virker i enhver webportal på 5 minutter",
  "partner.copyCode": "Kopier kode",
  "partner.dashboard": "Partner Dashboard",

  // Blog page
  "blog.searchPlaceholder": "Søk i guider...",
  "blog.readTime": "lesetid",
  "blog.headerTitle": "Guider & tips",
  "blog.heroTitle": "Bli smartere på økonomien din",
  "blog.heroSubtitle": "Praktiske guider, sparetips og beregninger bygget for norsk privatøkonomi.",
  "blog.ctaTitle": "Prøv {brand} gratis",
  "blog.ctaSubtitle": "Beregn disponibelt beløp på 3 minutter",
  "blog.ctaButton": "Kom i gang →",

  // Article page
  "article.guides": "Guider",
  "article.ctaTitle": "Beregn ditt eget disponibelt beløp",
  "article.ctaSubtitle": "Gratis · 3 minutter · Ingen innlogging",
  "article.ctaButton": "Prøv {brand} →",

  // Onboarding extras
  "onboarding.perMonthAfterExpenses": "per måned etter alle utgifter",
  "onboarding.estimatedAdjust": "Vi har estimert disse — rett dem hvis de ikke stemmer",
  "onboarding.everydayExpenses": "Hverdagsutgifter",
  "onboarding.ofIncome": "av inntekt",

  // Dashboard extras
  "dash.sectionTabs": "Seksjonsfaner",

  // FremadView timeline events
  "forward.childN": "Barn",
  "forward.yourChild": "Barnet ditt",
  "forward.startsSFO": "begynner på SFO",
  "forward.sfoDesc": "SFO-utgift ca. 2 000 kr./md.",
  "forward.leavesKindergarten": "slutter i barnehage",
  "forward.kindergartenDesc": "Barnehageutgift faller 3 315 kr./md.",
  "forward.turns7": "fyller 7 – barnetrygd reduseres",
  "forward.turns7Desc": "Reduseres med barnetrygd.",
  "forward.leavesSFO": "ut av SFO",
  "forward.leavesSFODesc": "SFO-utgift bortfaller.",
  "forward.turns18": "fyller 18",
  "forward.childBenefitEnds": "Barnetrygd bortfaller (1 766 kr./md.).",
  "forward.checkInterestOnly": "Sjekk avdragsfrihet",
  "forward.checkInterestOnlyDesc": "Mange lån fra 2018–2020 har 10-årig avdragsfrihet.",
  "forward.basedOnInvested": "Basert på {amount} investert",
  "forward.projectionPrefix": "med 7% årlig avkastning gir estimert ca.",
  "forward.projectionMid": "på 5 år og ca.",
  "forward.projectionSuffix": "på 10 år. Investering innebærer risiko.",
  "forward.increaseToReach20": "Øk med {amount} for å nå 20%",
  "unit.krMonth": "kr./md.",
  "unit.krYear": "kr./år",
  "unit.currency": "kr.",

  // AIChatPanel suggestion questions
  "ai.q.christmasBudget": "Hvordan klarer budsjettet mitt julen?",
  "ai.q.summerSavings": "Kan jeg spare til sommerferie?",
  "ai.q.switchInsurance": "Bør jeg bytte forsikring ved fornyelse?",
  "ai.q.cutMost": "Hvor kan jeg kutte mest?",
  "ai.q.carCost": "Hva koster bilen min egentlig?",
  "ai.q.dropStreaming": "Hvilken strømmetjeneste kan jeg droppe?",
  "ai.q.rateRise": "Hva hvis renten stiger 2%?",
  "ai.q.startSaving": "Hvordan begynner jeg å spare?",

  // Dashboard terms link
  "dash.termsLink": "Vilkår",

  // Subscriptions (units)
  "subs.activeCount": "aktive abonnementer",

  // Optimization (units)
  "optimize.perYearFollowPlan": "ved å følge planen",

  // Couple split
  "couple.remaining.suffix": "igjen",

  // History
  "history.points": "poeng",
  "history.tooltipDisposable": "Disponibelt",

  // Onboarding
  "onboarding.adjustAmount": "Rett beløpet ovenfor hvis det ikke stemmer.",
  "onboarding.emailReminder": "Ja takk, send meg en kvartalsvis påminnelse om å sjekke budsjettet.",
  "onboarding.emailUnsubscribe": "Du kan alltid melde deg av.",
  "onboarding.expenseShare": "Utgiftsandel",
  "onboarding.encourage.income": "Flott! Nå vet vi hvem du er 🎯",
  "onboarding.encourage.housing": "Bra klart — nå tar vi boligen 🏠",
  "onboarding.encourage.expenses": "Halvveis! Boligen er på plass ✅",
  "onboarding.encourage.review": "Siste steg — du er nesten i mål! 🏁",

  // Error boundary
  "error.somethingWrong": "Noe gikk galt",
  "error.unexpectedError": "Det oppstod en uventet feil. Prøv å laste siden på nytt.",
  "error.reloadPage": "Last siden på nytt",

  // Section error boundary
  "error.sectionFailed": "kunne ikke vises",
  "error.tryReload": "Prøv å laste siden på nytt",
  "error.tryAgain": "Prøv igjen",

  // Page loader
  "loader.loading": "Laster...",

  // Demo banner
  "demo.text": "Demo — NemtBudget white-label for {brand}. All data er eksempeldata.",
  "demo.bookPresentation": "Book presentasjon",
  "demo.trySelf": "Prøv selv",
  "demo.closeBanner": "Lukk demo-banner",

  // Suite nav
  "nav.comingSoon": "Snart",

  // Dark mode toggle
  "darkMode.switchToLight": "Bytt til lyst tema",
  "darkMode.switchToDark": "Bytt til mørkt tema",

  // Cookie banner
  "cookie.consent": "Informasjonskapsel-samtykke",
  "cookie.acceptAnalytics": "Aksepter analyse-informasjonskapsler",
  "cookie.declineAnalytics": "Avvis analyse-informasjonskapsler",

  // Cockpit
  "cockpit.alertsLabel": "Varsler",
  "cockpit.critical": "Kritisk",
  "cockpit.warning": "Advarsel",
  "cockpit.insight": "Innsikt",

  // Share card
  "share.bufferUnit": "mnd.",

  // Share budget deep-link
  "share.title": "Del budsjettet ditt",
  "share.description": "Legg til kontekst slik at andre forstår situasjonen din",
  "share.copyLink": "Kopier",
  "share.copied": "Kopiert!",
  "share.privacyNote": "Lenken inneholder kun tallene og konteksten du velger — ingen postnummer, e-post eller persondata deles.",
  "share.reddit": "Del på r/dkfinance",
  "share.chars": "tegn",
  "share.autoContext": "Profilen din viser automatisk",
  "share.addContext": "Legg til kontekst (valgfritt)",
  "share.agePlaceholder": "Alder",
  "share.jobPlaceholder": "Stilling",
  "share.cityPlaceholder": "By",
  "share.questionPlaceholder": "Hva vil du gjerne ha tilbakemelding på?",
  "share.generateLink": "Generer delingslenke",
  "share.generating": "Genererer...",
  "share.tagSolo": "Singel",
  "share.tagCouple": "Par",
  "share.tagChildren": "{count} barn ({ages})",
  "share.tagRenter": "Leietaker",
  "share.tagOwner": "Eier",
  "share.tagCoop": "Borettslag",
  "share.tagCar": "Bil",
  "share.tagSaves": "Sparer",
  "share.tagYears": "år",
  "share.preview": "Slik ser det ut for mottakeren",
  "share.q.canBuyHome": "Kan jeg/vi kjøpe bolig?",
  "share.q.refinance": "Bør jeg refinansiere lånet?",
  "share.q.tooMuchStreaming": "Bruker jeg for mye på strømming?",
  "share.q.carWorth": "Er bilbudsjettet mitt fornuftig?",
  "share.q.canAffordCar": "Har jeg råd til bil?",
  "share.q.howToSave": "Hvordan begynner jeg å spare?",
  "share.q.savingsEnough": "Sparer jeg nok?",
  "share.q.maternity": "Klarer vi oss på foreldrepermisjon?",
  "share.q.generalFeedback": "Vurder budsjettet mitt!",
  "share.payslipToggle": "Legg til lønnsslipp",
  "share.payslipTitle": "Lønnsslipp",
  "share.payslipHint": "Legg til bruttolønnen din for å vise hva som skjer med lønnen før den treffer kontoen.",
  "share.ps.gross": "Bruttolønn",
  "share.ps.grossLabel": "Bruttolønn (kr/mnd)",
  "share.ps.amBidrag": "Arb.avg. (8%)",
  "share.ps.pension": "Pensjon",
  "share.ps.pensionLabel": "Pensjon",
  "share.ps.tax": "Skatt",
  "share.ps.taxLabel": "Trekkprosent",
  "share.ps.atp": "ATP",
  "share.ps.net": "Utbetalt",
  "share.ps.netShort": "netto",
  "share.modeLink": "Lenke",
  "share.modeImage": "Bilde",
  "share.nativeShare": "Del...",
  "share.shareImage": "Del bilde",
  "share.copyText": "Kopier som tekst",
  "share.copiedText": "Tekst kopiert!",
  "share.textHeader": "Mitt budsjett",
  "share.textFooter": "Beregnet med nemtbudget.nu",
  "shared.banner": "Delt budsjett",
  "shared.bannerCta": "Lag ditt eget budsjett",
  "shared.closeBanner": "Lukk banner",
  "dash.share": "Del",

  // Payslip upload
  "payslip.title": "Last opp lønnsslippen din",
  "payslip.subtitle": "Ta et bilde eller last opp en PDF — AI-en leser den og anonymiserer alt automatisk",
  "payslip.dropzone": "Dra filen hit, klikk for å velge, eller lim inn med Ctrl+V",
  "payslip.pasteHint": "Tips: Du kan også bare trykke Ctrl+V med et skjermbilde i utklippstavlen",
  "payslip.acceptedFormats": "JPG, PNG eller PDF (maks 5 MB)",
  "payslip.privacy": "Bildet ditt sendes kryptert for analyse og slettes umiddelbart etter. Vi lagrer verken bildet eller dataen din.",
  "payslip.processing": "Leser lønnsslippen din...",
  "payslip.processingHint": "AI-en analyserer tall, fradrag og kontekst",
  "payslip.step1": "Last opp bilde eller PDF",
  "payslip.step2": "AI leser alle tall",
  "payslip.step3": "Anonymisert og klar til deling",
  "payslip.result.title": "Din lønnsslipp",
  "payslip.result.employer": "Arbeidsgiver",
  "payslip.result.municipality": "Kommune",
  "payslip.result.payrollSystem": "Lønnssystem",
  "payslip.result.confidenceHigh": "Høy sikkerhet",
  "payslip.result.confidenceMedium": "Middels sikkerhet",
  "payslip.result.confidenceLow": "Lav sikkerhet",
  "payslip.privateInfo": "Privat info (deles ikke)",
  "payslip.privateNote": "Denne informasjonen vises bare til deg og inkluderes aldri ved deling",
  "payslip.cta.share": "Del anonymt",
  "payslip.cta.budget": "Lag fullt budsjett",
  "payslip.cta.retry": "Prøv igjen",
  "payslip.error.tooLarge": "Filen er for stor (maks 5 MB)",
  "payslip.error.invalidType": "Ugyldig filtype — bruk JPG, PNG eller PDF",
  "payslip.error.readFailed": "Kunne ikke lese lønnsslippen — prøv et tydeligere bilde",
  "payslip.deductions.gross": "Bruttolønn",
  "payslip.deductions.net": "Utbetalt",
  "payslip.deductions.amBidrag": "Arbeidsgiveravgift",
  "payslip.deductions.pension": "Pensjon",
  "payslip.deductions.aSkat": "Skatt",
  "payslip.deductions.atp": "ATP",
  "payslip.deductions.union": "Fagforening",
  "payslip.deductions.healthIns": "Helseforsikring",
  "payslip.deductions.fritvalg": "Frivalgskonto",
  "payslip.deductions.feriepenge": "Feriepenger",
  "payslip.deductions.other": "Øvrige fradrag",
  "payslip.shareHeader": "Min lønnsslipp",
  "payslip.shareKeepPct": "Jeg beholder {pct}% av bruttolønnen min",
  "payslip.welcomeCta": "Har du en lønnsslipp? Last den opp og se budsjettet ditt på 10 sekunder",

  // Index page
  "confirm.resetBudget": "Er du sikker? Dette sletter det nåværende budsjettet og starter på nytt.",
  "confirm.editProfile": "Vil du redigere opplysningene dine? Nåværende data brukes som utgangspunkt.",

  // Admin
  "admin.title": "SEO Innholdskø",
  "admin.draftsAwait": "utkast venter på godkjenning",
  "admin.refresh": "Oppdater",
  "admin.emptyQueue": "Ingen utkast i kø. Neste artikkel genereres automatisk.",
  "admin.readTime": "lesetid",
  "admin.approve": "Godkjenn",
  "admin.reject": "Avvis",
  "admin.published": "Artikkel publisert!",
  "admin.rejected": "Utkast avvist",
  "admin.error": "Feil",

  // Salary comparison (payslip result page)
  "salary.comparison": "Lønnssammenligning",
  "salary.yourGross": "Din bruttolønn",
  "salary.industryMedian": "Median for {industry}",
  "salary.percentile": "Du ligger i {pct}. persentil",
  "salary.aboveMedian": "over medianen",
  "salary.belowMedian": "under medianen",
  "salary.atMedian": "rundt medianen",
  "salary.fewObservations": "Basert på få observasjoner — vis med forbehold",
  "salary.contributeTitle": "Hjelp andre med lønnsgjennomsiktighet",
  "salary.contributeDesc": "Del dine anonyme lønnsdata slik at andre kan sammenligne. Ingen persondata deles.",
  "salary.contributed": "Takk! Dine anonyme lønnsdata er registrert.",
  "salary.noData": "Ikke nok data for din bransje ennå",

  // Payslip image export
  "payslip.exportImage": "Del som bilde",
  "payslip.downloadImage": "Last ned bilde",
  "payslip.exportImageDesc": "Perfekt for Reddit",
  "payslip.keepPct": "Jeg beholder {pct}% av min bruttolønn",
  "payslip.imageCopied": "Bilde kopiert!",
  "payslip.imageDownloaded": "Bilde lastet ned!",
  "payslip.shareToReddit": "Del på r/dkloenseddel",
  "payslip.card.grossPay": "Bruttolønn",
  "payslip.card.totalDeductions": "Fradrag totalt",
  "payslip.card.netPay": "Nettolønn",
  "payslip.card.deductionBreakdown": "Fradrag",
  "payslip.card.madeWith": "Laget med",
  "payslip.card.cta": "Lag din egen gratis",
  "payslip.card.rankBadge": "Topp {pct}% i {industry}",
  "payslip.card.heroSubtitle": "utbetalt av din bruttolønn",
  "payslip.card.budgetSection": "Mitt budsjett",
  "payslip.share.sectionTitle": "Del på Reddit",
  "payslip.share.step1": "Kopier bilde",
  "payslip.share.step2": "Åpne Reddit",
  "payslip.share.step2Hint": "Lim inn bildet med Ctrl+V i Reddit-innlegget",
  "payslip.share.includeBudget": "Inkluder budsjettet mitt i bildet",
  "salary.autoContributed": "Din anonyme lønnsdata hjelper andre med å sammenligne",
  "payslip.meta.title": "Forstå lønnsslippen din på 10 sekunder — nemtbudget.nu",
  "payslip.meta.description": "Last opp lønnsslippen og forstå hvert eneste fradrag. Se hva AM-bidrag, A-skatt og pensjon betyr — og om lønnen din er normal for bransjen.",
  "payslip.landing.headline": "Forstå lønnsslippen din på 10 sekunder",
  "payslip.landing.subheadline": "Last opp lønnsslippen — vi forklarer hvert fradrag, sjekker om lønnen din er normal, og du kan dele anonymt på Reddit",
  "payslip.landing.socialProof": "73.000+ ukentlige besøkende på r/dkloenseddel vil forstå lønnsslippen sin",

  "payslip.explain.amBidrag": "AM-bidrag (arbeidsmarkedsbidrag) er en skatt på 8% som finansierer dagpenger, sykepenger og arbeidsmarkedsutdanning. Alle lønnstakere betaler det — det er det første som trekkes fra lønnen din.",
  "payslip.explain.pension": "Pensjonsopsparingen din består typisk av et arbeidstakerbidrag + et arbeidsgiverbidrag. Pengene investeres og utbetales når du går av med pensjon. Jo høyere pensjonsprosent, jo mer sparer du.",
  "payslip.explain.aSkat": "A-skatt er inntektsskatten din beregnet ut fra trekkprosenten og personfradraget ditt. Trekkprosenten avhenger av kommunen din, kirkeskatt og rentefradrag.",
  "payslip.explain.atp": "ATP (Arbeidsmarkedets Tilleggspensjon) er en lovpålagt pensjonsordning. Du betaler 1/3 og arbeidsgiveren din 2/3. Det gir en liten garantert pensjon oppå folkepensjon.",
  "payslip.explain.fagforening": "Fagforeningskontingent dekker den faglige organisasjonen din. De forhandler overenskomsten din (lønn, ferie, oppsigelsesvilkår) og kan hjelpe ved problemer på arbeidsplassen.",
  "payslip.explain.sundhedsforsikring": "En helseforsikring betalt via lønnen din — typisk en firmapolitikk. Gir raskere tilgang til spesialister, fysioterapi og psykolog uten å vente i det offentlige systemet.",
  "payslip.explain.fritvalg": "Fritvalgskonto er en sparekonto fra overenskomsten din. Du kan typisk bruke pengene til ekstra ferie, pensjon eller utbetaling. Prosentsatsen er avtalt i overenskomsten.",
  "payslip.explain.feriepenge": "Feriepenger er 12,5% av lønnen din som settes av til ferie. Du får dem utbetalt når du tar ferie.",

  "payslip.range.amBidrag": "Alltid 8% av inntektsgrunnlaget — dette er fast for alle",
  "payslip.range.pension": "Typisk 12-17% totalt (din + arbeidsgivers andel). Under 8% er lavt.",
  "payslip.range.aSkat": "Normal trekkprosent: 35-42%. Lavere med store rentefradrag, høyere i dyre kommuner.",
  "payslip.range.atp": "Fast 99,45 kr/md for heltid (din andel). Alltid det samme beløpet.",
  "payslip.range.fagforening": "Typisk 300-600 kr/md. Varierer etter fagforening og forsikringsvalg.",
  "payslip.range.sundhedsforsikring": "Typisk 50-200 kr/md. Arbeidsgiverbetalt gode.",
  "payslip.range.fritvalg": "Typisk 1-7% av lønn avhengig av overenskomst.",
  "payslip.range.feriepenge": "12,5% av ferieberettiget lønn. Lovbestemt sats.",

  // Hero-seksjon
  "payslip.hero.youKeep": "Du beholder",
  "payslip.hero.paidOut": "utbetalt",
  "payslip.hero.annual": "Det tilsvarer {amount} i året",
  "payslip.hero.gross": "Bruttolønn: {monthly}/md · {annual}/år",

  // Seksjonsoverskrifter
  "payslip.section.breakdown": "Fra bruttolønn til utbetaling",
  "payslip.section.insights": "3 ting du bør vite",

  // Innsikt-statusetiketter
  "payslip.insight.aboveNormal": "over normalen",
  "payslip.insight.belowNormal": "under normalen",

  // Detaljerte innsikter
  "payslip.insight.effectiveTax": "Effektiv skattesats",
  "payslip.insight.effectiveTaxDetail": "Trekkprosenten din er {marginal}%, men din reelle skattesats er {effective}% av brutto (AM-bidrag + A-skatt + ATP). Personfradrag: {personfradrag}/md.",
  "payslip.insight.pensionTitle": "Pensjonshelse",
  "payslip.insight.pensionDetail": "Pensjonen din er {pct}% (deg: {employee} + arbeidsgiver: {employer}). Gjennomsnittet er 12-17%.",
  "payslip.insight.pensionLow": "Det er under gjennomsnittet — vurder å øke pensjonsinnbetalingen.",
  "payslip.insight.pensionGood": "Flott! Pensjonen din er over gjennomsnittet.",
  "payslip.insight.annualTitle": "Årsoppgjør",
  "payslip.insight.annualDetail": "Over 12 måneder: {gross} brutto → {deductions} i skatt/fradrag → {net} utbetalt.",

  // Pensjon & skatt detaljer
  "payslip.pension.employerContrib": "Deg: {employee} + Arbeidsgiver: {employer}",
  "payslip.tax.traekprocent": "Trekkprosent",
  "payslip.tax.personfradrag": "Personfradrag",

  // Teaserkort
  "payslip.teaser.title": "Delingskortet ditt er klart",
  "payslip.teaser.subtitle": "Del anonymt på Reddit — ingen persondata",

  // Verifikasjonsskjerm
  "payslip.verify.title": "Vi fant disse postene på lønnsslippen din",
  "payslip.verify.subtitle": "Stemmer tallene? Trykk på blyanten for å rette.",
  "payslip.verify.confirm": "Ser riktig ut",
  "payslip.verify.retry": "Last opp igjen",
  "payslip.verify.rawLines": "Rålinjer fra lønnsslippen",

  // Lønnssammenligning
  "payslip.salary.dstSource": "Basert på Danmarks Statistik 2025",
  "payslip.salary.yourGross": "Din bruttolønn",
  "payslip.salary.difference": "Forskjell",
  "payslip.salary.showAll": "Vis alle bransjer",
  "payslip.salary.showFewer": "Vis færre",
  "payslip.ctaTitle": "Har du en lønnsslipp?",
  "payslip.ctaDesc": "Last opp lønnsslipp-bildet ditt og få en komplett analyse med fradrag, lønnssammenligning og delbart bilde.",

  // Accessibility
  "a11y.chartSummary": "Diagramoversikt",
  "a11y.sankeyTable": "Budsjettflyt",
  "a11y.historyDisposable": "Disponibelt beløp over tid",
  "a11y.historyScore": "Helsescore over tid",
  "a11y.partnerSplit": "Utgiftsfordeling mellom partnere",
  "a11y.bucketChart": "Budsjettfordeling etter kategori",
};
