// English texts — optional runtime language switch on any build
export const EN: Record<string, string> = {
  // Nav
  "nav.products": "Products",
  "nav.howItWorks": "How it works",
  "nav.back": "Back",
  "nav.budget": "Budget",
  "nav.coupleFinance": "Couple finance",
  "nav.childTax": "Child tax",
  "nav.cockpit": "Cockpit",
  "nav.overview": "Overview",
  "nav.action": "Action",
  "nav.future": "Future",
  "nav.advanced": "In-depth",

  // Hero
  "hero.title": "Take control of",
  "hero.titleHighlight": "your finances.",
  "hero.subtitle": "Find hidden expenses, see what you really have left and be prepared for the future — free, private and in 3 minutes.",
  "hero.cta": "Check your finances for free",
  "hero.imageAlt": "Personal finance and budget overview",

  // Trust
  "trust.danish": "Built for Danish finance",
  "trust.time": "Done in 3 minutes",
  "trust.private": "100% private · Data stored locally",

  // How it works
  "howItWorks.title": "Get the full picture in 3 minutes",
  "howItWorks.subtitle": "No spreadsheets. Answer yes/no — we handle the rest.",

  // Stats
  "stats.3min": "3 min",
  "stats.fillIn": "To complete",
  "stats.avgSaving": "Avg. savings/mo.",
  "stats.freePrivate": "Private & free",

  // Features
  "feature.findHidden": "Find hidden expenses",
  "feature.findHiddenDesc": "We review streaming, insurance and transport — and show what's eating your budget.",
  "feature.aiInsight": "AI insights",
  "feature.aiInsightDesc": "Analysis of your numbers and spending patterns.",
  "feature.compare": "Compare with others",
  "feature.compareDesc": "See your finances compared to others in your area and income bracket.",
  "feature.bankReport": "Bank meeting report",
  "feature.bankReportDesc": "Take a professional report to your bank advisor.",
  "feature.stressTest": "Stress-test your finances",
  "feature.stressTestDesc": "What happens with job loss, rate hikes or inflation? See your resilience.",

  // Testimonials
  "testimonials.title": "What others say",

  // Bottom CTA
  "bottomCta.title": "Ready to get started?",
  "bottomCta.subtitle": "It only takes 3 minutes — and it's completely free.",
  "bottomCta.noLogin": "No login · No data shared · Everything stored locally",

  // Footer
  "footer.tagline": "Get a complete overview of your finances. Free, private and built for Danish conditions.",
  "footer.product": "Product",
  "footer.budgetCalc": "Budget calculator",
  "footer.neighborComp": "Neighbor comparison",
  "footer.info": "Information",
  "footer.privacy": "Privacy policy",
  "footer.terms": "Terms & conditions",
  "footer.contact": "Contact",
  "footer.about": "About",
  "footer.private": "100% private · Data stored locally",
  "footer.tools": "Tools",
  "footer.legal": "Legal",
  "footer.disclaimer": "Kassen is a budgeting tool and does not provide financial advice. Talk to your bank or an advisor about specific financial decisions.",
  "footer.based": "Based on Danish averages 2026 · Data stored locally",
  "footer.installApp": "Install app",
  "footer.guides": "Guides & tips",

  // Onboarding — household
  "step.household.title": "Who is in the household?",
  "step.household.subtitle": "We tailor all estimates to your situation.",
  "step.household.solo": "Just me",
  "step.household.soloSub": "Single household",
  "step.household.couple": "Two of us",
  "step.household.coupleSub": "Couple / cohabiting",

  // Onboarding — income
  "step.income.titleSolo": "What is your income?",
  "step.income.titleCouple": "What is your combined income?",
  "step.income.subtitle": "Monthly after-tax payout.",
  "step.income.myIncome": "Monthly income",
  "step.income.myIncomePar": "Your income",
  "step.income.partnerIncome": "Partner's income",
  "step.income.otherIncome": "Other income",
  "step.income.placeholder": "E.g. Bonus, grants, child benefits",
  "step.income.amount": "Amount",
  "step.income.addSource": "Add income source",
  "step.income.total": "Total income",
  "step.income.tipSolo": "Average income for singles in Denmark is approx. 27,000 DKK/mo. after tax.",
  "step.income.tipCouple": "Average household income for couples in Denmark is approx. 52,000 DKK/mo. after tax.",
  "step.income.netTip": "Enter salary after tax (net — what you receive)",

  // Onboarding — housing
  "step.housing.title": "Housing situation",
  "step.housing.subtitle": "We estimate based on postal code — adjust freely.",
  "step.housing.renter": "Renter",
  "step.housing.coop": "Co-op",
  "step.housing.owner": "Owner",
  "step.housing.postalCode": "Postal code",
  "step.housing.postalPlaceholder": "E.g. 2100",
  "step.housing.rent": "Monthly rent",
  "step.housing.coopFee": "Monthly housing fee",
  "step.housing.coopLoan": "Co-op loan (payments + interest)",
  "step.housing.mortgage": "Monthly mortgage payment",
  "step.housing.propertyValue": "Estimated property value",
  "step.housing.interestRate": "Loan interest rate",

  // Onboarding — children
  "step.children.titleSolo": "Do you have children?",
  "step.children.titleCouple": "Do you have children?",
  "step.children.subtitle": "We find childcare prices automatically.",
  "step.children.no": "No children",
  "step.children.yes": "Yes, we have children",
  "step.children.age": "Age of each child:",
  "step.children.child": "Child",
  "step.children.years": "years",
  "step.children.add": "Add child",
  "step.children.tip": "Childcare prices are national averages 2026 (source: KL/municipalities). Nursery approx. 4,500 DKK, kindergarten approx. 2,600 DKK, after-school care approx. 2,300 DKK/mo. Your municipality may differ — adjust in the dashboard.",
  "step.children.benefitTitle": "Child benefits (automatically included)",
  "step.children.benefitTotal": "Total child benefits",

  // Onboarding — expenses
  "step.expenses.title": "Fixed expenses",
  "step.expenses.subtitle": "Select what applies — we pre-fill the prices.",
  "step.expenses.streaming": "Streaming & music",
  "step.expenses.transport": "Transport",
  "step.expenses.car": "Car",
  "step.expenses.carLoan": "Car loan / leasing",
  "step.expenses.fuel": "Fuel / charging",
  "step.expenses.carInsurance": "Car insurance",
  "step.expenses.carTax": "Vehicle tax / green owner tax",
  "step.expenses.carService": "Service / workshop",
  "step.expenses.insuranceUnion": "Insurance & union",
  "step.expenses.insurance": "Insurance",
  "step.expenses.insuranceSub": "Contents, accident, etc.",
  "step.expenses.union": "Union & unemployment fund",
  "step.expenses.fitness": "Fitness / sports",
  "step.expenses.petsLoans": "Pets, loans & savings",
  "step.expenses.pet": "Pet",
  "step.expenses.petSub": "Food, vet, insurance",
  "step.expenses.loan": "Loan",
  "step.expenses.loanSub": "Student loan, consumer loan",
  "step.expenses.savings": "Savings / investment",
  "step.expenses.savingsSub": "Monthly fixed savings",
  "step.expenses.custom": "Custom expenses",
  "step.expenses.customPlaceholder": "E.g. Contact lenses",
  "step.expenses.seeOverview": "See overview",
  "step.expenses.utilities": "Phone, internet & utilities",
  "step.expenses.internet": "Internet",
  "step.expenses.mobileSolo": "Mobile",
  "step.expenses.mobilePar": "Mobile (2 pers.)",
  "step.expenses.electricity": "Electricity",
  "step.expenses.heating": "Heating & water",
  "step.expenses.drLicens": "DR (media license)",
  "step.expenses.included": "(included)",
  "step.expenses.utilitiesNote": "These expenses are automatically included in your budget.",

  // Onboarding — review
  "step.review.title": "Review & adjust",
  "step.review.subtitle": "Adjust all numbers before continuing.",
  "step.review.disposable": "Disposable income per month",
  "step.review.good": "Good finances",
  "step.review.tight": "Tight margin",
  "step.review.warning": "Below recommendation",
  "step.review.income": "Income",
  "step.review.expenses": "Expenses",
  "step.review.share": "Share",
  "step.review.variableExpenses": "Variable expenses — adjust to your spending",
  "step.review.food": "Food & groceries",
  "step.review.restaurant": "Restaurant & takeaway",
  "step.review.leisure": "Leisure & experiences",
  "step.review.clothing": "Clothing & personal care",
  "step.review.health": "Health (doctor, dentist)",
  "step.review.fixedExpenses": "Fixed expenses",
  "step.review.seeDashboard": "See full dashboard",

  // Dashboard
  "dash.charts": "Charts",
  "dash.chartsShort": "Charts",
  "dash.report": "Report",
  "dash.newCalc": "New calculation",
  "dash.resetShort": "Reset",
  "dash.shareResult": "Share your result",
  "dash.close": "Close",
  "dash.editInfo": "Edit info",
  "dash.logOut": "Log out",
  "dash.logIn": "Log in",
  "dash.cloudSync": "Log in to save your budget across devices",
  "dash.subscriptions": "Subscriptions",

  // Sections
  "section.cockpit": "Cockpit",
  "section.cockpitSub": "Your financial overview — everything in one place.",
  "section.overview": "Overview",
  "section.overviewSub": "Where does your money go? See it all at a glance.",
  "section.action": "Action",
  "section.actionSub": "Concrete savings suggestions based on your numbers.",
  "section.future": "Future",
  "section.futureSub": "Look ahead — wealth, goals and timeline.",
  "section.advanced": "In-depth",
  "section.advancedSub": "Advanced analyses and simulations.",

  // Tabs
  "tab.cockpit": "Cockpit",
  "tab.forward": "Forward",
  "tab.whatIf": "What if",
  "tab.stressTest": "Stress test",
  "tab.calendar": "Calendar",
  "tab.optimize": "Optimize",
  "tab.compare": "Compare",
  "tab.history": "History",
  "tab.coupleSplit": "Couple split",

  // Health
  "health.freedom": "Freedom number",
  "health.freedomSub": "Actually left per month",
  "health.baseline": "Baseline",
  "health.baselineSub": "Fixed expenses per month",
  "health.buffer": "Buffer",
  "health.bufferSub": "mo. without income",

  // Frequencies
  "freq.monthly": "Monthly",
  "freq.quarterly": "Quarterly",
  "freq.biannual": "Biannual",
  "freq.annual": "Annual",
  "freq.monthlyShort": "Mo.",
  "freq.quarterShort": "Quarter",
  "freq.halfYearShort": "Half year",
  "freq.yearShort": "Year",

  // Stress test
  "stress.resilience": "Resilience score",
  "stress.resilienceGood": "Your finances can withstand most economic shocks. Strong position.",
  "stress.resilienceOk": "Your finances are vulnerable to certain scenarios. Consider strengthening your buffer.",
  "stress.resilienceBad": "Your finances are fragile. Even small changes can cause problems. Prioritize savings.",
  "stress.inflation": "Inflation",
  "stress.inflationDesc": "What happens if prices rise? Variable expenses are hit hardest.",
  "stress.moderate": "Moderate",
  "stress.severe": "Severe",
  "stress.extreme": "Extreme",
  "stress.newDisposable": "New disposable",
  "stress.impact": "Impact",
  "stress.rateHike": "Rate hike",
  "stress.rateHikeDesc": "What happens if interest rates rise? Directly affects your mortgage.",
  "stress.mortgageUp": "Mortgage increase",
  "stress.jobLoss": "Job loss",
  "stress.jobLossDesc": "What happens if your income drops? We calculate with and without unemployment benefits.",
  "stress.withoutHelp": "Without benefits",
  "stress.withDagpenge": "With benefits",
  "stress.survivalTime": "Survival time",
  "stress.months": "months",
  "stress.monthsShort": "mo.",
  "stress.withSavings": "with current savings",
  "stress.worstCase": "Worst case: Everything at once",
  "stress.worstCaseDesc": "Inflation + rate hike + income drop. Your budget under maximum pressure.",
  "stress.disclaimer": "The stress test is an estimate. Contact your bank for exact calculations.",

  // Årshjul
  "wheel.annual": "Annual expenses",
  "wheel.annualSub": "Large expenses you need to prepare for throughout the year",
  "wheel.monthlyOverview": "Monthly overview",
  "wheel.upcoming": "Upcoming expenses",
  "wheel.fullYear": "Full year",
  "wheel.now": "Now",
  "wheel.carInsurance": "Car insurance",
  "wheel.carTax": "Vehicle tax",
  "wheel.carService": "Car service",
  "wheel.propertyTax": "Property tax",
  "wheel.insuranceRenewal": "Insurance (renewal)",
  "wheel.christmas": "Christmas & gifts",
  "wheel.summerVacation": "Summer vacation",
  "wheel.taxSettlement": "Tax settlement",
  "wheel.backToSchool": "Back to school",
  "wheel.birthdays": "Birthdays",
  "wheel.disclaimer": "Amounts are estimates based on Danish averages.",

  // Nudges
  "nudge.savingsAbove": "Your savings rate ({pct}) is above average ({avg}) for similar households 💪",
  "nudge.savingsBelow": "Most similar households save at least {avg} of their income",
  "nudge.streaming": "You have {count} streaming services — 67% of Danish households have max 2",
  "nudge.foodAbove": "Your food budget is {pct}% above average for similar households",
  "nudge.foodBelow": "Your food budget is below average — well done! 🥗",
  "nudge.topPercentile": "Your disposable income is in the top {pct}% among similar households",
  "nudge.housingHigh": "Your housing cost is {pct}% of income — experts recommend max 33%",
  "nudge.healthTop": "Your health score is in the top 25 — you're better off than most",

  // Scenarios
  "scenario.buyHome.title": "Buy home",
  "scenario.buyHome.desc": "What happens if you switch from renting to owning?",
  "scenario.haveChild.title": "Have a child",
  "scenario.haveChild.desc": "How does a child affect your finances?",
  "scenario.newJob.title": "Change job",
  "scenario.newJob.desc": "Simulate a new salary and see the effect.",
  "scenario.intro": "Toggle scenarios and see how they affect your finances in real time.",
  "scenario.monthlyImpact": "Monthly impact",
  "scenario.newDisposable": "New disposable",
  "scenario.mortgagePayment": "Monthly mortgage payment",
  "scenario.salaryChange": "Salary change",
  "scenario.before": "Before vs. after",
  "scenario.now": "Now",
  "scenario.label": "Scenario",
  "scenario.disposablePerMonth": "available per month",
  "scenario.scoreLabel": "Score",

  // Page meta
  "page.lastUpdated": "Last updated",
  "page.updatedDate": "March 2026",

  // Actions
  "action.goToDashboard": "Go to your budget",

  // Cookie
  "cookie.text": "We use cookies to store your preferences locally. No data is sent to third parties.",
  "cookie.readMore": "Read more",
  "cookie.accept": "Accept",
  "cookie.decline": "Decline",

  // Generic
  "continue": "Continue",
  "currency": "DKK",
  "perMonth": "DKK/mo.",
  "perYear": "DKK/yr.",
  "perHalfYear": "DKK/half yr.",

  // Report
  "report.title": "Financial report",
  "report.solo": "Solo budget",
  "report.couple": "Couple budget",
  "report.postalCode": "Postal",
  "report.back": "Back",
  "report.share": "Share",
  "report.print": "Print / PDF",
  "report.health": "Financial health",
  "report.buffer": "Buffer",
  "report.monthlyIncome": "Monthly income",
  "report.totalExpenses": "Total expenses",
  "report.savingsRate": "Savings rate",
  "report.housingRatio": "Housing ratio",
  "report.expenseBreakdown": "Expense breakdown",
  "report.fixedExpenses": "Fixed expenses",
  "report.variableExpenses": "Variable expenses",
  "report.incomeDist": "Income distribution",
  "report.you": "You",
  "report.partner": "Partner",
  "report.generated": "Generated {date} · Based on Danish averages 2026",
  "report.disclaimer": "Budget tool — not financial advice",
  "report.bufferMonths": "{n} mo.",

  // Cockpit
  "cockpit.income": "Income",
  "cockpit.partner": "Partner",
  "cockpit.expenses": "Expenses",
  "cockpit.disposable": "Disposable",
  "cockpit.total": "Total",
  "cockpit.distribution": "Money distribution",
  "cockpit.savingsPotential": "Savings potential",
  "cockpit.seePlan": "See plan ↓",
  "cockpit.bucket.drift": "Fixed",
  "cockpit.bucket.driftTip": "Fixed costs: housing, food, transport, insurance",
  "cockpit.bucket.frihed": "Freedom",
  "cockpit.bucket.frihedTip": "Left after fixed costs — your disposable amount",
  "cockpit.bucket.fremtid": "Future",
  "cockpit.bucket.fremtidTip": "Savings and pension contributions",
  "cockpit.bucket.risiko": "Risk",
  "cockpit.bucket.risikoTip": "Debt and variable expenses",
  "cockpit.alert.overBudget": "You spend {amount} more than you earn",
  "cockpit.alert.housingHigh": "Housing is {pct}% of income — above recommended 35%",
  "cockpit.alert.streamingMany": "{count} streaming services — average person has 2",
  "cockpit.alert.savingsStrong": "Strong savings rate of {pct}%",
  "cockpit.live.electricity": "Power: {price} DKK/kWh",
  "cockpit.live.rate": "Rate: {rate}%",
  "cockpit.live.income": "Avg. income: {amount}",

  // Categories
  "cat.Bolig": "Housing",
  "cat.Forsyning": "Utilities",
  "cat.Transport": "Transport",
  "cat.Abonnementer": "Subscriptions",
  "cat.Forsikring": "Insurance",
  "cat.Fagforening": "Union",
  "cat.Børn": "Children",
  "cat.Kæledyr": "Pets",
  "cat.Lån": "Loans",
  "cat.Fitness": "Fitness",
  "cat.Opsparing": "Savings",
  "cat.Mad & dagligvarer": "Food & groceries",
  "cat.Fritid": "Leisure",
  "cat.Tøj": "Clothing",
  "cat.Sundhed": "Health",
  "cat.Restaurant": "Restaurant",
  "cat.Andet": "Other",

  // Sankey / overview
  "sankey.incomeDistribution": "Income distributed across expenses",
  "sankey.leftOver": "Left over",
  "sankey.salary": "Salary",
  "sankey.partner": "Partner",
  "sankey.otherIncome": "Other",
  "sankey.income": "Income",
  "sankey.expenses": "Expenses",

  // Dashboard misc
  "dash.startOver": "Start over",
  "dash.reset": "Reset",
  "dash.disclaimer": "Kassen is a budgeting tool — not financial advice.",
  "dash.aiTitle": "Let AI find your savings",
  "dash.aiSubtitle": "Guided walkthrough — you decide what to do",
  "dash.useDefaults": "Use defaults and see my result →",
  "dash.hideDetails": "Hide details",
  "dash.showCarDetails": "Break down car expenses",

  // Neighbor comparison
  "neighbor.comparedWith": "Compared with your income group",
  "neighbor.pair": "couples",
  "neighbor.single": "singles",
  "neighbor.housingCost": "Housing cost:",
  "neighbor.categoryByCategory": "Category by category",
  "neighbor.onPar": "On par",
  "neighbor.savingsIfLowered": "If you lower to typical level, you save",
  "neighbor.food": "Food & groceries",
  "neighbor.restaurant": "Restaurant & takeaway",
  "neighbor.transportCar": "Transport (car)",
  "neighbor.transport": "Transport",
  "neighbor.streaming": "Streaming & subscriptions",
  "neighbor.leisure": "Leisure & experiences",

  // Optimization
  "optimize.totalPotential": "Total potential",
  "optimize.lookingGood": "Your finances look strong",
  "optimize.noSavings": "We found no obvious savings — well done!",
  "optimize.doItNow": "Do it now — ",
  "optimize.dstBenchmark": "Statistics Denmark benchmark",
  "optimize.dkAverage": "DK average",
  "optimize.yourDisposable": "Your disposable income",

  // Couple split
  "couple.incomeBasedSplit": "Income-based",
  "couple.partnerIncome": "Partner's income",
  "couple.partnerPays": "Partner pays",
  "couple.expenses": "Expenses",
  "couple.remaining": "Remaining",

  // Profile edit
  "profile.householdIncome": "Household & Income",
  "profile.partnerIncomeNet": "Partner's income (net)",
  "profile.housing": "Housing",
  "profile.housingType": "Housing type",
  "profile.food": "Food & groceries",
  "profile.leisure": "Leisure & experiences",
  "profile.clothing": "Clothing & shoes",

  // Forward view
  "forward.propertyValue": "Property value",
  "forward.propertyEstimate": "Property value is an estimate — adjust in your profile",
  "forward.emergencyBuffer": "Emergency buffer (3 mo.)",
  "forward.savingsRate": "Savings rate",

  // Charts
  "charts.disposable": "Disposable income",
  "charts.average": "Average",
  "charts.lowest": "Lowest",
  "charts.highest": "Highest",
  "charts.monthNames": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",

  // AI chat
  "ai.askAbout": "Ask AI about your finances",
  "ai.askShort": "Ask AI",
  "ai.limitReached": "Monthly limit reached. Resets automatically next month.",

  // Guided saving
  "guided.title": "Guided savings session",
  "guided.found": "Found",
  "guided.totalFreed": "Total freed up",

  // Share card
  "share.economyCheck": "Finance check",
  "share.freedomNumber": "Freedom number",
  "share.savingsRate": "Savings rate",
  "share.buffer": "Buffer",
  "share.footer": "Calculated with Kassen · 2026",

  // Subscriptions
  "subs.warning": "Over 2,000 DKK/mo. on subscriptions — consider cutting back",
  "subs.foundInBudget": "Found in your budget",

  // Profile edit (extra)
  "profile.title": "Edit your details",
  "profile.saved": "Changes saved",
  "profile.savedDesc": "Your budget has been updated.",
  "profile.householdType": "Household type",
  "profile.solo": "Single",
  "profile.couple": "Couple",
  "profile.yourIncome": "Your income (net)",
  "profile.postalCode": "Postal code",
  "profile.rentPayment": "Rent/payment",
  "profile.monthlyPayment": "Monthly housing payment",
  "profile.interestRate": "Interest rate (%)",
  "profile.spending": "Spending",
  "profile.restaurantTakeaway": "Restaurant & takeaway",
  "profile.healthMedicine": "Health & medicine",
  "profile.transport": "Transport",
  "profile.hasCar": "Has car",
  "profile.carLoan": "Car loan (mo.)",
  "profile.carFuel": "Fuel/charging (mo.)",
  "profile.carInsurance": "Car insurance (mo.)",
  "profile.subscriptions": "Subscriptions",
  "profile.loansAndSavings": "Loans & Savings",
  "profile.hasLoan": "Has loan",
  "profile.loanPayment": "Loan payment (mo.)",
  "profile.savesUp": "Saves",
  "profile.savingsMonthly": "Savings (mo.)",
  "profile.insurances": "Insurance",
  "profile.insuranceMonthly": "Insurance (mo.)",
  "profile.saveChanges": "Save changes",

  // Subscriptions (extra)
  "subs.title": "Subscriptions",
  "subs.addedManually": "Added manually",
  "subs.namePlaceholder": "Name (e.g. ChatGPT Plus)",
  "subs.pricePlaceholder": "Price per month",
  "subs.add": "Add",
  "subs.cancel": "Cancel",
  "subs.addSubscription": "Add subscription",

  // GuidedSaving (extra)
  "guided.goalReached": "You reached your goal!",
  "guided.goalReachedDesc": "You freed up {amount} DKK/mo. in total.",
  "guided.skipped": "Skipped: {label}",
  "guided.whatIsYourGoal": "What is your goal?",
  "guided.goalDesc": "I'll review your budget and find the easiest savings — you decide what to do.",
  "guided.currentDisposable": "Your current disposable income is {amount} DKK/mo.",
  "guided.skip": "Skip",
  "guided.apply": "Apply",
  "guided.goalReachedTitle": "Goal reached!",
  "guided.sessionDone": "Session complete",
  "guided.reviewedAll": "You've reviewed all suggestions.",
  "guided.acceptedChanges": "Accepted changes",
  "guided.noChanges": "No changes selected.",
  "guided.seeUpdated": "See updated budget",

  // Forward view (extra)
  "forward.wealthProjection": "Wealth projection",
  "forward.years": "years",
  "forward.estimatedWealth": "Estimated wealth (property)",
  "forward.estDebt": "Est. debt (~70%)",
  "forward.netWorth": "Net worth",
  "forward.goalsProgress": "Goals & progress",
  "forward.rateShockSim": "Rate shock simulator",
  "forward.vulnerableEconomy": "Vulnerable finances",
  "forward.refinanceAdvice": "Refinancing could reduce your exposure.",
  "forward.timeline": "Timeline — next 10 years",
  "forward.noEvents": "No major events found based on your profile.",

  // ParSplit (extra)
  "couple.desc": "See how your shared expenses can be split fairly.",
  "couple.yourIncome": "Your income",
  "couple.expenseDistribution": "Expense distribution",
  "couple.youPay": "You pay",
  "couple.evenSplit": "Even split — both have roughly the same disposable income",
  "couple.youHaveMore": "You have {amount} DKK more disposable than your partner",
  "couple.partnerHasMore": "Your partner has {amount} DKK more disposable than you",
  "couple.visualization": "Visualization",
  "couple.tip": "With income-based split, you each pay relative to your salary — try it!",

  // AI chat (extra)
  "ai.personalAdvisor": "Your personal advisor",
  "ai.analyzing": "AI is analyzing your finances...",
  "ai.usedFreeAnswers": "You've used your 5 free AI answers",
  "ai.createAccount": "Create account — watch for premium",
  "ai.answersLeft": "AI answers left this month",
  "ai.placeholder": "Ask a question about your finances...",

  // History
  "history.noHistory": "No history yet",
  "history.noHistoryDesc": "Your history will appear here once you've used Kassen for more than a month. Each time you update your budget, we save a snapshot — so you can track your progress over time.",
  "history.oneSnapshot": "1 snapshot saved · Update your budget again to see a chart",
  "history.disposableSinceStart": "Disposable income since start",
  "history.healthSinceStart": "Health score since start",
  "history.disposableOverTime": "Disposable income over time",
  "history.healthOverTime": "Health score over time",
  "history.calculationsSaved": "{count} calculations saved",
  "history.first": "First",
  "history.latest": "Latest",

  // Editable amount
  "edit.clickToEdit": "Click to edit",
  "edit.cancel": "Cancel",
  "edit.save": "Save",

  // Onboarding UI
  "onboarding.leftOver": "Left over",
  "onboarding.seeOverview": "See overview",
  "onboarding.stepOf": "Step {idx} of {total}",

  // Optimize (extra)
  "optimize.opensExternal": "Opens external page",
  "optimize.savePerMonth": "Save {amount} DKK/mo.",
};
