// Danish texts — primary locale for kassen.dk build (VITE_LOCALE=da)
export const DA: Record<string, string> = {
  // Nav
  "nav.products": "Produkter",
  "nav.howItWorks": "Sådan virker det",
  "nav.back": "Tilbage",
  "nav.budget": "Budget",
  "nav.coupleFinance": "Parøkonomi",
  "nav.childTax": "Børneskat",
  "nav.cockpit": "Cockpit",
  "nav.overview": "Overblik",
  "nav.action": "Handling",
  "nav.future": "Fremtid",
  "nav.advanced": "Dybdegående",

  // Hero
  "hero.title": "Tag kontrol over",
  "hero.titleHighlight": "din privatøkonomi.",
  "hero.subtitle": "Find skjulte udgifter, se hvad du reelt har til overs og stå stærkt til fremtiden — gratis, privat og på 3 minutter.",
  "hero.cta": "Tjek din økonomi gratis",
  "hero.imageAlt": "Personlig økonomi og budgetoverblik",

  // Trust
  "trust.danish": "Bygget til dansk finanslovgivning",
  "trust.time": "Udfyldt på 3 minutter",
  "trust.private": "100% privat · Data gemmes lokalt",

  // How it works
  "howItWorks.title": "Få det fulde overblik på 3 minutter",
  "howItWorks.subtitle": "Ingen regneark. Svar ja/nej — vi klarer resten.",

  // Stats
  "stats.3min": "3 min",
  "stats.fillIn": "At udfylde",
  "stats.avgSaving": "Gns. besparelse/md.",
  "stats.freePrivate": "Privat & gratis",

  // Features
  "feature.findHidden": "Find skjulte udgifter",
  "feature.findHiddenDesc": "Vi gennemgår streaming, forsikring og transport — og viser hvad der æder dit budget.",
  "feature.aiInsight": "AI-indsigt",
  "feature.aiInsightDesc": "Analyse af dine tal og udgiftsmønstre.",
  "feature.compare": "Sammenlign med andre",
  "feature.compareDesc": "Se din økonomi sammenlignet med andre i dit område og din indkomstgruppe.",
  "feature.bankReport": "Bankmøde-rapport",
  "feature.bankReportDesc": "Tag en professionel rapport med til din bankrådgiver.",
  "feature.stressTest": "Stress-test din økonomi",
  "feature.stressTestDesc": "Hvad sker der ved jobmistelse, rentestigning eller inflation? Se din modstandskraft.",

  // Testimonials
  "testimonials.title": "Hvad andre siger",

  // Bottom CTA
  "bottomCta.title": "Klar til at komme i gang?",
  "bottomCta.subtitle": "Det tager kun 3 minutter — og koster ingenting.",
  "bottomCta.noLogin": "Ingen login · Ingen data deles · Alt gemmes lokalt",

  // Footer
  "footer.tagline": "Få det fulde overblik over din økonomi. Gratis, privat og bygget til danske forhold.",
  "footer.product": "Produkt",
  "footer.budgetCalc": "Budgetberegner",
  "footer.neighborComp": "Nabo-sammenligning",
  "footer.info": "Information",
  "footer.privacy": "Privatlivspolitik",
  "footer.terms": "Vilkår & betingelser",
  "footer.contact": "Kontakt",
  "footer.about": "Om",
  "footer.private": "100% privat · Data gemmes lokalt",
  "footer.tools": "Værktøjer",
  "footer.legal": "Juridisk",
  "footer.disclaimer": "Kassen er et budgetværktøj og yder ikke finansiel rådgivning. Tal med din bank eller en rådgiver om konkrete økonomiske beslutninger.",
  "footer.based": "Beregnet på danske gennemsnitstal 2026 · Data gemmes lokalt",
  "footer.installApp": "Installér app",
  "footer.guides": "Guides & tips",

  // Onboarding — household
  "step.household.title": "Hvem er med i husstanden?",
  "step.household.subtitle": "Vi tilpasser alle estimater til jeres situation.",
  "step.household.solo": "Kun mig",
  "step.household.soloSub": "Enlig husstand",
  "step.household.couple": "Vi er to",
  "step.household.coupleSub": "Par / samboende",

  // Onboarding — income
  "step.income.titleSolo": "Hvad er din indkomst?",
  "step.income.titleCouple": "Hvad er jeres indkomst?",
  "step.income.subtitle": "Månedlig udbetalt efter skat.",
  "step.income.myIncome": "Månedlig indkomst",
  "step.income.myIncomePar": "Din indkomst",
  "step.income.partnerIncome": "Partners indkomst",
  "step.income.otherIncome": "Øvrig indkomst",
  "step.income.placeholder": "F.eks. Bonus, SU, børnepenge",
  "step.income.amount": "Beløb",
  "step.income.addSource": "Tilføj indkomstkilde",
  "step.income.total": "Samlet indkomst",
  "step.income.tipSolo": "Gennemsnitlig indkomst for enlige i Danmark er ca. 27.000 kr./md. efter skat.",
  "step.income.tipCouple": "Gennemsnitlig husstandsindkomst for par i Danmark er ca. 52.000 kr./md. efter skat.",
  "step.income.netTip": "Indtast løn efter skat (netto — det du får udbetalt)",

  // Onboarding — housing
  "step.housing.title": "Boligsituation",
  "step.housing.subtitle": "Vi estimerer ud fra postnummer — justér frit.",
  "step.housing.renter": "Lejer",
  "step.housing.coop": "Andel",
  "step.housing.owner": "Ejer",
  "step.housing.postalCode": "Postnummer",
  "step.housing.postalPlaceholder": "F.eks. 2100",
  "step.housing.rent": "Månedlig husleje",
  "step.housing.coopFee": "Månedlig boligafgift",
  "step.housing.coopLoan": "Andelslån (afdrag + renter)",
  "step.housing.mortgage": "Månedlig boligydelse",
  "step.housing.propertyValue": "Boligens estimerede værdi",
  "step.housing.interestRate": "Rente på lån",

  // Onboarding — children
  "step.children.titleSolo": "Har du børn?",
  "step.children.titleCouple": "Har I børn?",
  "step.children.subtitle": "Vi finder institutionspriser automatisk.",
  "step.children.no": "Ingen børn",
  "step.children.yes": "Ja, vi har børn",
  "step.children.age": "Alder for hvert barn:",
  "step.children.child": "Barn",
  "step.children.years": "år",
  "step.children.add": "Tilføj barn",
  "step.children.tip": "Institutionspriser er landsgennemsnit 2026 (kilde: KL/kommunerne). Vuggestue ca. 4.500 kr., børnehave ca. 2.600 kr., SFO ca. 2.300 kr./md. Din kommune kan afvige — ret beløbet i dashboardet.",
  "step.children.benefitTitle": "Børnepenge (automatisk medregnet)",
  "step.children.benefitTotal": "I alt børnepenge",

  // Onboarding — expenses
  "step.expenses.title": "Faste udgifter",
  "step.expenses.subtitle": "Vælg det der passer — vi præudfylder priserne.",
  "step.expenses.streaming": "Streaming & musik",
  "step.expenses.transport": "Transport",
  "step.expenses.car": "Bil",
  "step.expenses.carLoan": "Billån / leasing",
  "step.expenses.fuel": "Benzin / opladning",
  "step.expenses.carInsurance": "Bilforsikring",
  "step.expenses.carTax": "Vægtafgift / grøn ejerafgift",
  "step.expenses.carService": "Service / værksted",
  "step.expenses.insuranceUnion": "Forsikring & fagforening",
  "step.expenses.insurance": "Forsikringer",
  "step.expenses.insuranceSub": "Indbo, ulykke, etc.",
  "step.expenses.union": "Fagforening & A-kasse",
  "step.expenses.fitness": "Fitness / sport",
  "step.expenses.petsLoans": "Kæledyr, lån & opsparing",
  "step.expenses.pet": "Kæledyr",
  "step.expenses.petSub": "Foder, dyrlæge, forsikring",
  "step.expenses.loan": "Lån",
  "step.expenses.loanSub": "SU-lån, forbrugslån, billån",
  "step.expenses.savings": "Opsparing / investering",
  "step.expenses.savingsSub": "Fast opsparing pr. måned",
  "step.expenses.custom": "Egne udgifter",
  "step.expenses.customPlaceholder": "F.eks. Kontaktlinser",
  "step.expenses.seeOverview": "Se overblik",
  "step.expenses.utilities": "Telefon, internet & forsyning",
  "step.expenses.internet": "Internet",
  "step.expenses.mobileSolo": "Mobil",
  "step.expenses.mobilePar": "Mobil (2 pers.)",
  "step.expenses.electricity": "El",
  "step.expenses.heating": "Varme & vand",
  "step.expenses.drLicens": "DR (medielicens)",
  "step.expenses.included": "(inkluderet)",
  "step.expenses.utilitiesNote": "Disse udgifter medregnes automatisk i dit budget.",

  // Onboarding — review
  "step.review.title": "Gennemse & justér",
  "step.review.subtitle": "Ret alle tal til inden du går videre.",
  "step.review.disposable": "Rådighedsbeløb pr. måned",
  "step.review.good": "God økonomi",
  "step.review.tight": "Slank margin",
  "step.review.warning": "Under anbefaling",
  "step.review.income": "Indkomst",
  "step.review.expenses": "Udgifter",
  "step.review.share": "Andel",
  "step.review.variableExpenses": "Variable udgifter — justér til dit forbrug",
  "step.review.food": "Mad & dagligvarer",
  "step.review.restaurant": "Restaurant & takeaway",
  "step.review.leisure": "Fritid & oplevelser",
  "step.review.clothing": "Tøj & personlig pleje",
  "step.review.health": "Sundhed (læge, tandlæge)",
  "step.review.fixedExpenses": "Faste udgifter",
  "step.review.seeDashboard": "Se fuldt dashboard",

  // Dashboard
  "dash.charts": "Diagrammer",
  "dash.chartsShort": "Grafer",
  "dash.report": "Rapport",
  "dash.newCalc": "Ny beregning",
  "dash.resetShort": "Nulstil",
  "dash.shareResult": "Del dit resultat",
  "dash.close": "Luk",
  "dash.editInfo": "Ret oplysninger",
  "dash.logOut": "Log ud",
  "dash.logIn": "Log ind",
  "dash.cloudSync": "Log ind for at gemme dit budget på tværs af enheder",
  "dash.subscriptions": "Abonnementer",

  // Sections
  "section.cockpit": "Cockpit",
  "section.cockpitSub": "Dit økonomiske overblik — alt på ét sted.",
  "section.overview": "Overblik",
  "section.overviewSub": "Hvor går dine penge hen? Se det hele i ét blik.",
  "section.action": "Handling",
  "section.actionSub": "Konkrete besparelsesforslag baseret på dine tal.",
  "section.future": "Fremtid",
  "section.futureSub": "Se frem — formue, mål og tidslinje.",
  "section.advanced": "Dybdegående",
  "section.advancedSub": "Avancerede analyser og simulationer.",

  // Tabs
  "tab.cockpit": "Cockpit",
  "tab.forward": "Fremad",
  "tab.whatIf": "Hvad hvis",
  "tab.stressTest": "Stress-test",
  "tab.calendar": "Årshjul",
  "tab.optimize": "Optimering",
  "tab.compare": "Sammenlign",
  "tab.history": "Historik",
  "tab.coupleSplit": "Parsplit",

  // Health
  "health.freedom": "Frihedstal",
  "health.freedomSub": "Reelt til overs pr. md.",
  "health.baseline": "Baseline",
  "health.baselineSub": "Faste udgifter pr. md.",
  "health.buffer": "Buffer",
  "health.bufferSub": "md. uden indkomst",

  // Frequencies
  "freq.monthly": "Månedlig",
  "freq.quarterly": "Kvartalsvis",
  "freq.biannual": "Halvårlig",
  "freq.annual": "Årlig",
  "freq.monthlyShort": "Md.",
  "freq.quarterShort": "Kvartal",
  "freq.halfYearShort": "Halvår",
  "freq.yearShort": "År",

  // Stress test
  "stress.resilience": "Modstandskraft",
  "stress.resilienceGood": "Din økonomi kan modstå de fleste økonomiske chok. Stærk position.",
  "stress.resilienceOk": "Din økonomi er sårbar over for visse scenarier. Overvej at styrke din buffer.",
  "stress.resilienceBad": "Din økonomi er skrøbelig. Selv små ændringer kan skabe problemer. Prioritér opsparing.",
  "stress.inflation": "Inflation",
  "stress.inflationDesc": "Hvad sker der, hvis priserne stiger? Variable udgifter rammes hårdest.",
  "stress.moderate": "Moderat",
  "stress.severe": "Alvorlig",
  "stress.extreme": "Ekstrem",
  "stress.newDisposable": "Nyt rådighedsbeløb",
  "stress.impact": "Effekt",
  "stress.rateHike": "Rentestigning",
  "stress.rateHikeDesc": "Hvad sker der, hvis renten stiger? Påvirker dit boliglån direkte.",
  "stress.mortgageUp": "Boliglån stiger",
  "stress.jobLoss": "Jobmistelse",
  "stress.jobLossDesc": "Hvad sker der, hvis din indkomst falder? Vi beregner med og uden dagpenge.",
  "stress.withoutHelp": "Uden dagpenge",
  "stress.withDagpenge": "Med dagpenge",
  "stress.survivalTime": "Overlevelsestid",
  "stress.months": "måneder",
  "stress.monthsShort": "md.",
  "stress.withSavings": "med nuværende opsparing",
  "stress.worstCase": "Worst case: Alt på én gang",
  "stress.worstCaseDesc": "Inflation + rentestigning + indkomstfald. Dit budget under maksimalt pres.",
  "stress.disclaimer": "Stress-testen er et estimat. Kontakt din bank for præcis beregning.",

  // Årshjul
  "wheel.annual": "Årlige udgifter",
  "wheel.annualSub": "Store udgifter du skal forberede dig på i løbet af året",
  "wheel.monthlyOverview": "Månedsvisning",
  "wheel.upcoming": "Kommende udgifter",
  "wheel.fullYear": "Hele året",
  "wheel.now": "Nu",
  "wheel.carInsurance": "Bilforsikring",
  "wheel.carTax": "Vægtafgift",
  "wheel.carService": "Bilservice",
  "wheel.propertyTax": "Ejendomsskat",
  "wheel.insuranceRenewal": "Forsikring (fornyelse)",
  "wheel.christmas": "Jul & gaver",
  "wheel.summerVacation": "Sommerferie",
  "wheel.taxSettlement": "Restskat / overskydende",
  "wheel.backToSchool": "Skolestart",
  "wheel.birthdays": "Fødselsdage",
  "wheel.disclaimer": "Beløbene er estimater baseret på danske gennemsnit.",

  // Nudges
  "nudge.savingsAbove": "Din opsparingsrate ({pct}) ligger over gennemsnittet ({avg}) for lignende husstande 💪",
  "nudge.savingsBelow": "De fleste lignende husstande sparer mindst {avg} af deres indkomst op",
  "nudge.streaming": "Du har {count} streamingtjenester — 67% af danske husstande har maks 2",
  "nudge.foodAbove": "Dit madbudget er {pct}% over gennemsnittet for lignende husstande",
  "nudge.foodBelow": "Dit madbudget er under gennemsnittet — godt klaret! 🥗",
  "nudge.topPercentile": "Dit rådighedsbeløb er i top {pct}% blandt lignende husstande",
  "nudge.housingHigh": "Din boligudgift udgør {pct}% af indkomsten — eksperter anbefaler maks 33%",
  "nudge.healthTop": "Din sundhedsscore er i top-25 — du er bedre stillet end de fleste",

  // Scenarios
  "scenario.buyHome.title": "Køb bolig",
  "scenario.buyHome.desc": "Hvad sker der, hvis du skifter fra leje til ejerbolig?",
  "scenario.haveChild.title": "Få barn",
  "scenario.haveChild.desc": "Hvordan påvirker et barn din økonomi?",
  "scenario.newJob.title": "Skift job",
  "scenario.newJob.desc": "Simulér en ny løn og se effekten.",
  "scenario.intro": "Slå scenarier til og se hvordan de påvirker din økonomi i realtid.",
  "scenario.monthlyImpact": "Månedlig effekt",
  "scenario.newDisposable": "Nyt rådighedsbeløb",
  "scenario.mortgagePayment": "Månedlig boligydelse",
  "scenario.salaryChange": "Lønændring",
  "scenario.before": "Før vs. efter",
  "scenario.now": "Nu",
  "scenario.label": "Scenarie",
  "scenario.disposablePerMonth": "til rådighed pr. md.",
  "scenario.scoreLabel": "Score",

  // Page meta
  "page.lastUpdated": "Sidst opdateret",
  "page.updatedDate": "marts 2026",

  // Actions
  "action.goToDashboard": "Fortsæt til dit budget",

  // Cookie
  "cookie.text": "Vi bruger cookies til at gemme dine præferencer lokalt. Ingen data sendes til tredjeparter.",
  "cookie.readMore": "Læs mere",
  "cookie.accept": "Acceptér",
  "cookie.decline": "Afvis",

  // Generic
  "continue": "Fortsæt",
  "currency": "kr.",
  "perMonth": "kr./md.",
  "perYear": "kr./år",
  "perHalfYear": "kr./halvår",

  // Report
  "report.title": "Økonomirapport",
  "report.solo": "Solobudget",
  "report.couple": "Parbudget",
  "report.postalCode": "Postnr.",
  "report.back": "Tilbage",
  "report.share": "Del",
  "report.print": "Print / PDF",
  "report.health": "Økonomisk sundhed",
  "report.buffer": "Buffer",
  "report.monthlyIncome": "Månedlig indkomst",
  "report.totalExpenses": "Samlede udgifter",
  "report.savingsRate": "Opsparingsrate",
  "report.housingRatio": "Bolig-ratio",
  "report.expenseBreakdown": "Udgiftsspecifikation",
  "report.fixedExpenses": "Faste udgifter",
  "report.variableExpenses": "Variable udgifter",
  "report.incomeDist": "Indkomstfordeling",
  "report.you": "Dig",
  "report.partner": "Partner",
  "report.generated": "Genereret {date} · Beregnet på danske gennemsnitstal 2026",
  "report.disclaimer": "Budgetværktøj — ikke finansiel rådgivning",
  "report.bufferMonths": "{n} md.",

  // Cockpit
  "cockpit.income": "Indkomst",
  "cockpit.partner": "Partner",
  "cockpit.expenses": "Udgifter",
  "cockpit.disposable": "Til rådighed",
  "cockpit.total": "I alt",
  "cockpit.distribution": "Pengenes fordeling",
  "cockpit.savingsPotential": "Besparelsespotentiale",
  "cockpit.seePlan": "Se plan ↓",
  "cockpit.bucket.drift": "Drift",
  "cockpit.bucket.driftTip": "Faste udgifter: bolig, mad, transport, forsikring",
  "cockpit.bucket.frihed": "Frihed",
  "cockpit.bucket.frihedTip": "Til overs efter faste udgifter — dit rådighedsbeløb",
  "cockpit.bucket.fremtid": "Fremtid",
  "cockpit.bucket.fremtidTip": "Opsparing og pensionsbidrag",
  "cockpit.bucket.risiko": "Risiko",
  "cockpit.bucket.risikoTip": "Gæld og varierende udgifter",
  "cockpit.alert.overBudget": "Du bruger {amount} kr. mere end du tjener",
  "cockpit.alert.housingHigh": "Bolig udgør {pct}% af indkomsten — over anbefalede 35%",
  "cockpit.alert.streamingMany": "{count} streamingtjenester — gennemsnitsdansker har 2",
  "cockpit.alert.savingsStrong": "Stærk opsparingsrate på {pct}%",
  "cockpit.live.electricity": "El: {price} kr/kWh",
  "cockpit.live.rate": "Rente: {rate}%",
  "cockpit.live.income": "Gns. indkomst: {amount} kr.",
};
