// Danish texts — primary locale for nemtbudget.nu build (VITE_LOCALE=da)
export const DA: Record<string, string> = {
  // Nav
  "nav.products": "Produkter",
  "nav.howItWorks": "Sådan virker det",
  "nav.back": "Tilbage",
  "nav.budget": "Budget",
  "nav.coupleFinance": "Parøkonomi",
  "nav.childTax": "Børneskat",
  "nav.cockpit": "Cockpit",
  "nav.overview": "Overblik",
  "nav.action": "Handling",
  "nav.future": "Fremtid",
  "nav.advanced": "Dybdegående",

  // Hero
  "hero.title": "Du har mindre end du tror",
  "hero.titleHighlight": "til overs hver måned.",
  "hero.subtitle": "De fleste danskere overvurderer deres rådighedsbeløb med 3.000-5.000 kr. Find dine skjulte udgifter på 3 minutter — gratis og privat.",
  "hero.cta": "Beregn dit rådighedsbeløb",
  "hero.imageAlt": "Personlig økonomi og budgetoverblik",
  "hero.socialProof": "1.200+ danskere har allerede tjekket deres budget",

  // Trust
  "trust.danish": "Bygget til dansk finanslovgivning",
  "trust.time": "Udfyldt på 3 minutter",
  "trust.private": "100% privat · Data gemmes lokalt",

  // How it works
  "howItWorks.title": "Få det fulde overblik på 3 minutter",
  "howItWorks.subtitle": "Ingen regneark. Svar ja/nej — vi klarer resten.",

  // Stats
  "stats.3min": "3 min",
  "stats.fillIn": "At udfylde",
  "stats.avgSaving": "Gns. besparelse/md.",
  "stats.freePrivate": "Privat & gratis",

  // Features
  "feature.findHidden": "Find skjulte udgifter",
  "feature.findHiddenDesc": "Vi gennemgår streaming, forsikring og transport — og viser hvad der æder dit budget.",
  "feature.aiInsight": "AI-indsigt",
  "feature.aiInsightDesc": "Analyse af dine tal og udgiftsmønstre.",
  "feature.compare": "Sammenlign med andre",
  "feature.compareDesc": "Se din økonomi sammenlignet med andre i dit område og din indkomstgruppe.",
  "feature.bankReport": "Bankmøde-rapport",
  "feature.bankReportDesc": "Tag en professionel rapport med til din bankrådgiver.",
  "feature.stressTest": "Stress-test din økonomi",
  "feature.stressTestDesc": "Hvad sker der ved jobmistelse, rentestigning eller inflation? Se din modstandskraft.",
  "feature.savings": "Opsparingsplanlægger",
  "feature.savingsDesc": "Se hvornår du når dine mål med din nuværende opsparingsrate.",

  // Testimonials
  "testimonials.title": "Hvad andre siger",

  // Bottom CTA
  "bottomCta.title": "3 minutter. 0 kroner. Fuldt overblik.",
  "bottomCta.subtitle": "De fleste finder mindst én udgift de ikke vidste de betalte.",
  "bottomCta.noLogin": "Ingen login · Ingen data deles · Alt gemmes lokalt",

  // Footer
  "footer.tagline": "Få det fulde overblik over din økonomi. Gratis, privat og bygget til danske forhold.",
  "footer.product": "Produkt",
  "footer.budgetCalc": "Budgetberegner",
  "footer.neighborComp": "Nabo-sammenligning",
  "footer.info": "Information",
  "footer.privacy": "Privatlivspolitik",
  "footer.terms": "Vilkår & betingelser",
  "footer.contact": "Kontakt",
  "footer.about": "Om",
  "footer.private": "100% privat · Data gemmes lokalt",
  "footer.tools": "Værktøjer",
  "footer.legal": "Juridisk",
  "footer.disclaimer": "NemtBudget.nu yder ikke finansiel r\u00e5dgivning. Beregninger er vejledende. AI-r\u00e5dgiveren kan producere fejl. Tal med din bank eller en r\u00e5dgiver om konkrete \u00f8konomiske beslutninger.",
  "footer.based": "Beregnet på danske gennemsnitstal 2026 · Data gemmes lokalt",
  "footer.installApp": "Installér app",
  "footer.guides": "Guides & tips",

  // Onboarding — household
  "step.household.title": "Hvem er med i husstanden?",
  "step.household.subtitle": "Vi tilpasser alle estimater til jeres situation.",
  "step.household.solo": "Kun mig",
  "step.household.soloSub": "Enlig husstand",
  "step.household.couple": "Vi er to",
  "step.household.coupleSub": "Par / samboende",

  // Onboarding — income
  "step.income.titleSolo": "Hvad er din indkomst?",
  "step.income.titleCouple": "Hvad er jeres indkomst?",
  "step.income.subtitle": "Månedlig udbetalt efter skat.",
  "step.income.myIncome": "Månedlig indkomst",
  "step.income.myIncomePar": "Din indkomst",
  "step.income.partnerIncome": "Partners indkomst",
  "step.income.otherIncome": "Øvrig indkomst",
  "step.income.placeholder": "F.eks. Bonus, SU, børnepenge",
  "step.income.amount": "Beløb",
  "step.income.addSource": "Tilføj indkomstkilde",
  "step.income.total": "Samlet indkomst",
  "step.income.tipSolo": "Gennemsnitlig indkomst for enlige i Danmark er ca. 27.000 kr./md. efter skat.",
  "step.income.tipCouple": "Gennemsnitlig husstandsindkomst for par i Danmark er ca. 52.000 kr./md. efter skat.",
  "step.income.netTip": "Indtast løn efter skat (netto — det du får udbetalt)",
  "step.income.payslip.title": "Har du din lønseddel?",
  "step.income.payslip.hint": "Upload foto eller PDF — vi læser beløbet automatisk",
  "step.income.payslip.analyzing": "Analyserer lønseddel...",
  "step.income.payslip.success": "Lønseddel aflæst!",
  "step.income.payslip.applied": "Indkomst og fradrag er udfyldt automatisk.",
  "step.income.payslip.retry": "Prøv igen",
  "step.income.payslip.skipManual": "Skriv selv",
  "step.income.payslip.clear": "Fjern",
  "step.income.payslip.divider": "eller indtast manuelt",

  // Onboarding — housing
  "step.housing.title": "Boligsituation",
  "step.housing.subtitle": "Vi estimerer ud fra postnummer — justér frit.",
  "step.housing.renter": "Lejer",
  "step.housing.coop": "Andel",
  "step.housing.owner": "Ejer",
  "step.housing.postalCode": "Postnummer",
  "step.housing.postalPlaceholder": "F.eks. 2100",
  "step.housing.unknownPostal": "Ukendt postnummer — estimater kan ikke beregnes",
  "step.housing.rent": "Månedlig husleje",
  "step.housing.coopFee": "Månedlig boligafgift",
  "step.housing.coopLoan": "Andelslån (afdrag + renter)",
  "step.housing.mortgage": "Månedlig boligydelse",
  "step.housing.propertyValue": "Boligens estimerede værdi",
  "step.housing.interestRate": "Rente på lån",

  // Onboarding — children
  "step.children.titleSolo": "Har du børn?",
  "step.children.titleCouple": "Har I børn?",
  "step.children.subtitle": "Vi finder institutionspriser automatisk.",
  "step.children.no": "Ingen børn",
  "step.children.yes": "Ja, vi har børn",
  "step.children.age": "Alder for hvert barn:",
  "step.children.child": "Barn",
  "step.children.years": "år",
  "step.children.add": "Tilføj barn",
  "step.children.tip": "Institutionspriser er landsgennemsnit 2026 (kilde: KL/kommunerne). Vuggestue ca. 4.500 kr., børnehave ca. 2.600 kr., SFO ca. 2.300 kr./md. Din kommune kan afvige — ret beløbet i dashboardet.",
  "step.children.benefitTitle": "Børnepenge (automatisk medregnet)",
  "step.children.benefitTotal": "I alt børnepenge",

  // Onboarding — expenses
  "step.expenses.title": "Faste udgifter",
  "step.expenses.subtitle": "Vælg det der passer — vi præudfylder priserne.",
  "step.expenses.streaming": "Streaming & musik",
  "step.expenses.transport": "Transport",
  "step.expenses.car": "Bil",
  "step.expenses.carLoan": "Billån / leasing",
  "step.expenses.fuel": "Benzin / opladning",
  "step.expenses.carInsurance": "Bilforsikring",
  "step.expenses.carTax": "Vægtafgift / grøn ejerafgift",
  "step.expenses.carService": "Service / værksted",
  "step.expenses.insuranceUnion": "Forsikring & fagforening",
  "step.expenses.insurance": "Forsikringer",
  "step.expenses.insuranceSub": "Indbo, ulykke, etc.",
  "step.expenses.union": "Fagforening & A-kasse",
  "step.expenses.fitness": "Fitness / sport",
  "step.expenses.petsLoans": "Kæledyr, lån & opsparing",
  "step.expenses.pet": "Kæledyr",
  "step.expenses.petSub": "Foder, dyrlæge, forsikring",
  "step.expenses.loan": "Lån",
  "step.expenses.loanSub": "SU-lån, forbrugslån, billån",
  "step.expenses.savings": "Opsparing / investering",
  "step.expenses.savingsSub": "Fast opsparing pr. måned",
  "step.everyday.title": "Hverdagsudgifter",
  "step.everyday.subtitle": "Juster dine daglige udgifter — vi har udfyldt med gennemsnit",
  "step.everyday.smartDefaults": "Vi har gættet dit hverdagsbudget — justér det der ikke passer.",
  "step.fixed.title": "Faste udgifter",
  "step.fixed.subtitle": "Abonnementer, forsikring og andet fast.",
  "step.fixed.smartDefaults": "Faste udgifter — vi har udfyldt med typiske danske priser.",
  "step.expenses.custom": "Egne udgifter",
  "step.expenses.customPlaceholder": "F.eks. Kontaktlinser",
  "step.expenses.seeOverview": "Se overblik",
  "step.expenses.utilities": "Telefon, internet & forsyning",
  "step.expenses.internet": "Internet",
  "step.expenses.mobileSolo": "Mobil",
  "step.expenses.mobilePar": "Mobil (2 pers.)",
  "step.expenses.electricity": "El",
  "step.expenses.heating": "Varme & vand",
  "step.expenses.drLicens": "DR (medielicens)",
  "step.expenses.included": "(inkluderet)",
  "step.expenses.utilitiesNote": "Disse udgifter medregnes automatisk i dit budget.",

  // Onboarding — review
  "step.review.title": "Gennemse & justér",
  "step.review.subtitle": "Ret alle tal til inden du går videre.",
  "step.review.disposable": "Rådighedsbeløb pr. måned",
  "step.review.good": "God økonomi",
  "step.review.tight": "Slank margin",
  "step.review.warning": "Under anbefaling",
  "step.review.income": "Indkomst",
  "step.review.expenses": "Udgifter",
  "step.review.share": "Andel",
  "step.review.variableExpenses": "Variable udgifter — justér til dit forbrug",
  "step.review.food": "Mad & dagligvarer",
  "step.review.restaurant": "Restaurant & takeaway",
  "step.review.leisure": "Fritid & oplevelser",
  "step.review.clothing": "Tøj & personlig pleje",
  "step.review.health": "Sundhed (læge, tandlæge)",
  "step.review.fixedExpenses": "Faste udgifter",
  "step.review.seeDashboard": "Se fuldt dashboard",
  "step.review.zeroIncomeWarning": "Din indkomst er sat til 0 kr. Er det korrekt?",

  // Dashboard
  "dash.title": "Dit budget — NemtBudget",
  "dash.charts": "Diagrammer",
  "dash.chartsShort": "Grafer",
  "dash.report": "Rapport",
  "dash.newCalc": "Ny beregning",
  "dash.resetShort": "Nulstil",
  "dash.shareResult": "Del dit resultat",
  "dash.close": "Luk",
  "dash.editInfo": "Ret oplysninger",
  "dash.logOut": "Log ud",
  "dash.logIn": "Log ind",
  "dash.cloudSync": "Log ind for at gemme dit budget på tværs af enheder",
  "dash.subscriptions": "Abonnementer",

  // Sections
  "section.cockpit": "Overblik",
  "section.cockpitSub": "Dit økonomiske overblik — alt på ét sted.",
  "section.overview": "Overblik",
  "section.overviewSub": "Hvor går dine penge hen? Se det hele i ét blik.",
  "section.action": "Handling",
  "section.actionSub": "Konkrete besparelsesforslag baseret på dine tal.",
  "section.future": "Fremtid",
  "section.futureSub": "Se frem — formue, mål og tidslinje.",
  "section.advanced": "Dybdegående",
  "section.advancedSub": "Avancerede analyser og simulationer.",

  // Tabs
  "tab.cockpit": "Cockpit",
  "tab.forward": "Fremad",
  "tab.whatIf": "Hvad hvis",
  "tab.stressTest": "Stress-test",
  "tab.calendar": "Årshjul",
  "tab.optimize": "Optimering",
  "tab.compare": "Sammenlign",
  "tab.history": "Historik",
  "tab.coupleSplit": "Parsplit",

  // Health
  "health.freedom": "Frihedstal",
  "health.freedomSub": "Reelt til overs pr. md.",
  "health.baseline": "Baseline",
  "health.baselineSub": "Faste udgifter pr. md.",
  "health.buffer": "Buffer",
  "health.bufferSub": "md. uden indkomst",

  // Frequencies
  "freq.monthly": "Månedlig",
  "freq.quarterly": "Kvartalsvis",
  "freq.biannual": "Halvårlig",
  "freq.annual": "Årlig",
  "freq.monthlyShort": "Md.",
  "freq.quarterShort": "Kvartal",
  "freq.halfYearShort": "Halvår",
  "freq.yearShort": "År",

  // Stress test
  "stress.resilience": "Modstandskraft",
  "stress.resilienceGood": "Din økonomi kan modstå de fleste økonomiske chok. Stærk position.",
  "stress.resilienceOk": "Din økonomi er sårbar over for visse scenarier. Overvej at styrke din buffer.",
  "stress.resilienceBad": "Din økonomi er skrøbelig. Selv små ændringer kan skabe problemer. Prioritér opsparing.",
  "stress.inflation": "Inflation",
  "stress.inflationDesc": "Hvad sker der, hvis priserne stiger? Variable udgifter rammes hårdest.",
  "stress.moderate": "Moderat",
  "stress.severe": "Alvorlig",
  "stress.extreme": "Ekstrem",
  "stress.newDisposable": "Nyt rådighedsbeløb",
  "stress.impact": "Effekt",
  "stress.rateHike": "Rentestigning",
  "stress.rateHikeDesc": "Hvad sker der, hvis renten stiger? Påvirker dit boliglån direkte.",
  "stress.mortgageUp": "Boliglån stiger",
  "stress.jobLoss": "Jobmistelse",
  "stress.jobLossDesc": "Hvad sker der, hvis din indkomst falder? Vi beregner med og uden dagpenge.",
  "stress.withoutHelp": "Uden dagpenge",
  "stress.withDagpenge": "Med dagpenge",
  "stress.personalDagpenge": "Din personlige dagpengesats",
  "stress.survivalTime": "Overlevelsestid",
  "stress.months": "måneder",
  "stress.monthsShort": "md.",
  "stress.withSavings": "med nuværende opsparing",
  "stress.worstCase": "Worst case: Alt på én gang",
  "stress.worstCaseDesc": "Inflation + rentestigning + indkomstfald. Dit budget under maksimalt pres.",
  "stress.disclaimer": "Stress-testen er et estimat. Kontakt din bank for præcis beregning.",

  // Årshjul
  "wheel.annual": "Årlige udgifter",
  "wheel.annualSub": "Store udgifter du skal forberede dig på i løbet af året",
  "wheel.monthlyOverview": "Månedsvisning",
  "wheel.upcoming": "Kommende udgifter",
  "wheel.fullYear": "Hele året",
  "wheel.now": "Nu",
  "wheel.carInsurance": "Bilforsikring",
  "wheel.carTax": "Vægtafgift",
  "wheel.carService": "Bilservice",
  "wheel.propertyTax": "Ejendomsskat",
  "wheel.insuranceRenewal": "Forsikring (fornyelse)",
  "wheel.christmas": "Jul & gaver",
  "wheel.summerVacation": "Sommerferie",
  "wheel.taxSettlement": "Restskat / overskydende",
  "wheel.backToSchool": "Skolestart",
  "wheel.birthdays": "Fødselsdage",
  "wheel.disclaimer": "Beløbene er estimater baseret på danske gennemsnit.",

  // Nudges
  "nudge.savingsAbove": "Din opsparingsrate ({pct}) ligger over gennemsnittet ({avg}) for lignende husstande 💪",
  "nudge.savingsBelow": "De fleste lignende husstande sparer mindst {avg} af deres indkomst op",
  "nudge.streaming": "Du har {count} streamingtjenester — 67% af danske husstande har maks 2",
  "nudge.foodAbove": "Dit madbudget er {pct}% over gennemsnittet for lignende husstande",
  "nudge.foodBelow": "Dit madbudget er under gennemsnittet — godt klaret! 🥗",
  "nudge.topPercentile": "Dit rådighedsbeløb er i top {pct}% blandt lignende husstande",
  "nudge.housingHigh": "Din boligudgift udgør {pct}% af indkomsten — eksperter anbefaler maks 33%",
  "nudge.healthTop": "Din sundhedsscore er i top-25 — du er bedre stillet end de fleste",

  // Scenarios
  "scenario.buyHome.title": "Køb bolig",
  "scenario.buyHome.desc": "Hvad sker der, hvis du skifter fra leje til ejerbolig?",
  "scenario.haveChild.title": "Få barn",
  "scenario.haveChild.desc": "Hvordan påvirker et barn din økonomi?",
  "scenario.newJob.title": "Skift job",
  "scenario.newJob.desc": "Simulér en ny løn og se effekten.",
  "scenario.intro": "Slå scenarier til og se hvordan de påvirker din økonomi i realtid.",
  "scenario.monthlyImpact": "Månedlig effekt",
  "scenario.newDisposable": "Nyt rådighedsbeløb",
  "scenario.mortgagePayment": "Månedlig boligydelse",
  "scenario.salaryChange": "Lønændring",
  "scenario.before": "Før vs. efter",
  "scenario.now": "Nu",
  "scenario.label": "Scenarie",
  "scenario.disposablePerMonth": "til rådighed pr. md.",
  "scenario.scoreLabel": "Score",

  // Page meta
  "page.lastUpdated": "Sidst opdateret",
  "page.updatedDate": "marts 2026",

  // Actions
  "action.goToDashboard": "Fortsæt til dit budget",

  // Cookie
  "cookie.text": "Vi bruger cookies til at gemme dine præferencer lokalt. Ingen data sendes til tredjeparter.",
  "cookie.readMore": "Læs mere",
  "cookie.accept": "Acceptér",
  "cookie.decline": "Afvis",

  // Generic
  "continue": "Fortsæt",
  "currency": "kr.",
  "perMonth": "kr./md.",
  "perYear": "kr./år",
  "perHalfYear": "kr./halvår",

  // Report
  "report.title": "Økonomirapport",
  "report.solo": "Solobudget",
  "report.couple": "Parbudget",
  "report.postalCode": "Postnr.",
  "report.back": "Tilbage",
  "report.share": "Del",
  "report.print": "Print / PDF",
  "report.health": "Økonomisk sundhed",
  "report.buffer": "Buffer",
  "report.monthlyIncome": "Månedlig indkomst",
  "report.totalExpenses": "Samlede udgifter",
  "report.savingsRate": "Opsparingsrate",
  "report.housingRatio": "Bolig-ratio",
  "report.expenseBreakdown": "Udgiftsspecifikation",
  "report.fixedExpenses": "Faste udgifter",
  "report.variableExpenses": "Variable udgifter",
  "report.incomeDist": "Indkomstfordeling",
  "report.you": "Dig",
  "report.partner": "Partner",
  "report.generated": "Genereret {date} · Beregnet på danske gennemsnitstal 2026",
  "report.disclaimer": "Budgetværktøj — ikke finansiel rådgivning",
  "report.bufferMonths": "{n} md.",

  // Cockpit
  "cockpit.income": "Indkomst",
  "cockpit.partner": "Partner",
  "cockpit.expenses": "Udgifter",
  "cockpit.disposable": "Til rådighed",
  "cockpit.total": "I alt",
  "cockpit.distribution": "Pengenes fordeling",
  "cockpit.savingsPotential": "Besparelsespotentiale",
  "cockpit.seePlan": "Se plan ↓",
  "cockpit.insights": "Hvordan klarer du dig?",
  "cockpit.bucket.drift": "Drift",
  "cockpit.bucket.driftTip": "Faste udgifter: bolig, mad, transport, forsikring",
  "cockpit.bucket.frihed": "Frihed",
  "cockpit.bucket.frihedTip": "Til overs efter faste udgifter — dit rådighedsbeløb",
  "cockpit.bucket.fremtid": "Fremtid",
  "cockpit.bucket.fremtidTip": "Opsparing og pensionsbidrag",
  "cockpit.bucket.risiko": "Risiko",
  "cockpit.bucket.risikoTip": "Gæld og varierende udgifter",
  "cockpit.alert.overBudget": "Du bruger {amount} kr. mere end du tjener",
  "cockpit.alert.housingHigh": "Bolig udgør {pct}% af indkomsten — over anbefalede 35%",
  "cockpit.alert.streamingMany": "{count} streamingtjenester — gennemsnitsdansker har 2",
  "cockpit.alert.savingsStrong": "Stærk opsparingsrate på {pct}%",
  "cockpit.live.electricity": "El: {price} kr/kWh",
  "cockpit.live.rate": "Rente: {rate}%",
  "cockpit.live.income": "Gns. indkomst: {amount} kr.",

  // Categories (used by Sankey, budget overview, etc.)
  "cat.Bolig": "Bolig",
  "cat.Forsyning": "Forsyning",
  "cat.Transport": "Transport",
  "cat.Abonnementer": "Abonnementer",
  "cat.Forsikring": "Forsikring",
  "cat.Fagforening": "Fagforening",
  "cat.Børn": "Børn",
  "cat.Kæledyr": "Kæledyr",
  "cat.Lån": "Lån",
  "cat.Fitness": "Fitness",
  "cat.Opsparing": "Opsparing",
  "cat.Mad & dagligvarer": "Mad & dagligvarer",
  "cat.Fritid": "Fritid",
  "cat.Tøj": "Tøj",
  "cat.Sundhed": "Sundhed",
  "cat.Restaurant": "Restaurant",
  "cat.Andet": "Andet",

  // Sankey / overview
  "sankey.incomeDistribution": "Indkomst fordelt på udgifter",
  "sankey.leftOver": "Til overs",
  "sankey.salary": "Løn",
  "sankey.partner": "Partner",
  "sankey.otherIncome": "Øvrig",
  "sankey.income": "Indkomst",
  "sankey.expenses": "Udgifter",
  "sankey.whatIf": "Hvad nu hvis?",
  "sankey.reset": "Nulstil",
  "sankey.perMonth": "kr./md.",
  "sankey.saved": "sparet",
  "sankey.extra": "ekstra",
  // V2 features
  "sankey.privacy": "Privat",
  "sankey.privacyTip": "Skjul beløb — vis kun procenter",
  "sankey.benchmark": "50/30/20",
  "sankey.benchmarkTip": "Sammenlign dit budget med tommelfingerreglen",
  "sankey.projection": "Sparemål",
  "sankey.projectionTip": "Hvad kan du spare med dette budget?",
  "sankey.share": "Del",
  "sankey.shareTip": "Kopiér diagram som billede",
  "sankey.needs": "Behov",
  "sankey.wants": "Ønsker",
  "sankey.savingsLabel": "Opsparing",
  "sankey.recommended": "Anbefalet",
  "sankey.actual": "Faktisk",
  "sankey.projMonths": "{n} md.",
  "sankey.projSaved": "Sparepotentiale",
  "sankey.projTotal": "Med dette budget efter {n} md.",
  "sankey.projDisclaimer": "Baseret på dit nuværende budget — ikke historisk data",
  "sankey.ofIncome": "af indkomst",
  "sankey.dkAvg": "DK gns.",
  "sankey.items": "poster",
  "sankey.drillDown": "Klik for detaljer",
  "sankey.collapse": "Luk",
  "sankey.copied": "Kopieret!",
  "sankey.export": "Eksportér",
  "sankey.exportTip": "Gem som billede — perfekt til deling",
  "sankey.exportBrand": "nemtbudget.nu",
  "sankey.exportMadeWith": "Lavet med",
  "sankey.milestone.saver": "Stærk opsparer! Du sparer {pct}%",
  "sankey.milestone.balanced": "Balanceret budget!",
  "sankey.insight.highHousing": "Bolig udgør {pct}% — over anbefalet 30%",
  "sankey.insight.goodSavings": "Din opsparingsrate på {pct}% er over gennemsnittet",
  "sankey.insight.lowFree": "Kun {amount} til overs — overvej at reducere",
  "sankey.insight.streaming": "{count} streamingtjenester — overvej at samle",
  "sankey.insight.topCat": "{cat} er din største udgift ({pct}%)",

  // Dashboard misc
  "dash.startOver": "Start forfra",
  "dash.reset": "Nulstil",
  "dash.disclaimer": "NemtBudget er et budgetværktøj — ikke finansiel rådgivning.",
  "dash.aiTitle": "Lad AI finde dine besparelser",
  "dash.aiSubtitle": "Guidet gennemgang — du bestemmer hvad du vil gøre",
  "dash.useDefaults": "Brug standardtal og se mit resultat →",
  "dash.hideDetails": "Skjul detaljer",
  "dash.showCarDetails": "Fordel udgifter på bil",

  // Neighbor comparison
  "neighbor.comparedWith": "Sammenlignet med din indkomstgruppe",
  "neighbor.pair": "par",
  "neighbor.single": "enlig",
  "neighbor.housingCost": "Boligudgift:",
  "neighbor.categoryByCategory": "Kategori for kategori",
  "neighbor.onPar": "På niveau",
  "neighbor.savingsIfLowered": "Hvis du sænker til typisk niveau, sparer du",
  "neighbor.food": "Mad & dagligvarer",
  "neighbor.restaurant": "Restaurant & takeaway",
  "neighbor.transportCar": "Transport (bil)",
  "neighbor.transport": "Transport",
  "neighbor.streaming": "Streaming & abonnementer",
  "neighbor.leisure": "Fritid & oplevelser",

  // Optimization
  "optimize.totalPotential": "Samlet potentiale",
  "optimize.lookingGood": "Din økonomi ser stærk ud",
  "optimize.noSavings": "Vi fandt ingen åbenlyse besparelser — godt gået!",
  "optimize.doItNow": "Gør det nu — ",
  "optimize.dstBenchmark": "Danmarks Statistik benchmark",
  "optimize.dkAverage": "DK-gennemsnit",
  "optimize.yourDisposable": "Jeres rådighedsbeløb",

  // Couple split
  "couple.incomeBasedSplit": "Indkomstfordelt",
  "couple.partnerIncome": "Partners indkomst",
  "couple.partnerPays": "Partner betaler",
  "couple.expenses": "Udgifter",
  "couple.remaining": "Rest",

  // Profile edit
  "profile.householdIncome": "Husstand & Indkomst",
  "profile.partnerIncomeNet": "Partners indkomst (netto)",
  "profile.housing": "Bolig",
  "profile.housingType": "Boligtype",
  "profile.food": "Mad & dagligvarer",
  "profile.leisure": "Fritid & oplevelser",
  "profile.clothing": "Tøj & sko",

  // Forward view
  "forward.propertyValue": "Boligværdi",
  "forward.propertyEstimate": "Boligværdi er et estimat — justér i din profil",
  "forward.emergencyBuffer": "Nødbuffer (3 mdr.)",
  "forward.savingsRate": "Opsparingsrate",

  // Charts
  "charts.disposable": "Rådighedsbeløb",
  "charts.average": "Gennemsnit",
  "charts.lowest": "Laveste",
  "charts.highest": "Højeste",
  "charts.monthNames": "Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec",
  "charts.seasonalTitle": "Forventet rådighedsbeløb",
  "charts.seasonalSubtitle": "Estimeret baseret på sæsonudsving i danske husholdninger",
  "charts.seasonalDisclaimer": "Baseret på gennemsnitlige sæsonudsving — ikke dine faktiske tal",

  // AI chat
  "ai.askAbout": "Spørg AI om din økonomi",
  "ai.askShort": "Spørg AI",
  "ai.limitReached": "Månedlig grænse nået. Nulstilles automatisk næste måned.",

  // Guided saving
  "guided.title": "Guidet besparelses-session",
  "guided.found": "Fundet",
  "guided.totalFreed": "I alt frigjort",

  // Share card
  "share.economyCheck": "Økonomi-check",
  "share.freedomNumber": "Frihedstal",
  "share.savingsRate": "Opsparingsrate",
  "share.buffer": "Buffer",
  "share.footer": "Beregnet med NemtBudget · 2026",

  // Subscriptions
  "subs.warning": "Over 2.000 kr./md. i abonnementer — overvej at skære ned",
  "subs.foundInBudget": "Fundet i dit budget",

  // Profile edit (extra)
  "profile.title": "Ret dine oplysninger",
  "profile.saved": "Ændringer gemt",
  "profile.savedDesc": "Dit budget er opdateret.",
  "profile.householdType": "Husstandstype",
  "profile.solo": "Enlig",
  "profile.couple": "Par",
  "profile.yourIncome": "Din indkomst (netto)",
  "profile.postalCode": "Postnummer",
  "profile.rentPayment": "Husleje/ydelse",
  "profile.monthlyPayment": "Månedlig boligydelse",
  "profile.interestRate": "Rente (%)",
  "profile.spending": "Forbrug",
  "profile.restaurantTakeaway": "Restauranter & takeaway",
  "profile.healthMedicine": "Sundhed & medicin",
  "profile.transport": "Transport",
  "profile.hasCar": "Har bil",
  "profile.carLoan": "Billån (md.)",
  "profile.carFuel": "Benzin/el (md.)",
  "profile.carInsurance": "Bilforsikring (md.)",
  "profile.subscriptions": "Abonnementer",
  "profile.loansAndSavings": "Lån & Opsparing",
  "profile.hasLoan": "Har lån",
  "profile.loanPayment": "Lånebetaling (md.)",
  "profile.savesUp": "Sparer op",
  "profile.savingsMonthly": "Opsparing (md.)",
  "profile.insurances": "Forsikringer",
  "profile.insuranceMonthly": "Forsikring (md.)",
  "profile.saveChanges": "Gem ændringer",

  // Subscriptions (extra)
  "subs.title": "Abonnementer",
  "subs.addedManually": "Tilføjet manuelt",
  "subs.namePlaceholder": "Navn (f.eks. ChatGPT Plus)",
  "subs.pricePlaceholder": "Pris pr. måned",
  "subs.add": "Tilføj",
  "subs.cancel": "Annullér",
  "subs.addSubscription": "Tilføj abonnement",

  // GuidedSaving (extra)
  "guided.goalReached": "Du har nået dit mål!",
  "guided.goalReachedDesc": "Du frigjorde {amount} kr./md. i alt.",
  "guided.skipped": "Sprang over: {label}",
  "guided.whatIsYourGoal": "Hvad er dit mål?",
  "guided.goalDesc": "Jeg gennemgår dit budget og finder de nemmeste besparelser — du beslutter hvad du vil gøre.",
  "guided.currentDisposable": "Dit nuværende rådighedsbeløb er {amount} kr./md.",
  "guided.skip": "Spring over",
  "guided.apply": "Anvend",
  "guided.goalReachedTitle": "Mål nået!",
  "guided.sessionDone": "Sessionen er færdig",
  "guided.reviewedAll": "Du har gennemgået alle forslag.",
  "guided.acceptedChanges": "Accepterede ændringer",
  "guided.noChanges": "Ingen ændringer valgt.",
  "guided.seeUpdated": "Se opdateret budget",
  "guided.undo": "Fortryd",
  "guided.undoLast": "Fortryd seneste ændring",
  "guided.undone": "Fortrudt: {label}",
  "guided.noResponse": "Ingen respons",
  "guided.errorRetry": "Noget gik galt. Prøv igen.",
  "guided.goalExtra": "— med {amount} kr. mere vil du have",
  "guided.findGoal": "Find {amount}",
  "guided.progressLabel": "{found} / {goal}",
  "guided.withThis": "Med dette: {found} / {goal} fundet",

  // Forward view (extra)
  "forward.wealthProjection": "Formue-projektion",
  "forward.years": "år",
  "forward.estimatedWealth": "Estimeret formue (bolig)",
  "forward.estDebt": "Est. gæld (~70%)",
  "forward.netWorth": "Nettoformue",
  "forward.goalsProgress": "Mål & fremskridt",
  "forward.rateShockSim": "Rentechok-simulator",
  "forward.vulnerableEconomy": "Sårbar økonomi",
  "forward.refinanceAdvice": "Refinansiering kan reducere jeres eksponering.",
  "forward.timeline": "Tidslinje – næste 10 år",
  "forward.noEvents": "Ingen store begivenheder fundet baseret på jeres profil.",

  // ParSplit (extra)
  "couple.desc": "Se hvordan jeres fælles udgifter kan fordeles retfærdigt.",
  "couple.yourIncome": "Din indkomst",
  "couple.expenseDistribution": "Udgiftsfordeling",
  "couple.youPay": "Du betaler",
  "couple.evenSplit": "Jævn fordeling — begge har ca. lige meget til rådighed",
  "couple.youHaveMore": "Du har {amount} kr. mere til rådighed end din partner",
  "couple.partnerHasMore": "Din partner har {amount} kr. mere til rådighed end dig",
  "couple.visualization": "Visualisering",
  "couple.tip": "Med indkomstfordelt model betaler I relativt til jeres løn — prøv den!",

  // AI chat (extra)
  "ai.personalAdvisor": "Din personlige rådgiver",
  "ai.analyzing": "AI analyserer din økonomi...",
  "ai.usedFreeAnswers": "Du har brugt dine 5 gratis AI-svar",
  "ai.createAccount": "Opret konto — hold øje med premium",
  "ai.answersLeft": "AI-svar tilbage denne måned",
  "ai.placeholder": "Stil et spørgsmål om din økonomi...",

  // History
  "history.noHistory": "Ingen historik endnu",
  "history.noHistoryDesc": "Din historik vises her når du har brugt NemtBudget i mere end en måned. Hver gang du opdaterer dit budget, gemmer vi et snapshot — så du kan se din udvikling over tid.",
  "history.oneSnapshot": "1 snapshot gemt · Opdater dit budget igen for at se en graf",
  "history.disposableSinceStart": "Rådighedsbeløb siden start",
  "history.healthSinceStart": "Sundhedsscore siden start",
  "history.disposableOverTime": "Rådighedsbeløb over tid",
  "history.healthOverTime": "Sundhedsscore over tid",
  "history.calculationsSaved": "{count} beregninger gemt",
  "history.first": "Første",
  "history.latest": "Seneste",

  // Editable amount
  "edit.clickToEdit": "Klik for at redigere",
  "edit.cancel": "Annuller",
  "edit.save": "Gem",

  // Onboarding UI
  "onboarding.leftOver": "Til overs",
  "onboarding.seeOverview": "Se overblik",
  "onboarding.stepOf": "Trin {current} af {total}",

  // Optimize (extra)
  "optimize.opensExternal": "Åbner ekstern side",
  "optimize.savePerMonth": "Spar {amount} kr./md.",

  // Auth page
  "auth.pageTitle": "Log ind — NemtBudget",
  "auth.pageDesc": "Log ind eller opret en gratis konto for at synkronisere dit budget på tværs af enheder.",
  "auth.enterEmail": "Indtast e-mail",
  "auth.enterEmailDesc": "Skriv din e-mail ovenfor, så sender vi et link til nulstilling.",
  "auth.error": "Fejl",
  "auth.checkEmail": "Tjek din e-mail",
  "auth.checkEmailDesc": "Vi har sendt et link til nulstilling af din adgangskode.",
  "auth.loginSubtitle": "Log ind for at synkronisere dit budget",
  "auth.signupSubtitle": "Opret konto og gem dit budget i skyen",
  "auth.emailPlaceholder": "E-mail",
  "auth.passwordPlaceholder": "Adgangskode",
  "auth.waiting": "Vent...",
  "auth.login": "Log ind",
  "auth.signup": "Opret konto",
  "auth.forgotPassword": "Glemt kodeord?",
  "auth.noAccount": "Har du ingen konto? Opret gratis",
  "auth.hasAccount": "Har du allerede en konto? Log ind",
  "auth.continueWithout": "← Fortsæt uden login",
  "auth.newPasswordSubtitle": "Vælg en ny adgangskode",
  "auth.newPasswordPlaceholder": "Ny adgangskode",
  "auth.resetPassword": "Nulstil adgangskode",
  "auth.passwordMinLength": "Adgangskoden skal være mindst 6 tegn.",
  "auth.passwordResetSuccess": "Adgangskode opdateret",
  "auth.passwordResetSuccessDesc": "Din adgangskode er blevet ændret. Du kan nu logge ind.",
  "auth.sessionExpired": "Session udløbet",
  "auth.sessionExpiredDesc": "Din session er udløbet. Log ind igen for at synkronisere.",

  // Install page
  "install.pageTitle": "Installér NemtBudget — Gratis budget-app",
  "install.pageDesc": "Installér NemtBudget som app på din telefon — uden app store. Få hurtigt overblik over dit budget.",
  "install.installed": "NemtBudget er installeret!",
  "install.title": "Installér NemtBudget",
  "install.installedDesc": "Åbn appen fra din hjemmeskærm for den bedste oplevelse.",
  "install.desc": "Få NemtBudget som app på din telefon — uden app store.",
  "install.goToApp": "Gå til NemtBudget →",
  "install.installNow": "Installér nu",
  "install.iosTitle": "Sådan installerer du på iPhone:",
  "install.iosStep1": "Tryk på",
  "install.iosStep1Share": "Del ↑",
  "install.iosStep1Suffix": "i Safari",
  "install.iosStep2": "Vælg \"Føj til hjemmeskærm\"",
  "install.iosStep3": "Tryk \"Tilføj\"",
  "install.openInBrowser": "Åbn denne side i Chrome eller Safari for at installere appen.",
  "install.back": "← Tilbage til NemtBudget",

  // NotFound page
  "notFound.title": "404",
  "notFound.message": "Ups! Siden blev ikke fundet",
  "notFound.link": "Tilbage til forsiden",

  // AI Welcome Insight
  "ai.insightLabel": "AI Indsigt",
  "ai.fallback": "Din økonomi er klar til analyse. Gå videre til dit dashboard for det fulde overblik.",

  // NaboeffektView
  "neighbor.aheadOfAvgPar": "I er foran gennemsnittet",
  "neighbor.aheadOfAvgSolo": "Du er foran gennemsnittet",
  "neighbor.moreLeftPar": "I har",
  "neighbor.moreLeftSolo": "Du har",
  "neighbor.moreLeftSuffix": "kr. mere til overs end andre med din profil.",
  "neighbor.potentialSaving": "Potentiel besparelse:",
  "neighbor.biggestOpportunity": "Største mulighed:",
  "neighbor.overTypical": "kr. over typisk",
  "neighbor.ofIncome": "af indkomsten",
  "neighbor.expertsRecommend": "Eksperter anbefaler maks 33% —",
  "neighbor.youUsePar": "I bruger",
  "neighbor.youUseSolo": "du bruger",
  "neighbor.percentPointMore": "procentpoint mere",
  "neighbor.adjustFood": "Justér madbudget",
  "neighbor.seeSavings": "Se besparelsesforslag",
  "neighbor.seeTransport": "Se transportoptimering",
  "neighbor.reviewSubs": "Gennemgå abonnementer",
  "neighbor.seeLeisure": "Se fritidsbudget",
  "neighbor.optimize": "Optimer",
  "neighbor.youLabel": "Dig",
  "neighbor.youLabelPar": "Jer",
  "neighbor.typicalLabel": "Typisk",
  "neighbor.industryLabel": "Typisk ({industry})",
  "neighbor.benchmarkIndustry": "Justeret for branche.",
  "neighbor.perYear": "kr. om året",
  "neighbor.benchmarkFootnote": "Benchmarks baseret på Danmarks Statistik —",
  "neighbor.benchmarkSingles": "enlige",
  "neighbor.benchmarkCouples": "par",
  "neighbor.benchmarkSuffix": "i din indkomstgruppe · 2025",

  // ProfileEditSheet housing types
  "profile.housingLeje": "Leje",
  "profile.housingEjer": "Ejer",
  "profile.housingAndel": "Andel",
  "profile.housingUngdomsbolig": "Ungdomsbolig",
  "profile.netflix": "Netflix (149 kr.)",
  "profile.spotify": "Spotify (109 kr.)",
  "profile.hboMax": "HBO Max (99 kr.)",
  "profile.viaplay": "Viaplay (99 kr.)",
  "profile.disneyPlus": "Disney+ (99 kr.)",
  "profile.appleTvPlus": "Apple TV+ (59 kr.)",
  "profile.amazonPrime": "Amazon Prime (89 kr.)",

  // FremadView extras
  "forward.expectedWealth": "Forventet formue",
  "forward.interestLabel": "Rente:",
  "forward.ofGoal": "af mål",
  "forward.goalLabel": "mål",
  "forward.exceedsRecommendation": "Du overstiger anbefalingen!",
  "forward.currentLabel": "Aktuel",
  "forward.leftAfter": "kr. tilbage",
  "forward.mortgageSearch": "Boliglån",
  "forward.seeRefinance": "Se hvad refinansiering kan gøre →",

  // ShareCard
  "share.brandName": "NemtBudget",
  "share.brandUrl": "nemtbudget.nu",
  "share.bucketDrift": "Drift",
  "share.bucketFrihed": "Frihed",
  "share.bucketFremtid": "Fremtid",
  "share.bucketRisiko": "Risiko",

  // Units (extra)
  "unit.krKwh": "kr/kWh",
  "unit.possible": "muligt",

  // LossAversionInsights
  "insights.heading": "Indsigter baseret på dine tal",
  "insights.incomeBadge": "Indkomst vs. nabolag",
  "insights.neighborLabel": "postnummer {postal}",
  "insights.incomeBelow": "Du tjener {amount} kr./md. under gennemsnittet i {postal}",
  "insights.incomeBelowValue": "−{amount} {unit}/år",
  "insights.incomeBelowSub": "Gennemsnitsindkomsten i dit postnummer er {avg} kr./md. efter skat. Det er ikke nødvendigvis et problem — men det er værd at vide. (Kilde: {source})",
  "insights.incomeAbove": "Du tjener {amount} kr./md. over gennemsnittet i {postal}",
  "insights.incomeAboveValue": "+{amount} {unit}/år",
  "insights.incomeAboveSub": "Gennemsnitsindkomsten i dit postnummer er {avg} kr./md. efter skat. Du er altså over midten — udnytter dit budget det fuldt ud? (Kilde: {source})",
  "insights.subsBadge": "Abonnementer pr. år",
  "insights.subsTitle": "{count} streamingtjenester koster {amount} kr. om året",
  "insights.subsSub": "De fleste bruger 1-2 aktivt. Koster de hver for sig: Netflix {netflix}, Viaplay {viaplay}, HBO {hbo} kr./år. Går du på skift, er der penge at hente.",
  "insights.savingsBadge": "Opsparingsmulighed",
  "insights.savingsTitle": "Du har {amount} kr./md. til overs — men sparer intet op",
  "insights.savingsSub": "{monthly} kr./md. i et globalt indeksfond (historisk ~7%/år) giver {total} kr. om 15 år med rentes rente. For hver måned der går uden opsparing mister du dette potentiale.",
  "insights.elCheapNowBadge": "El billigst nu ⚡",
  "insights.elCheapBadge": "Billigste el i dag",
  "insights.elCheapNowTitle": "El er billigst lige nu ({price} kr/kWh) — sæt opvasker og tørretumbler på",
  "insights.elScheduleTitle": "Sæt opvasker og vaskemaskine til at køre kl. {hours}",
  "insights.elSavingSub": "{saving} kr/kWh billigere end det dyreste tidspunkt i dag. Kører du tørretumbler (2 kWh) til {cheap} vs {expensive} kr/kWh sparer du {total} kr. på én tur. (Live data: Energi Data Service)",
  "insights.elLiveSub": "Baseret på live Elspot-data fra Energi Data Service, opdateret i dag.",

  // B2B page
  "b2b.heroTag": "B2B Partnership",
  "b2b.heroTitle": "Giv jeres kunder Danmarks smarteste",
  "b2b.heroTitleHighlight": "budgetværktøj",
  "b2b.heroTitleSuffix": "— under jeres eget brand",
  "b2b.heroSubtitle": "NemtBudget er en AI-drevet budget-platform klar til white-label. Integrer den i jeres kundeoplevelse på under 2 uger — ingen bankkobling påkrævet.",
  "b2b.liveDemo": "Se live demo",
  "b2b.contactUs": "Kontakt os",
  "b2b.whyTitle": "Hvorfor banker vælger NemtBudget",
  "b2b.whiteLabelReady": "White-label klar",
  "b2b.whiteLabelDesc": "Jeres logo, farver og branding. Kunderne oplever det som jeres eget produkt. Ingen synlig reference til NemtBudget.",
  "b2b.aiPowered": "AI-drevet",
  "b2b.aiPoweredDesc": "Personlige anbefalinger, optimeringsforslag og intelligent chat. Powered by Claude — verdens mest avancerede AI.",
  "b2b.privacyFirst": "Privacy-first",
  "b2b.privacyFirstDesc": "Ingen bankkobling nødvendig. Brugerne indtaster selv — fuld kontrol, ingen compliance-hovedpine.",
  "b2b.featureTitle": "Alt hvad jeres kunder har brug for",
  "b2b.featureSubtitle": "Overblik, Sankey-flow, AI-optimering, fremtidsprojektion og meget mere.",
  "b2b.feat.cockpit": "Budget-cockpit",
  "b2b.feat.cockpitDesc": "Overblik over indkomst, udgifter og rådighed på ét dashboard.",
  "b2b.feat.sankey": "Sankey-diagram",
  "b2b.feat.sankeyDesc": "Visualiser pengestrømme fra indkomst til udgifter.",
  "b2b.feat.aiOpt": "AI-optimering",
  "b2b.feat.aiOptDesc": "Personlige forslag til besparelser baseret på brugerens profil.",
  "b2b.feat.projection": "Fremtidsprojektion",
  "b2b.feat.projectionDesc": "Se hvordan økonomien udvikler sig over 1-5 år.",
  "b2b.feat.stress": "Stress-test",
  "b2b.feat.stressDesc": "Hvad sker der ved rentestigning eller jobskifte?",
  "b2b.feat.neighbor": "Naboeffekten",
  "b2b.feat.neighborDesc": "Sammenlign med andre i samme postnummer.",
  "b2b.brandTitle": "Se det i jeres brand",
  "b2b.brandSubtitle": "Prøv vores live demos med Nordea og Danske Bank branding.",
  "b2b.pricingTitle": "Simpel og gennemsigtig prissætning",
  "b2b.pricingSubtitle": "Alle planer inkluderer setup, white-label design, drift og support.",
  "b2b.mostPopular": "Mest populær",
  "b2b.getStarted": "Kom i gang",
  "b2b.starter.users": "Op til 10.000 brugere",
  "b2b.starter.f1": "White-label design",
  "b2b.starter.f2": "Setup & onboarding",
  "b2b.starter.f3": "Drift & hosting",
  "b2b.starter.f4": "Email-support",
  "b2b.starter.f5": "Månedlig rapport",
  "b2b.growth.users": "Op til 50.000 brugere",
  "b2b.growth.f1": "Alt i Starter",
  "b2b.growth.f2": "AI-rådgivning",
  "b2b.growth.f3": "Prioriteret support",
  "b2b.growth.f4": "Custom integrationer",
  "b2b.growth.f5": "Kvartalsvise review-møder",
  "b2b.enterprise.price": "Kontakt os",
  "b2b.enterprise.users": "Ubegrænset brugere",
  "b2b.enterprise.f1": "Alt i Growth",
  "b2b.enterprise.f2": "Dedicated account manager",
  "b2b.enterprise.f3": "SLA-garanti",
  "b2b.enterprise.f4": "On-premise mulighed",
  "b2b.enterprise.f5": "API-adgang",
  "b2b.testimonialTitle": "Hvad vores partnere siger",
  "b2b.testimonialQuote": "Vi er i gang med at onboarde vores første bankpartnere. Kontakt os for referencer.",
  "b2b.testimonialLink": "Kontakt os for referencer",
  "b2b.contactTitle": "Kontakt os",
  "b2b.contactSubtitle": "Udfyld formularen, så vender vi tilbage inden for 24 timer.",
  "b2b.thankYou": "Tak for din henvendelse!",
  "b2b.thankYouDesc": "Din email-klient åbner nu med en forudfyldt besked. Vi vender tilbage hurtigst muligt.",
  "b2b.labelName": "Navn",
  "b2b.labelCompany": "Virksomhed",
  "b2b.labelEmail": "Email",
  "b2b.labelMessage": "Besked",
  "b2b.placeholderName": "Dit navn",
  "b2b.placeholderCompany": "Virksomhedens navn",
  "b2b.placeholderMessage": "Fortæl os om jeres behov...",
  "b2b.submit": "Send henvendelse",
  "b2b.emailSubject": "B2B henvendelse fra {company}",

  // Partner page
  "partner.noToken": "Ingen token",
  "partner.invalidToken": "Ugyldigt token",
  "partner.contactEmail": "Kontakt hej@nemtbudget.nu",
  "partner.noActivity": "Ingen aktivitet endnu",
  "partner.noEvents": "Ingen events endnu",
  "partner.uniqueSessions": "Unikke sessioner",
  "partner.uniqueSessionsSub": "Unikke brugere der har åbnet værktøjet",
  "partner.budgetsCreated": "Budgetter oprettet",
  "partner.conversion": "{pct}% konvertering",
  "partner.aiQuestions": "AI-spørgsmål",
  "partner.aiQuestionsSub": "Spørgsmål til AI-rådgiveren",
  "partner.reports": "Rapporter",
  "partner.reportsSub": "Downloadede økonomirapporter",
  "partner.dailyActivity": "Daglig aktivitet — seneste 30 dage",
  "partner.memberUsage": "Hvad bruger dine medlemmer?",
  "partner.event.onboarding_start": "Startede onboarding",
  "partner.event.onboarding_complete": "Gennemførte budgetberegning",
  "partner.event.dashboard_view": "Åbnede dashboard",
  "partner.event.ai_chat_open": "Åbnede AI-rådgiveren",
  "partner.event.ai_message_sent": "Stillede spørgsmål til AI",
  "partner.event.report_generated": "Genererede økonomirapport",
  "partner.embedTitle": "Integration — embed kode",
  "partner.embedSub": "Virker i enhver webportal på 5 minutter",
  "partner.copyCode": "Kopiér kode",
  "partner.dashboard": "Partner Dashboard",

  // Blog page
  "blog.searchPlaceholder": "Søg i guides...",
  "blog.readTime": "læsetid",
  "blog.headerTitle": "Guides & tips",
  "blog.heroTitle": "Bliv klogere på din økonomi",
  "blog.heroSubtitle": "Praktiske guides, sparetips og beregninger bygget til dansk privatøkonomi.",
  "blog.ctaTitle": "Prøv {brand} gratis",
  "blog.ctaSubtitle": "Beregn dit rådighedsbeløb på 3 minutter",
  "blog.ctaButton": "Kom i gang →",

  // Article page
  "article.guides": "Guides",
  "article.ctaTitle": "Beregn dit eget rådighedsbeløb",
  "article.ctaSubtitle": "Gratis · 3 minutter · Ingen login",
  "article.ctaButton": "Prøv {brand} →",

  // Onboarding extras
  "onboarding.perMonthAfterExpenses": "pr. måned efter alle udgifter",
  "onboarding.estimatedAdjust": "Vi har estimeret disse — ret dem hvis de ikke passer",
  "onboarding.everydayExpenses": "Hverdagsudgifter",
  "onboarding.ofIncome": "af indkomst",

  // Dashboard extras
  "dash.sectionTabs": "Sektionstabs",

  // FremadView timeline events
  "forward.childN": "Barn",
  "forward.yourChild": "Dit barn",
  "forward.startsSFO": "starter i SFO",
  "forward.sfoDesc": "SFO-udgift 2.100 kr./md.",
  "forward.leavesKindergarten": "forlader børnehave",
  "forward.kindergartenDesc": "Institutionsudgift falder 2.600 kr./md.",
  "forward.turns7": "fylder 7 – børneydelse falder",
  "forward.turns7Desc": "Reduceres med 1.130 kr./md.",
  "forward.leavesSFO": "ud af SFO",
  "forward.leavesSFODesc": "SFO-udgift bortfalder.",
  "forward.turns18": "fylder 18",
  "forward.childBenefitEnds": "Børneydelse bortfalder.",
  "forward.checkInterestOnly": "Tjek afdragsfrihed",
  "forward.checkInterestOnlyDesc": "Mange lån fra 2018–2020 har 10-årig afdragsfrihed.",
  "forward.basedOnInvested": "Baseret på {amount} investeret",
  "forward.projectionPrefix": "med 7% årligt afkast giver estimeret ca.",
  "forward.projectionMid": "på 5 år og ca.",
  "forward.projectionSuffix": "på 10 år. Investering indebærer risiko.",
  "forward.increaseToReach20": "Øg med {amount} for at nå 20%",
  "unit.krMonth": "kr./md.",
  "unit.krYear": "kr./år",
  "unit.krHalfYear": "kr./halvår",
  "unit.currency": "kr.",

  // AIChatPanel suggestion questions
  "ai.q.christmasBudget": "Hvordan klarer mit budget julen?",
  "ai.q.summerSavings": "Kan jeg spare op til sommerferie?",
  "ai.q.switchInsurance": "Skal jeg skifte forsikring ved fornyelse?",
  "ai.q.cutMost": "Hvor kan jeg skære mest?",
  "ai.q.carCost": "Hvad koster min bil reelt?",
  "ai.q.dropStreaming": "Hvilken streaming kan jeg droppe?",
  "ai.q.rateRise": "Hvad hvis renten stiger 2%?",
  "ai.q.startSaving": "Hvordan starter jeg med at spare op?",

  // Dashboard terms link
  "dash.termsLink": "Vilkår",

  // Subscriptions (units)
  "subs.activeCount": "aktive abonnementer",

  // Optimization (units)
  "optimize.perYearFollowPlan": "ved at følge planen",

  // Couple split
  "couple.remaining.suffix": "tilbage",

  // History
  "history.points": "point",
  "history.tooltipDisposable": "Rådighed",

  // Onboarding
  "onboarding.adjustAmount": "Ret beløbet ovenfor hvis det ikke passer.",
  "onboarding.emailReminder": "Ja tak, send mig en kvartalsvis påmindelse om at tjekke mit budget.",
  "onboarding.emailUnsubscribe": "Du kan altid afmelde dig.",
  "onboarding.expenseShare": "Udgiftsandel",
  "step.income.minWarning": "Indtast mindst 1.000 kr. i samlet indkomst for at fortsætte.",
  "onboarding.encourage.income": "Super! Nu ved vi hvem du er 🎯",
  "onboarding.encourage.housing": "Godt klaret — nu tager vi boligen 🏠",
  "onboarding.encourage.everyday": "Halvvejs! Boligen er på plads ✅",
  "onboarding.encourage.fixed": "Næsten færdig — bare de faste udgifter 📋",
  "onboarding.encourage.review": "Sidste trin — du er næsten i mål! 🏁",

  // Error boundary
  "error.somethingWrong": "Noget gik galt",
  "error.unexpectedError": "Der opstod en uventet fejl. Prøv at genindlæse siden.",
  "error.reloadPage": "Genindlæs siden",

  // Section error boundary
  "error.sectionFailed": "kunne ikke vises",
  "error.tryReload": "Prøv at genindlæse siden",
  "error.tryAgain": "Prøv igen",

  // Page loader
  "loader.loading": "Indlæser...",

  // Demo banner
  "demo.text": "Demo — NemtBudget white-label til {brand}. Al data er eksempeldata.",
  "demo.bookPresentation": "Book præsentation",
  "demo.trySelf": "Prøv selv",
  "demo.closeBanner": "Luk demo-banner",

  // Suite nav
  "nav.comingSoon": "Snart",

  // Dark mode toggle
  "darkMode.switchToLight": "Skift til lyst tema",
  "darkMode.switchToDark": "Skift til mørkt tema",

  // Cookie banner
  "cookie.consent": "Cookie-samtykke",
  "cookie.acceptAnalytics": "Accepter analytics-cookies",
  "cookie.declineAnalytics": "Afvis analytics-cookies",
  "cookie.settings": "Cookie-indstillinger",
  "cookie.changeAnytime": "Du kan til enhver tid ændre dit cookie-valg via \"Cookie-indstillinger\" i sidefoden.",

  // Cockpit
  "cockpit.alertsLabel": "Advarsler",
  "cockpit.critical": "Kritisk",
  "cockpit.warning": "Advarsel",
  "cockpit.insight": "Indsigt",

  // Share card
  "share.bufferUnit": "md.",

  // Share budget deep-link
  "share.title": "Del dit budget",
  "share.description": "Tilføj kontekst så andre forstår din situation",
  "share.copyLink": "Kopier",
  "share.copied": "Kopieret!",
  "share.privacyNote": "Linket indeholder kun de tal og kontekst du selv vælger — ingen postnummer, e-mail eller persondata deles.",
  "share.reddit": "Del på r/dkfinance",
  "share.chars": "tegn",
  "share.autoContext": "Din profil viser automatisk",
  "share.addContext": "Tilføj kontekst (valgfrit)",
  "share.agePlaceholder": "Alder",
  "share.jobPlaceholder": "Stilling",
  "share.cityPlaceholder": "By",
  "share.questionPlaceholder": "Hvad vil du gerne have feedback på?",
  "share.generateLink": "Generer delings-link",
  "share.generating": "Genererer...",
  "share.tagSolo": "Single",
  "share.tagCouple": "Par",
  "share.tagChildren": "{count} børn ({ages})",
  "share.tagRenter": "Lejer",
  "share.tagOwner": "Ejer",
  "share.tagCoop": "Andel",
  "share.tagCar": "Bil",
  "share.tagSaves": "Opsparer",
  "share.tagYears": "år",
  "share.preview": "Sådan ser det ud for modtageren",
  "share.q.canBuyHome": "Kan jeg/vi købe bolig?",
  "share.q.refinance": "Bør jeg omlægge mit lån?",
  "share.q.tooMuchStreaming": "Bruger jeg for meget på streaming?",
  "share.q.carWorth": "Er min bil-økonomi fornuftig?",
  "share.q.canAffordCar": "Har jeg råd til bil?",
  "share.q.howToSave": "Hvordan kommer jeg i gang med opsparing?",
  "share.q.savingsEnough": "Sparer jeg nok?",
  "share.q.maternity": "Kan vi klare os på barsel?",
  "share.q.generalFeedback": "Vurder mit budget!",
  "share.payslipToggle": "Tilføj lønseddel",
  "share.payslipTitle": "Lønseddel",
  "share.payslipHint": "Tilføj din bruttoløn for at vise hvad der sker med din løn, før den rammer kontoen.",
  "share.ps.gross": "Bruttoløn",
  "share.ps.grossLabel": "Bruttoløn (kr/md)",
  "share.ps.amBidrag": "AM-bidrag (8%)",
  "share.ps.pension": "Pension",
  "share.ps.pensionLabel": "Pension",
  "share.ps.tax": "A-skat",
  "share.ps.taxLabel": "Trækprocent",
  "share.ps.atp": "ATP",
  "share.ps.net": "Udbetalt",
  "share.ps.netShort": "netto",
  "share.modeLink": "Link",
  "share.modeImage": "Billede",
  "share.nativeShare": "Del...",
  "share.shareImage": "Del billede",
  "share.copyText": "Kopier som tekst",
  "share.copiedText": "Tekst kopieret!",
  "share.textHeader": "Mit budget",
  "share.textFooter": "Beregnet med nemtbudget.nu",
  "shared.banner": "Delt budget",
  "shared.bannerCta": "Lav dit eget budget",
  "shared.closeBanner": "Luk banner",
  "dash.share": "Del",

  // Payslip upload
  "payslip.title": "Upload din lønseddel",
  "payslip.subtitle": "Tag et billede eller upload en PDF — AI'en læser den og anonymiserer alt automatisk",
  "payslip.dropzone": "Træk filen hertil, klik for at vælge, eller indsæt med Ctrl+V",
  "payslip.pasteHint": "Tip: Du kan også bare trykke Ctrl+V med et screenshot i udklipsholderen",
  "payslip.acceptedFormats": "JPG, PNG eller PDF (max 5 MB)",
  "payslip.privacy": "Din lønseddel sendes krypteret til AI-analyse og slettes straks efter. Vi gemmer intet.",
  "payslip.journey.title": "Hvad sker der med din lønseddel?",
  "payslip.journey.step1": "Din telefon",
  "payslip.journey.step1Detail": "Billedet komprimeres i din browser",
  "payslip.journey.step2": "AI læser tallene",
  "payslip.journey.step2Detail": "Krypteret. Ingen mennesker ser det.",
  "payslip.journey.step3": "Slettet med det samme",
  "payslip.journey.step3Detail": "Kun tal sendes tilbage. Billedet er væk.",
  "payslip.journey.honest": "Ærligt: Mens AI'en læser (3-8 sek.), kan den se hele billedet — inkl. CPR og navn. Den kører i en lukket server, ingen mennesker har adgang, og billedet slettes straks efter. Vi gemmer ingenting.",
  "payslip.journey.disclaimer": "NemtBudget er et gratis budgetværktøj, ikke en rådgiver. Lønseddelanalysen kan indeholde fejl — tjek altid selv. Upload = accept af AI-behandling som beskrevet. Sløring af CPR anbefales.",
  "payslip.processing": "Læser din lønseddel...",
  "payslip.processingHint": "AI'en analyserer tal, fradrag og kontekst",
  "payslip.step1": "Upload billede eller PDF",
  "payslip.step2": "AI læser alle tal",
  "payslip.step3": "Anonymt delingskort — klar til Reddit",
  "payslip.result.title": "Din lønseddel",
  "payslip.result.employer": "Arbejdsgiver",
  "payslip.result.municipality": "Kommune",
  "payslip.result.payrollSystem": "Lønsystem",
  "payslip.result.confidenceHigh": "Høj sikkerhed",
  "payslip.result.confidenceMedium": "Middel sikkerhed",
  "payslip.result.confidenceLow": "Lav sikkerhed",
  "payslip.privateInfo": "Privat info (deles ikke)",
  "payslip.privateNote": "Disse oplysninger vises kun til dig og indgår aldrig i deling",
  "payslip.cta.share": "Del anonymt",
  "payslip.cta.budget": "Lav fuldt budget",
  "payslip.crossPromo.title": "Vil du se hvor pengene faktisk går hen?",
  "payslip.crossPromo.desc": "Upload dit kontoudtog og kombiner med lønsedlen — så pre-filler vi budgettet med både din indkomst OG dit faktiske forbrug.",
  "payslip.crossPromo.cta": "Prøv Pengetjekket",
  "payslip.cta.retry": "Prøv igen",
  "payslip.error.tooLarge": "Filen er for stor (max 5 MB)",
  "payslip.error.invalidType": "Ugyldig filtype — brug JPG, PNG eller PDF",
  "payslip.error.readFailed": "Kunne ikke læse lønsedlen — prøv et tydeligere billede",
  "payslip.deductions.gross": "Bruttoløn",
  "payslip.deductions.net": "Udbetalt",
  "payslip.deductions.amBidrag": "AM-bidrag (8%)",
  "payslip.deductions.pension": "Pension",
  "payslip.deductions.aSkat": "A-skat",
  "payslip.deductions.atp": "ATP",
  "payslip.deductions.union": "Fagforening",
  "payslip.deductions.healthIns": "Sundhedsforsikring",
  "payslip.deductions.fritvalg": "Fritvalgskonto",
  "payslip.deductions.feriepenge": "Feriepenge",
  "payslip.deductions.other": "Øvrige fradrag",
  "payslip.shareHeader": "Min lønseddel",
  "payslip.shareKeepPct": "Jeg beholder {pct}% af min bruttoløn",
  "payslip.welcomeCta": "Har du en lønseddel? Upload den og se dit budget på 10 sekunder",
  "payslip.ctaTitle": "Har du en lønseddel?",
  "payslip.ctaDesc": "Upload dit lønseddel-billede og få en komplet analyse med fradrag, lønsammenligning og delbart billede.",

  // Index page
  "confirm.resetBudget": "Er du sikker? Dette sletter dit nuværende budget og starter forfra.",
  "confirm.editProfile": "Vil du redigere dine oplysninger? Dine nuværende data bruges som udgangspunkt.",

  // Admin
  "admin.title": "SEO Indholdskø",
  "admin.draftsAwait": "udkast afventer godkendelse",
  "admin.refresh": "Opdater",
  "admin.emptyQueue": "Ingen udkast i kø. Næste artikel genereres automatisk.",
  "admin.readTime": "læsetid",
  "admin.approve": "Godkend",
  "admin.reject": "Afvis",
  "admin.published": "Artikel publiceret!",
  "admin.rejected": "Udkast afvist",
  "admin.error": "Fejl",

  // Salary comparison (payslip result page)
  "salary.comparison": "Lønsammenligning",
  "salary.yourGross": "Din bruttoløn",
  "salary.industryMedian": "Median for {industry}",
  "salary.percentile": "Du ligger i {pct}. percentil",
  "salary.aboveMedian": "over medianen",
  "salary.belowMedian": "under medianen",
  "salary.atMedian": "omkring medianen",
  "salary.fewObservations": "Baseret på få observationer — vis med forbehold",
  "salary.contributeTitle": "Hjælp andre med løngennemsigtighed",
  "salary.contributeDesc": "Del din anonyme løndata så andre kan sammenligne. Ingen persondata deles.",
  "salary.contributed": "Tak! Din anonyme løndata er registreret.",
  "salary.noData": "Ikke nok data for din branche endnu",

  // Payslip image export
  "payslip.exportImage": "Del som billede",
  "payslip.downloadImage": "Download billede",
  "payslip.exportImageDesc": "Perfekt til Reddit",
  "payslip.keepPct": "Jeg beholder {pct}% af min bruttoløn",
  "payslip.imageCopied": "Billede kopieret!",
  "payslip.imageDownloaded": "Billede downloadet!",
  "payslip.shareToReddit": "Del på r/dkloenseddel",
  "payslip.card.grossPay": "Bruttoløn",
  "payslip.card.totalDeductions": "Fradrag i alt",
  "payslip.card.netPay": "Nettoløn",
  "payslip.card.deductionBreakdown": "Fradrag",
  "payslip.card.madeWith": "Lavet med",
  "payslip.card.cta": "Lav din egen gratis",
  "payslip.card.rankBadge": "Top {pct}% i {industry}",
  "payslip.card.heroSubtitle": "udbetalt af din bruttoløn",
  "payslip.card.budgetSection": "Mit budget",
  "payslip.share.sectionTitle": "Del på Reddit",
  "payslip.share.step1": "Kopier billede",
  "payslip.share.step2": "Åbn Reddit",
  "payslip.share.step2Hint": "Indsæt billedet med Ctrl+V i Reddit-opslaget",
  "payslip.share.includeBudget": "Inkluder mit budget i billedet",
  "salary.autoContributed": "Din anonyme løndata hjælper andre med at sammenligne",
  "payslip.meta.title": "Scan din lønseddel — se skjulte goder og sammenlign din løn",
  "payslip.meta.description": "Upload din lønseddel og se præcis hvad du betaler i skat, hvad arbejdsgiveren betaler for dig, og om din løn er over eller under medianen i din branche.",
  "payslip.landing.headline": "Scan din lønseddel — se hvad du går glip af",
  "payslip.landing.subheadline": "Upload et billede eller PDF. Vi finder skjulte goder, sammenligner din løn med branchen, og laver et budget klar på 10 sekunder.",
  "payslip.landing.socialProof": "Del anonymt på r/dkloenseddel, r/dkfinance eller andre fora",

  // Deduction explanations — shown when user taps a deduction row
  "payslip.explain.amBidrag": "AM-bidrag (arbejdsmarkedsbidrag) er en skat på 8% der finansierer dagpenge, sygedagpenge og arbejdsmarkedsuddannelser. Alle lønmodtagere betaler det — det er det første der trækkes fra din løn.",
  "payslip.explain.pension": "Din pensionsopsparing består typisk af et lønmodtagerbidrag + et arbejdsgiverbidrag. Pengene investeres og udbetales når du går på pension. Jo højere pensionsprocent, jo mere sparer du op.",
  "payslip.explain.aSkat": "A-skat er din indkomstskat beregnet ud fra dit trækprocent og personfradrag. Trækprocenten afhænger af din kommune, kirkeskat, og om du har rentefradrag. Du kan tjekke din forskudsopgørelse på skat.dk.",
  "payslip.explain.atp": "ATP (Arbejdsmarkedets Tillægspension) er en lovpligtig pensionsordning. Du betaler 1/3 og din arbejdsgiver 2/3. Det giver en lille garanteret pension oveni folkepensionen.",
  "payslip.explain.fagforening": "Fagforeningskontingent dækker din faglige organisation. De forhandler din overenskomst (løn, ferie, opsigelsesvilkår) og kan hjælpe hvis du har problemer på arbejdspladsen.",
  "payslip.explain.sundhedsforsikring": "En sundhedsforsikring betalt via din løn — typisk en firmapolitik. Giver hurtigere adgang til speciallæger, fysioterapi og psykolog uden at vente i det offentlige system.",
  "payslip.explain.fritvalg": "Fritvalgskonto er en opsparingskonto fra din overenskomst. Du kan typisk bruge pengene til ekstra ferie, pension eller udbetaling. Procentsatsen er aftalt i din overenskomst.",
  "payslip.explain.feriepenge": "Feriepenge er 12,5% af din løn der sættes til side til ferie. Du får dem udbetalt når du holder ferie. Siden 2020 følger feriepenge den nye ferielov med samtidighedsferie.",

  // Normal ranges
  "payslip.range.amBidrag": "Altid 8% af indkomstgrundlaget — det her er fast for alle",
  "payslip.range.pension": "Typisk 12-17% i alt (din + arbejdsgivers andel). Under 8% er lavt.",
  "payslip.range.aSkat": "Normal trækprocent: 35-42%. Lavere med store rentefradrag, højere i dyre kommuner.",
  "payslip.range.atp": "Fast 99,45 kr/md for fuldtid (din andel). Altid det samme beløb.",
  "payslip.range.fagforening": "Typisk 300-600 kr/md. Varierer efter fagforening og forsikringsvalg.",
  "payslip.range.sundhedsforsikring": "Typisk 50-200 kr/md. Arbejdsgiverbetalt gode.",
  "payslip.range.fritvalg": "Typisk 1-7% af løn afhængig af overenskomst.",
  "payslip.range.feriepenge": "12,5% af ferieberettiget løn. Lovbestemt sats.",

  // Hero section
  "payslip.hero.youKeep": "Du beholder",
  "payslip.hero.paidOut": "udbetalt",
  "payslip.hero.annual": "Det svarer til {amount} om året",
  "payslip.hero.gross": "Bruttoløn: {monthly}/md · {annual}/år",
  "payslip.hero.atypicalMonth": "Denne måned er atypisk (engangsposter)",
  "payslip.hero.normalGross": "Normal bruttoløn: ca. {amount}/md · {annual}/år",

  // Section headers
  "payslip.section.breakdown": "Fra bruttoløn til udbetaling",
  "payslip.section.insights": "3 ting du skal vide",

  // Insight status labels
  "payslip.insight.aboveNormal": "over normalen",
  "payslip.insight.belowNormal": "under normalen",

  // Detailed insights
  "payslip.insight.effectiveTax": "Effektiv skattesats",
  "payslip.insight.effectiveTaxDetail": "Din trækprocent er {marginal}%, men din reelle skattesats er {effective}% af brutto (AM-bidrag + A-skat + ATP). Personfradrag: {personfradrag}/md.",
  "payslip.insight.pensionTitle": "Pensionssundhed",
  "payslip.insight.pensionDetail": "Din pension er {pct}% (dig: {employee} + arbejdsgiver: {employer}). Gennemsnittet er 12-17%.",
  "payslip.insight.pensionLow": "Det er under gennemsnittet — overvej at øge din pensionsindbetaling.",
  "payslip.insight.pensionGood": "Flot! Din pension er over gennemsnittet.",
  "payslip.insight.annualTitle": "Årsopgørelse",
  "payslip.insight.annualTitleNormal": "Typisk årsløn",
  "payslip.insight.annualDetail": "Over 12 måneder: {gross} brutto → {deductions} i skat/fradrag → {net} udbetalt.",
  "payslip.insight.annualNormalDetail": "Baseret på din grundløn: ca. {gross}/år ({monthly}/md). Denne måneds engangsposter er ikke medregnet.",

  // Hvad ser SKAT?
  "payslip.section.hiddenBenefits": "Skjulte goder fra din arbejdsgiver",
  "payslip.benefits.intro": "Ud over din løn betaler din arbejdsgiver for goder du ikke ser på kontoen — men som arbejder for dig.",
  "payslip.benefits.pension": "Arbejdsgiver-pension",
  "payslip.benefits.health": "Sundhedsforsikring",
  "payslip.benefits.feriepenge": "Feriepenge (hensat)",
  "payslip.benefits.fritvalg": "Fritvalgskonto",
  "payslip.benefits.total": "Samlet årlig værdi",
  "payslip.benefits.healthHint": "Du har sundhedsforsikring via arbejdsgiver. Tjek om din private forsikring overlapper — du kan muligvis spare.",
  "payslip.section.skatView": "Hvad ser SKAT?",
  "payslip.skat.intro": "SKAT ser ikke din bruttoløn direkte. Pension og ATP trækkes fra først — derfor er SKATs tal lavere end du forventer.",
  "payslip.skat.step.brutto": "Bruttoløn",
  "payslip.skat.step.pension": "Pension (dit bidrag)",
  "payslip.skat.step.atp": "ATP",
  "payslip.skat.step.amGrundlag": "AM-grundlag",
  "payslip.skat.step.amGrundlagNote": "AM-bidrag (8%) beregnes af dette beløb",
  "payslip.skat.step.amBidrag": "AM-bidrag (8%)",
  "payslip.skat.step.aIndkomst": "A-indkomst",
  "payslip.skat.step.aIndkomstNote": "A-skat beregnes af dette beløb (minus personfradrag)",
  "payslip.skat.annual.title": "Årlig indberetning",
  "payslip.skat.annual.naive": "Brutto × 12 = {naive}",
  "payslip.skat.annual.real": "SKAT ser ca. {real}/år (AM-grundlag × 12)",
  "payslip.skat.annual.diff": "Forskel: {diff} — pension + ATP trækkes fra først",
  "payslip.skat.opsparing.title": "Opsparede beløb",
  "payslip.skat.opsparing.detail": "Fritvalg, ferietillæg o.lign. ({amount}/md) opspares på din lønseddel, men beskattes først når de udbetales. Derfor kan SKATs årstal være endnu lavere end AM-grundlag × 12.",

  // Pension & tax details
  "payslip.pension.employerContrib": "Dig: {employee} + Arbejdsgiver: {employer}",
  "payslip.tax.traekprocent": "Trækprocent",
  "payslip.tax.personfradrag": "Personfradrag",

  // Teaser card
  "payslip.teaser.title": "Dit delingskort er klar",
  "payslip.teaser.subtitle": "Del anonymt på Reddit — ingen persondata",

  // Verification screen
  "payslip.verify.title": "Vi fandt disse poster på din lønseddel",
  "payslip.verify.subtitle": "Ser tallene rigtige ud? Tryk på blyanten for at rette.",
  "payslip.verify.confirm": "Ser rigtigt ud",
  "payslip.verify.retry": "Upload igen",
  "payslip.verify.rawLines": "Rå linjer fra lønsedlen",

  // Salary comparison
  "payslip.salary.dstSource": "Baseret på Danmarks Statistik 2025",
  "payslip.salary.yourGross": "Din bruttoløn",
  "payslip.salary.difference": "Forskel",
  "payslip.salary.showAll": "Vis alle brancher",
  "payslip.salary.showFewer": "Vis færre",
  "payslip.salary.normalMonth": "typisk måned",

  // Accessibility
  "a11y.chartSummary": "Diagramoversigt",
  "a11y.sankeyTable": "Budgetflow",
  "a11y.historyDisposable": "Rådighedsbeløb over tid",
  "a11y.historyScore": "Sundhedsscore over tid",
  "a11y.partnerSplit": "Udgiftsfordeling mellem partnere",
  "a11y.bucketChart": "Budgetfordeling i kategorier",
  "a11y.skipToContent": "Spring til indhold",

  // Consent & dropzone accessibility
  "salary.consentLabel": "Hjælp andre danskere: Del din anonyme løndata (branche + region + lønniveau) så andre kan sammenligne. Vi gemmer aldrig dit navn eller CPR.",
  "payslip.dropzone.ariaLabel": "Upload lønseddel — træk og slip eller klik",
  "pengetjek.dropzone.ariaLabel": "Upload kontoudtog — træk og slip eller klik",

  // Homepage meta
  "meta.title": "Gratis budgetberegner — Beregn dit rådighedsbeløb | NemtBudget",

  // ── Pengetjekket ──
  "pengetjek.meta.title": "Pengetjekket — Se hvor dine penge forsvinder | NemtBudget.nu",
  "pengetjek.meta.description": "Upload dit kontoudtog og få overblik over dit forbrug på 30 sekunder. Gratis og anonymt.",
  "pengetjek.landing.headline": "Pengetjekket",
  "pengetjek.landing.subheadline": "Se hvor dine penge virkelig forsvinder hen — upload kontoudtog eller screenshot fra din bank-app",
  "pengetjek.dropzone": "Upload kontoudtog eller screenshot fra din bank-app",
  "pengetjek.pasteHint": "Du kan også indsætte et screenshot (Ctrl+V)",
  "pengetjek.acceptedFormats": "PDF, billede eller CSV-fil",
  "pengetjek.processing": "Analyserer dit kontoudtog...",
  "pengetjek.processingHint": "Vi kategoriserer alle transaktioner — det tager 10-20 sekunder",
  "pengetjek.step1": "Upload kontoudtog, screenshot eller CSV",
  "pengetjek.step2": "AI kategoriserer alle transaktioner",
  "pengetjek.step3": "Se hvor pengene forsvinder — ingen data gemmes",
  "pengetjek.privacy.summary": "CSV analyseres i din browser — intet sendes. Billede/PDF krypteres, analyseres af AI og slettes straks.",
  "pengetjek.journey.title": "Hvad sker der med dine data?",
  "pengetjek.journey.step1": "Din browser",
  "pengetjek.journey.step1Detail": "CSV? Alt sker her. Intet sendes.",
  "pengetjek.journey.step2": "AI kategoriserer",
  "pengetjek.journey.step2Detail": "Kun billede/PDF. Krypteret. Ingen ser det.",
  "pengetjek.journey.step3": "Slettet med det samme",
  "pengetjek.journey.step3Detail": "Kun kategorier sendes tilbage. Filen er væk.",
  "pengetjek.journey.honest": "CSV-filer forlader aldrig din browser. Billeder og PDF'er sendes krypteret til AI, analyseres på en lukket server uden menneskelig adgang, og slettes straks efter. Ingen login, ingen konto, ingen sporing.",
  "pengetjek.cta.retry": "Upload nyt kontoudtog",
  "pengetjek.crossPromo.title": "Gør budgettet endnu mere præcist",
  "pengetjek.crossPromo.desc": "Upload din lønseddel og få præcis indkomst, skatteoplysninger og pensionsdata med i budgettet.",
  "pengetjek.crossPromo.cta": "Upload lønseddel",
  "pengetjek.error.tooLarge": "Filen er for stor (max 10 MB)",
  "pengetjek.error.invalidType": "Filtypen understøttes ikke. Brug PDF, billede (JPG/PNG) eller CSV.",
  "pengetjek.error.csvParseFailed": "Kunne ikke læse CSV-filen. Tjek at det er et kontoudtog fra din bank.",
  "pengetjek.error.readFailed": "Kunne ikke læse kontoudtoget — prøv et tydeligere billede eller CSV.",
  "pengetjek.result.hero.spent": "Samlet forbrug",
  "pengetjek.result.hero.transactions": "transaktioner",
  "pengetjek.result.pengeslugere.title": "Dine pengeslugere",
  "pengetjek.result.pengeslugere.subtitle": "Her forsvinder dine penge",
  "pengetjek.result.subscriptions.title": "Abonnementer fundet",
  "pengetjek.result.subscriptions.total": "Du betaler {amount} kr/md i faste abonnementer",
  "pengetjek.result.categories.title": "Alle kategorier",
  "pengetjek.result.budget.title": "Budget vs. virkelighed",
  "pengetjek.result.cta": "Lav et budget baseret på dit forbrug",
  "pengetjek.result.truncated": "Kontoudtoget var for langt til at læse fuldt ud. Nogle transaktioner kan mangle.",
  "pengetjek.result.transactions.toggle": "Vis alle transaktioner",
  "pengetjek.result.transactions.unknownDate": "Ukendt dato",
  "pengetjek.currency": "kr",
  "pengetjek.perMonth": "md",
  "pengetjek.result.hero.income": "Indkomst i perioden: {amount} kr",
  "pengetjek.result.hero.aboveAverage": "Det er over gennemsnittet for en dansk husstand",
  "pengetjek.result.hero.belowAverage": "Det er under gennemsnittet — godt gået!",
  "pengetjek.result.hero.nearAverage": "Det er tæt på gennemsnittet for en dansk husstand",
  "pengetjek.result.pengeslugere.ofSpending": "af dit forbrug",
  "pengetjek.result.budget.budgeted": "Budget",
  "pengetjek.result.budget.actual": "Faktisk",
  "pengetjek.result.copied": "Kopieret!",
  "pengetjek.result.copyShare": "Kopiér overblik",
  "pengetjek.share.title": "Mit Pengetjek — NemtBudget.nu",
  "pengetjek.share.period": "Periode",
  "pengetjek.share.totalSpending": "Total forbrug",
  "pengetjek.share.transactionCount": "Antal transaktioner",
  "pengetjek.share.topCategories": "Top 5 kategorier",
  "pengetjek.share.subscriptions": "Abonnementer fundet",

  // OCR consent
  "ocr.consent": "Dit kontoudtog sendes til en AI-tjeneste (Anthropic) i USA for at afl\u00e6se transaktioner. Data opbevares i op til 7 dage og bruges ikke til tr\u00e6ning. Vil du forts\u00e6tte?",
  "ocr.consentPayslip": "Din l\u00f8nseddel sendes til en AI-tjeneste (Anthropic) i USA for at afl\u00e6se tal. Data opbevares i op til 7 dage og bruges ikke til tr\u00e6ning. Vil du forts\u00e6tte?",
  "salary.contributeAnonymous": "Bidrag anonymt til l\u00f8nstatistik",
  "cpr.redacting": "Sl\u00f8rer CPR og kontonumre...",
  "cpr.convertingPdf": "Konverterer PDF til billede...",
  "payslip.scanning": "AI l\u00e6ser din l\u00f8nseddel...",
  "pengetjek.scanning": "AI l\u00e6ser dit kontoudtog...",

  // Redaction review
  "redaction.title": "Tjek sl\u00f8ringen",
  "redaction.instruction": "Tjek at alle f\u00f8lsomme oplysninger er sl\u00f8ret. Tegn hen over det der mangler.",
  "redaction.autoFound": "{cpr} CPR-numre og {account} kontonumre fundet og sl\u00f8ret",
  "redaction.undo": "Fortryd",
  "redaction.clearMine": "Ryd mine",
  "redaction.regions": "sl\u00f8rede omr\u00e5der",
  "redaction.approve": "Godkend og forts\u00e6t",
  "redaction.cancel": "Annull\u00e9r",
  "redaction.hint": "Billedet forlader f\u00f8rst din enhed n\u00e5r du godkender. Sorte felter kan ikke fjernes.",

  // GDPR
  "gdpr.section": "Privatliv & data",
  "gdpr.exportData": "Eksportér mine data",
  "gdpr.exportDesc": "Download alle dine budgetdata som JSON-fil.",
  "gdpr.deleteAccount": "Slet min konto",
  "gdpr.deleteDesc": "Slet din konto og alle tilknyttede data permanent.",
  "gdpr.confirmDelete": "Er du sikker? Skriv 'SLET' for at bekræfte.",
  "gdpr.exporting": "Eksporterer...",
  "gdpr.deleting": "Sletter...",
  "gdpr.exportSuccess": "Dine data er downloadet.",
  "gdpr.deleteSuccess": "Din konto er slettet.",
  "gdpr.error": "Der opstod en fejl. Prøv igen.",
};
