// Norwegian texts — primary locale for kassen.no build (VITE_LOCALE=no)
// Complete set — no fallback to Danish needed
export const NO: Record<string, string> = {
  // Nav
  "nav.products": "Produkter",
  "nav.howItWorks": "Slik virker det",
  "nav.back": "Tilbake",
  "nav.budget": "Budsjett",
  "nav.coupleFinance": "Parøkonomi",
  "nav.childTax": "Barneskatteplanlegging",
  "nav.cockpit": "Cockpit",
  "nav.overview": "Oversikt",
  "nav.action": "Handling",
  "nav.future": "Fremtid",
  "nav.advanced": "Dybdegående",

  // Hero
  "hero.title": "Ta kontroll over",
  "hero.titleHighlight": "din privatøkonomi.",
  "hero.subtitle": "Finn skjulte utgifter, se hva du reelt har til overs og stå sterkt for fremtiden — gratis, privat og på 3 minutter.",
  "hero.cta": "Sjekk økonomien din gratis",
  "hero.imageAlt": "Personlig økonomi og budsjettoverikt",

  // Trust
  "trust.danish": "Bygget for norsk økonomi",
  "trust.time": "Utfylt på 3 minutter",
  "trust.private": "100% privat · Data lagres lokalt",

  // How it works
  "howItWorks.title": "Få det fulle oversiktet på 3 minutter",
  "howItWorks.subtitle": "Ingen regneark. Svar ja/nei — vi tar resten.",

  // Stats
  "stats.3min": "3 min",
  "stats.fillIn": "Å fylle ut",
  "stats.avgSaving": "Gj.sn. besparelse/md.",
  "stats.freePrivate": "Privat & gratis",

  // Features
  "feature.findHidden": "Finn skjulte utgifter",
  "feature.findHiddenDesc": "Vi gjennomgår strømming, forsikring og transport — og viser hva som spiser budsjettet ditt.",
  "feature.aiInsight": "AI-innsikt",
  "feature.aiInsightDesc": "Analyse av tallene dine og utgiftsmønstre.",
  "feature.compare": "Sammenlign med andre",
  "feature.compareDesc": "Se økonomien din sammenlignet med andre i ditt område og din inntektsgruppe.",
  "feature.bankReport": "Bankmøte-rapport",
  "feature.bankReportDesc": "Ta med en profesjonell rapport til banken din.",
  "feature.stressTest": "Stress-test økonomien din",
  "feature.stressTestDesc": "Hva skjer ved jobbtap, renteøkning eller inflasjon? Se din motstandsdyktighet.",

  // Testimonials
  "testimonials.title": "Hva andre sier",

  // Bottom CTA
  "bottomCta.title": "Klar til å komme i gang?",
  "bottomCta.subtitle": "Det tar bare 3 minutter — og koster ingenting.",
  "bottomCta.noLogin": "Ingen innlogging · Ingen data deles · Alt lagres lokalt",

  // Footer
  "footer.tagline": "Få et komplett oversikt over økonomien din. Gratis, privat og bygget for norske forhold.",
  "footer.product": "Produkt",
  "footer.budgetCalc": "Budsjettberegner",
  "footer.neighborComp": "Nabo-sammenligning",
  "footer.info": "Informasjon",
  "footer.privacy": "Personvern",
  "footer.terms": "Vilkår",
  "footer.contact": "Kontakt",
  "footer.about": "Om",
  "footer.private": "All data lagres lokalt i nettleseren din. Vi selger aldri dine data.",
  "footer.tools": "Verktøy",
  "footer.legal": "Juridisk",
  "footer.disclaimer": "Kassen er et budsjetteringsverktøy og gir ikke finansiell rådgivning. Snakk med banken din eller en rådgiver om konkrete økonomiske beslutninger.",
  "footer.based": "Beregnet på norske gjennomsnittstall 2026 · Data lagres lokalt",
  "footer.installApp": "Installer app",
  "footer.guides": "Guider & tips",

  // Onboarding — household
  "step.household.title": "Hvem er med i husstanden?",
  "step.household.subtitle": "Vi tilpasser alle estimater til situasjonen din.",
  "step.household.solo": "Bare meg",
  "step.household.soloSub": "Enslig husstand",
  "step.household.couple": "Vi er to",
  "step.household.coupleSub": "Par / samboende",

  // Onboarding — income
  "step.income.titleSolo": "Hva er inntekten din?",
  "step.income.titleCouple": "Hva er inntekten deres?",
  "step.income.subtitle": "Månedlig utbetalt etter skatt.",
  "step.income.myIncome": "Månedlig inntekt",
  "step.income.myIncomePar": "Din inntekt",
  "step.income.partnerIncome": "Partners inntekt",
  "step.income.otherIncome": "Øvrig inntekt",
  "step.income.placeholder": "F.eks. Bonus, dagpenger, barnetrygd",
  "step.income.amount": "Beløp",
  "step.income.addSource": "Legg til inntektskilde",
  "step.income.total": "Samlet inntekt",
  "step.income.tipSolo": "Gjennomsnittlig inntekt for enslige i Norge er ca. 32 000 kr./md. etter skatt.",
  "step.income.tipCouple": "Gjennomsnittlig husholdningsinntekt for par i Norge er ca. 62 000 kr./md. etter skatt.",
  "step.income.netTip": "Oppgi lønn etter skatt (netto — det du får utbetalt)",

  // Onboarding — housing
  "step.housing.title": "Boligsituasjon",
  "step.housing.subtitle": "Vi estimerer ut fra postnummer — juster fritt.",
  "step.housing.renter": "Leier",
  "step.housing.coop": "Borettslag",
  "step.housing.owner": "Selveier",
  "step.housing.postalCode": "Postnummer",
  "step.housing.postalPlaceholder": "F.eks. 0450",
  "step.housing.rent": "Månedlig husleie",
  "step.housing.coopFee": "Månedlige felleskostnader",
  "step.housing.coopLoan": "Borettslånet (avdrag + renter)",
  "step.housing.mortgage": "Månedlig boligytelse",
  "step.housing.propertyValue": "Estimert boligverdi",
  "step.housing.interestRate": "Rente på lån",

  // Onboarding — children
  "step.children.titleSolo": "Har du barn?",
  "step.children.titleCouple": "Har dere barn?",
  "step.children.subtitle": "Vi finner barnehagepriser automatisk.",
  "step.children.no": "Ingen barn",
  "step.children.yes": "Ja, vi har barn",
  "step.children.age": "Alder for hvert barn:",
  "step.children.child": "Barn",
  "step.children.years": "år",
  "step.children.add": "Legg til barn",
  "step.children.tip": "Barnehagepriser er makspris 2025: 3 315 kr./md. (Utdanningsdirektoratet). SFO ca. 2 000 kr./md. Din kommune kan avvike — juster i dashboardet.",
  "step.children.benefitTitle": "Barnetrygd (automatisk inkludert)",
  "step.children.benefitTotal": "Total barnetrygd",

  // Onboarding — expenses
  "step.expenses.title": "Faste utgifter",
  "step.expenses.subtitle": "Velg det som passer — vi fyller inn prisene.",
  "step.expenses.streaming": "Streaming & musikk",
  "step.expenses.transport": "Transport",
  "step.expenses.car": "Bil",
  "step.expenses.carLoan": "Billån / leasing",
  "step.expenses.fuel": "Bensin / lading",
  "step.expenses.carInsurance": "Bilforsikring",
  "step.expenses.carTax": "Årsavgift / trafikkforsikring",
  "step.expenses.carService": "Service / verksted",
  "step.expenses.insuranceUnion": "Forsikring & fagforbund",
  "step.expenses.insurance": "Forsikringer",
  "step.expenses.insuranceSub": "Innbo, ulykke, etc.",
  "step.expenses.union": "Fagforbund & dagpengekasse",
  "step.expenses.fitness": "Fitness / sport",
  "step.expenses.petsLoans": "Kjæledyr, lån & sparing",
  "step.expenses.pet": "Kjæledyr",
  "step.expenses.petSub": "Fôr, veterinær, forsikring",
  "step.expenses.loan": "Lån",
  "step.expenses.loanSub": "Studielån, forbrukslån, billån",
  "step.expenses.savings": "Sparing / investering",
  "step.expenses.savingsSub": "Fast sparing per måned",
  "step.expenses.custom": "Egne utgifter",
  "step.expenses.customPlaceholder": "F.eks. Kontaktlinser",
  "step.expenses.seeOverview": "Se oversikt",
  "step.expenses.utilities": "Telefon, internett & forsyning",
  "step.expenses.internet": "Internett",
  "step.expenses.mobileSolo": "Mobil",
  "step.expenses.mobilePar": "Mobil (2 pers.)",
  "step.expenses.electricity": "Strøm",
  "step.expenses.heating": "Varme & vann",
  "step.expenses.drLicens": "NRK-lisens",
  "step.expenses.included": "(inkludert)",
  "step.expenses.utilitiesNote": "Disse utgiftene medregnes automatisk i budsjettet ditt.",

  // Onboarding — review
  "step.review.title": "Gjennomgå & juster",
  "step.review.subtitle": "Rett alle tall til før du går videre.",
  "step.review.disposable": "Disponibel inntekt per måned",
  "step.review.good": "God økonomi",
  "step.review.tight": "Slank margin",
  "step.review.warning": "Under anbefaling",
  "step.review.income": "Inntekt",
  "step.review.expenses": "Utgifter",
  "step.review.share": "Andel",
  "step.review.variableExpenses": "Variable utgifter — juster til ditt forbruk",
  "step.review.food": "Mat & dagligvarer",
  "step.review.restaurant": "Restaurant & takeaway",
  "step.review.leisure": "Fritid & opplevelser",
  "step.review.clothing": "Klær & personlig pleie",
  "step.review.health": "Helse (lege, tannlege)",
  "step.review.fixedExpenses": "Faste utgifter",
  "step.review.seeDashboard": "Se fullt dashboard",

  // Dashboard
  "dash.charts": "Diagrammer",
  "dash.chartsShort": "Grafer",
  "dash.report": "Rapport",
  "dash.newCalc": "Ny beregning",
  "dash.resetShort": "Nullstill",
  "dash.shareResult": "Del resultatet ditt",
  "dash.close": "Lukk",
  "dash.editInfo": "Rediger opplysninger",
  "dash.logOut": "Logg ut",
  "dash.logIn": "Logg inn",
  "dash.cloudSync": "Logg inn for å lagre budsjettet ditt på tvers av enheter",
  "dash.subscriptions": "Abonnementer",

  // Sections
  "section.cockpit": "Cockpit",
  "section.cockpitSub": "Ditt økonomiske oversikt — alt på ett sted.",
  "section.overview": "Oversikt",
  "section.overviewSub": "Hvor går pengene dine? Se det hele i ett blikk.",
  "section.action": "Handling",
  "section.actionSub": "Konkrete spareforslag basert på tallene dine.",
  "section.future": "Fremtid",
  "section.futureSub": "Se fremover — formue, mål og tidslinje.",
  "section.advanced": "Dybdegående",
  "section.advancedSub": "Avanserte analyser og simuleringer.",

  // Tabs
  "tab.cockpit": "Cockpit",
  "tab.forward": "Fremover",
  "tab.whatIf": "Hva hvis",
  "tab.stressTest": "Stress-test",
  "tab.calendar": "Årshjul",
  "tab.optimize": "Optimering",
  "tab.compare": "Sammenlign",
  "tab.history": "Historikk",
  "tab.coupleSplit": "Parsplit",

  // Health
  "health.freedom": "Frihetstall",
  "health.freedomSub": "Reelt til overs per md.",
  "health.baseline": "Grunnlinje",
  "health.baselineSub": "Faste utgifter per md.",
  "health.buffer": "Buffer",
  "health.bufferSub": "md. uten inntekt",

  // Frequencies
  "freq.monthly": "Månedlig",
  "freq.quarterly": "Kvartalsvis",
  "freq.biannual": "Halvårlig",
  "freq.annual": "Årlig",
  "freq.monthlyShort": "Md.",
  "freq.quarterShort": "Kvartal",
  "freq.halfYearShort": "Halvår",
  "freq.yearShort": "År",

  // Stress test
  "stress.resilience": "Motstandsdyktighet",
  "stress.resilienceGood": "Økonomien din kan motstå de fleste økonomiske sjokk. Sterk posisjon.",
  "stress.resilienceOk": "Økonomien din er sårbar for visse scenarioer. Vurder å styrke bufferen din.",
  "stress.resilienceBad": "Økonomien din er skjør. Selv små endringer kan skape problemer. Prioriter sparing.",
  "stress.inflation": "Inflasjon",
  "stress.inflationDesc": "Hva skjer hvis prisene stiger? Variable utgifter rammes hardest.",
  "stress.moderate": "Moderat",
  "stress.severe": "Alvorlig",
  "stress.extreme": "Ekstrem",
  "stress.newDisposable": "Nytt disponibelt beløp",
  "stress.impact": "Effekt",
  "stress.rateHike": "Renteøkning",
  "stress.rateHikeDesc": "Hva skjer hvis renten stiger? Påvirker boliglånet ditt direkte.",
  "stress.mortgageUp": "Boliglån øker",
  "stress.jobLoss": "Jobbtap",
  "stress.jobLossDesc": "Hva skjer hvis inntekten din faller? Vi beregner med og uten dagpenger.",
  "stress.withoutHelp": "Uten dagpenger",
  "stress.withDagpenge": "Med dagpenger",
  "stress.survivalTime": "Overlevelsestid",
  "stress.months": "måneder",
  "stress.monthsShort": "md.",
  "stress.withSavings": "med nåværende sparing",
  "stress.worstCase": "Worst case: Alt på én gang",
  "stress.worstCaseDesc": "Inflasjon + renteøkning + inntektsfall. Budsjettet ditt under maksimalt press.",
  "stress.disclaimer": "Stress-testen er et estimat. Kontakt banken din for nøyaktig beregning.",

  // Årshjul
  "wheel.annual": "Årlige utgifter",
  "wheel.annualSub": "Store utgifter du bør forberede deg på i løpet av året",
  "wheel.monthlyOverview": "Månedsoversikt",
  "wheel.upcoming": "Kommende utgifter",
  "wheel.fullYear": "Hele året",
  "wheel.now": "Nå",
  "wheel.carInsurance": "Bilforsikring",
  "wheel.carTax": "Årsavgift",
  "wheel.carService": "Bilservice",
  "wheel.propertyTax": "Eiendomsskatt",
  "wheel.insuranceRenewal": "Forsikring (fornyelse)",
  "wheel.christmas": "Jul & gaver",
  "wheel.summerVacation": "Sommerferie",
  "wheel.taxSettlement": "Restskatt / overskudd",
  "wheel.backToSchool": "Skolestart",
  "wheel.birthdays": "Fødselsdager",
  "wheel.disclaimer": "Beløpene er estimater basert på norske gjennomsnitt.",

  // Nudges
  "nudge.savingsAbove": "Spareraten din ({pct}) er over gjennomsnittet ({avg}) for lignende husholdninger 💪",
  "nudge.savingsBelow": "De fleste lignende husholdninger sparer minst {avg} av inntekten",
  "nudge.streaming": "Du har {count} strømmetjenester — 67% av norske husholdninger har maks 2",
  "nudge.foodAbove": "Matbudsjettet ditt er {pct}% over gjennomsnittet for lignende husholdninger",
  "nudge.foodBelow": "Matbudsjettet ditt er under gjennomsnittet — godt jobba! 🥗",
  "nudge.topPercentile": "Disponibelt beløp er i topp {pct}% blant lignende husholdninger",
  "nudge.housingHigh": "Boligutgiften utgjør {pct}% av inntekten — eksperter anbefaler maks 33%",
  "nudge.healthTop": "Helsescoren din er i topp 25 — du er bedre stilt enn de fleste",

  // Scenarios
  "scenario.buyHome.title": "Kjøp bolig",
  "scenario.buyHome.desc": "Hva skjer hvis du skifter fra leie til selveier?",
  "scenario.haveChild.title": "Få barn",
  "scenario.haveChild.desc": "Hvordan påvirker et barn økonomien din?",
  "scenario.newJob.title": "Bytt jobb",
  "scenario.newJob.desc": "Simuler en ny lønn og se effekten.",
  "scenario.intro": "Slå på scenarioer og se hvordan de påvirker økonomien din i sanntid.",
  "scenario.monthlyImpact": "Månedlig effekt",
  "scenario.newDisposable": "Nytt disponibelt beløp",
  "scenario.mortgagePayment": "Månedlig boligytelse",
  "scenario.salaryChange": "Lønnsendring",
  "scenario.before": "Før vs. etter",
  "scenario.now": "Nå",
  "scenario.label": "Scenario",
  "scenario.disposablePerMonth": "disponibelt pr. md.",
  "scenario.scoreLabel": "Score",

  // Page meta
  "page.lastUpdated": "Sist oppdatert",
  "page.updatedDate": "mars 2026",

  // Actions
  "action.goToDashboard": "Gå til budsjettet ditt",

  // Cookie
  "cookie.text": "Vi bruker informasjonskapsler for å lagre preferansene dine lokalt. Ingen data sendes til tredjeparter.",
  "cookie.readMore": "Les mer",
  "cookie.accept": "Aksepter",
  "cookie.decline": "Avvis",

  // Generic
  "continue": "Fortsett",
  "currency": "kr.",
  "perMonth": "kr./md.",
  "perYear": "kr./år",
  "perHalfYear": "kr./halvår",

  // Report
  "report.title": "Finansrapport",
  "report.solo": "Solobudsjett",
  "report.couple": "Parbudsjett",
  "report.postalCode": "Postnr.",
  "report.back": "Tilbake",
  "report.share": "Del",
  "report.print": "Print / PDF",
  "report.health": "Økonomisk helse",
  "report.buffer": "Buffer",
  "report.monthlyIncome": "Månedlig inntekt",
  "report.totalExpenses": "Samlede utgifter",
  "report.savingsRate": "Sparerate",
  "report.housingRatio": "Bolig-ratio",
  "report.expenseBreakdown": "Utgiftsspesifikasjon",
  "report.fixedExpenses": "Faste utgifter",
  "report.variableExpenses": "Variable utgifter",
  "report.incomeDist": "Inntektsfordeling",
  "report.you": "Deg",
  "report.partner": "Partner",
  "report.generated": "Generert {date} · Beregnet på norske gjennomsnittstall 2026",
  "report.disclaimer": "Budsjetteringsverktøy — ikke finansiell rådgivning",
  "report.bufferMonths": "{n} md.",

  // Cockpit
  "cockpit.income": "Inntekt",
  "cockpit.partner": "Partner",
  "cockpit.expenses": "Utgifter",
  "cockpit.disposable": "Til rådighet",
  "cockpit.total": "I alt",
  "cockpit.distribution": "Pengefordeling",
  "cockpit.savingsPotential": "Sparepotensial",
  "cockpit.seePlan": "Se plan ↓",
  "cockpit.bucket.drift": "Drift",
  "cockpit.bucket.driftTip": "Faste utgifter: bolig, mat, transport, forsikring",
  "cockpit.bucket.frihed": "Frihet",
  "cockpit.bucket.frihedTip": "Til overs etter faste utgifter — ditt disponibelt beløp",
  "cockpit.bucket.fremtid": "Fremtid",
  "cockpit.bucket.fremtidTip": "Sparing og pensjonsinnskudd",
  "cockpit.bucket.risiko": "Risiko",
  "cockpit.bucket.risikoTip": "Gjeld og variable utgifter",
  "cockpit.alert.overBudget": "Du bruker {amount} kr. mer enn du tjener",
  "cockpit.alert.housingHigh": "Bolig utgjør {pct}% av inntekten — over anbefalte 35%",
  "cockpit.alert.streamingMany": "{count} strømmetjenester — gjennomsnittsnordmann har 2",
  "cockpit.alert.savingsStrong": "Sterk sparerate på {pct}%",
  "cockpit.live.electricity": "Strøm: {price} kr/kWh",
  "cockpit.live.rate": "Rente: {rate}%",
  "cockpit.live.income": "Gj.sn. inntekt: {amount} kr.",

  // Categories
  "cat.Bolig": "Bolig",
  "cat.Forsyning": "Forsyning",
  "cat.Transport": "Transport",
  "cat.Abonnementer": "Abonnementer",
  "cat.Forsikring": "Forsikring",
  "cat.Fagforening": "Fagforening",
  "cat.Børn": "Barn",
  "cat.Kæledyr": "Kjæledyr",
  "cat.Lån": "Lån",
  "cat.Fitness": "Fitness",
  "cat.Opsparing": "Sparing",
  "cat.Mad & dagligvarer": "Mat & dagligvarer",
  "cat.Fritid": "Fritid",
  "cat.Tøj": "Klær",
  "cat.Sundhed": "Helse",
  "cat.Restaurant": "Restaurant",
  "cat.Andet": "Annet",

  // Sankey / overview
  "sankey.incomeDistribution": "Inntekt fordelt på utgifter",
  "sankey.leftOver": "Til overs",
  "sankey.salary": "Lønn",
  "sankey.partner": "Partner",
  "sankey.otherIncome": "Øvrig",
  "sankey.income": "Inntekt",
  "sankey.expenses": "Utgifter",

  // Dashboard misc
  "dash.startOver": "Start på nytt",
  "dash.reset": "Nullstill",
  "dash.disclaimer": "Kassen er et budsjetteringsverktøy — ikke finansiell rådgivning.",
  "dash.aiTitle": "La AI finne dine besparelser",
  "dash.aiSubtitle": "Guidet gjennomgang — du bestemmer hva du vil gjøre",
  "dash.useDefaults": "Bruk standardtall og se mitt resultat →",
  "dash.hideDetails": "Skjul detaljer",
  "dash.showCarDetails": "Fordel utgifter på bil",

  // Neighbor comparison
  "neighbor.comparedWith": "Sammenlignet med din inntektsgruppe",
  "neighbor.pair": "par",
  "neighbor.single": "enslig",
  "neighbor.housingCost": "Boligutgift:",
  "neighbor.categoryByCategory": "Kategori for kategori",
  "neighbor.onPar": "På nivå",
  "neighbor.savingsIfLowered": "Hvis du senker til typisk nivå, sparer du",
  "neighbor.food": "Mat & dagligvarer",
  "neighbor.restaurant": "Restaurant & takeaway",
  "neighbor.transportCar": "Transport (bil)",
  "neighbor.transport": "Transport",
  "neighbor.streaming": "Strømming & abonnementer",
  "neighbor.leisure": "Fritid & opplevelser",

  // Optimization
  "optimize.totalPotential": "Samlet potensial",
  "optimize.lookingGood": "Økonomien din ser sterk ut",
  "optimize.noSavings": "Vi fant ingen åpenbare besparelser — bra jobba!",
  "optimize.doItNow": "Gjør det nå — ",
  "optimize.dstBenchmark": "SSB-referanse",
  "optimize.dkAverage": "NO-gjennomsnitt",
  "optimize.yourDisposable": "Ditt disponibelt beløp",

  // Couple split
  "couple.incomeBasedSplit": "Inntektsfordelt",
  "couple.partnerIncome": "Partners inntekt",
  "couple.partnerPays": "Partner betaler",
  "couple.expenses": "Utgifter",
  "couple.remaining": "Rest",

  // Profile edit
  "profile.householdIncome": "Husstand & Inntekt",
  "profile.partnerIncomeNet": "Partners inntekt (netto)",
  "profile.housing": "Bolig",
  "profile.housingType": "Boligtype",
  "profile.food": "Mat & dagligvarer",
  "profile.leisure": "Fritid & opplevelser",
  "profile.clothing": "Klær & sko",

  // Forward view
  "forward.propertyValue": "Boligverdi",
  "forward.propertyEstimate": "Boligverdi er et estimat — juster i profilen din",
  "forward.emergencyBuffer": "Nødbuffer (3 mnd.)",
  "forward.savingsRate": "Sparerate",

  // Charts
  "charts.disposable": "Disponibelt beløp",
  "charts.average": "Gjennomsnitt",
  "charts.lowest": "Laveste",
  "charts.highest": "Høyeste",
  "charts.monthNames": "Jan,Feb,Mar,Apr,Mai,Jun,Jul,Aug,Sep,Okt,Nov,Des",

  // AI chat
  "ai.askAbout": "Spør AI om økonomien din",
  "ai.askShort": "Spør AI",
  "ai.limitReached": "Månedlig grense nådd. Nullstilles automatisk neste måned.",

  // Guided saving
  "guided.title": "Guidet sparesession",
  "guided.found": "Funnet",
  "guided.totalFreed": "Totalt frigjort",

  // Share card
  "share.economyCheck": "Økonomi-sjekk",
  "share.freedomNumber": "Frihetstall",
  "share.savingsRate": "Sparerate",
  "share.buffer": "Buffer",
  "share.footer": "Beregnet med Kassen · 2026",

  // Subscriptions
  "subs.warning": "Over 2 000 kr/mnd. i abonnementer — vurder å kutte ned",
  "subs.foundInBudget": "Funnet i budsjettet ditt",

  // Profile edit (extra)
  "profile.title": "Rediger opplysningene dine",
  "profile.saved": "Endringer lagret",
  "profile.savedDesc": "Budsjettet ditt er oppdatert.",
  "profile.householdType": "Husstandstype",
  "profile.solo": "Enslig",
  "profile.couple": "Par",
  "profile.yourIncome": "Din inntekt (netto)",
  "profile.postalCode": "Postnummer",
  "profile.rentPayment": "Husleie/betaling",
  "profile.monthlyPayment": "Månedlig boligbetaling",
  "profile.interestRate": "Rente (%)",
  "profile.spending": "Forbruk",
  "profile.restaurantTakeaway": "Restaurant & takeaway",
  "profile.healthMedicine": "Helse & medisin",
  "profile.transport": "Transport",
  "profile.hasCar": "Har bil",
  "profile.carLoan": "Billån (mnd.)",
  "profile.carFuel": "Bensin/lading (mnd.)",
  "profile.carInsurance": "Bilforsikring (mnd.)",
  "profile.subscriptions": "Abonnementer",
  "profile.loansAndSavings": "Lån & Sparing",
  "profile.hasLoan": "Har lån",
  "profile.loanPayment": "Lånebetaling (mnd.)",
  "profile.savesUp": "Sparer",
  "profile.savingsMonthly": "Sparing (mnd.)",
  "profile.insurances": "Forsikringer",
  "profile.insuranceMonthly": "Forsikring (mnd.)",
  "profile.saveChanges": "Lagre endringer",

  // Subscriptions (extra)
  "subs.title": "Abonnementer",
  "subs.addedManually": "Lagt til manuelt",
  "subs.namePlaceholder": "Navn (f.eks. ChatGPT Plus)",
  "subs.pricePlaceholder": "Pris per måned",
  "subs.add": "Legg til",
  "subs.cancel": "Avbryt",
  "subs.addSubscription": "Legg til abonnement",

  // GuidedSaving (extra)
  "guided.goalReached": "Du nådde målet ditt!",
  "guided.goalReachedDesc": "Du frigjorde {amount} kr/mnd. totalt.",
  "guided.skipped": "Hoppet over: {label}",
  "guided.whatIsYourGoal": "Hva er målet ditt?",
  "guided.goalDesc": "Jeg gjennomgår budsjettet ditt og finner de enkleste besparelsene — du bestemmer hva du vil gjøre.",
  "guided.currentDisposable": "Ditt nåværende disponibelt beløp er {amount} kr/mnd.",
  "guided.skip": "Hopp over",
  "guided.apply": "Bruk",
  "guided.goalReachedTitle": "Mål nådd!",
  "guided.sessionDone": "Sesjonen er ferdig",
  "guided.reviewedAll": "Du har gjennomgått alle forslag.",
  "guided.acceptedChanges": "Godkjente endringer",
  "guided.noChanges": "Ingen endringer valgt.",
  "guided.seeUpdated": "Se oppdatert budsjett",

  // Forward view (extra)
  "forward.wealthProjection": "Formue-projeksjon",
  "forward.years": "år",
  "forward.estimatedWealth": "Estimert formue (bolig)",
  "forward.estDebt": "Est. gjeld (~70%)",
  "forward.netWorth": "Net worth",
  "forward.goalsProgress": "Mål & fremgang",
  "forward.rateShockSim": "Rentesjokk-simulator",
  "forward.vulnerableEconomy": "Sårbar økonomi",
  "forward.refinanceAdvice": "Refinansiering kan redusere eksponeringen deres.",
  "forward.timeline": "Tidslinje — neste 10 år",
  "forward.noEvents": "Ingen store hendelser funnet basert på profilen deres.",

  // ParSplit (extra)
  "couple.desc": "Se hvordan de felles utgiftene kan fordeles rettferdig.",
  "couple.yourIncome": "Din inntekt",
  "couple.expenseDistribution": "Utgiftsfordeling",
  "couple.youPay": "Du betaler",
  "couple.evenSplit": "Jevn fordeling — begge har omtrent like mye til rådighet",
  "couple.youHaveMore": "Du har {amount} kr mer til rådighet enn partneren din",
  "couple.partnerHasMore": "Partneren din har {amount} kr mer til rådighet enn deg",
  "couple.visualization": "Visualisering",
  "couple.tip": "Med inntektsfordelt modell betaler dere relativt til lønnen — prøv den!",

  // AI chat (extra)
  "ai.personalAdvisor": "Din personlige rådgiver",
  "ai.analyzing": "AI analyserer økonomien din...",
  "ai.usedFreeAnswers": "Du har brukt dine 5 gratis AI-svar",
  "ai.createAccount": "Opprett konto — følg med på premium",
  "ai.answersLeft": "AI-svar igjen denne måneden",
  "ai.placeholder": "Still et spørsmål om økonomien din...",

  // History
  "history.noHistory": "Ingen historikk ennå",
  "history.noHistoryDesc": "Historikken din vises her når du har brukt Kassen i mer enn en måned. Hver gang du oppdaterer budsjettet, lagrer vi et øyeblikksbilde — slik at du kan se utviklingen over tid.",
  "history.oneSnapshot": "1 øyeblikksbilde lagret · Oppdater budsjettet igjen for å se en graf",
  "history.disposableSinceStart": "Disponibelt beløp siden start",
  "history.healthSinceStart": "Helsescore siden start",
  "history.disposableOverTime": "Disponibelt beløp over tid",
  "history.healthOverTime": "Helsescore over tid",
  "history.calculationsSaved": "{count} beregninger lagret",
  "history.first": "Første",
  "history.latest": "Siste",

  // Editable amount
  "edit.clickToEdit": "Klikk for å redigere",
  "edit.cancel": "Avbryt",
  "edit.save": "Lagre",

  // Onboarding UI
  "onboarding.leftOver": "Til overs",
  "onboarding.seeOverview": "Se oversikt",
  "onboarding.stepOf": "Steg {idx} av {total}",

  // Optimize (extra)
  "optimize.opensExternal": "Åpner ekstern side",
  "optimize.savePerMonth": "Spar {amount} kr/mnd.",
};
