// English texts — optional runtime language switch on any build
export const EN: Record<string, string> = {
  // Nav
  "nav.products": "Products",
  "nav.howItWorks": "How it works",
  "nav.back": "Back",
  "nav.budget": "Budget",
  "nav.coupleFinance": "Couple finance",
  "nav.childTax": "Child tax",
  "nav.cockpit": "Cockpit",
  "nav.overview": "Overview",
  "nav.action": "Action",
  "nav.future": "Future",
  "nav.advanced": "In-depth",

  // Hero
  "hero.title": "You have less than you think",
  "hero.titleHighlight": "left each month.",
  "hero.subtitle": "Most people overestimate their disposable income by 3,000-5,000 kr. Find your hidden expenses in 3 minutes — free and private.",
  "hero.cta": "Calculate your disposable income",
  "hero.imageAlt": "Personal finance and budget overview",
  "hero.socialProof": "1,200+ Danes have already checked their budget",

  // Trust
  "trust.danish": "Built for Danish finance",
  "trust.time": "Done in 3 minutes",
  "trust.private": "100% private · Data stored locally",

  // How it works
  "howItWorks.title": "Get the full picture in 3 minutes",
  "howItWorks.subtitle": "No spreadsheets. Answer yes/no — we handle the rest.",

  // Stats
  "stats.3min": "3 min",
  "stats.fillIn": "To complete",
  "stats.avgSaving": "Avg. savings/mo.",
  "stats.freePrivate": "Private & free",

  // Features
  "feature.findHidden": "Find hidden expenses",
  "feature.findHiddenDesc": "We review streaming, insurance and transport — and show what's eating your budget.",
  "feature.aiInsight": "AI insights",
  "feature.aiInsightDesc": "Analysis of your numbers and spending patterns.",
  "feature.compare": "Compare with others",
  "feature.compareDesc": "See your finances compared to others in your area and income bracket.",
  "feature.bankReport": "Bank meeting report",
  "feature.bankReportDesc": "Take a professional report to your bank advisor.",
  "feature.stressTest": "Stress-test your finances",
  "feature.stressTestDesc": "What happens with job loss, rate hikes or inflation? See your resilience.",
  "feature.savings": "Savings planner",
  "feature.savingsDesc": "See when you'll reach your goals with your current savings rate.",

  // Testimonials
  "testimonials.title": "What others say",

  // Bottom CTA
  "bottomCta.title": "3 minutes. 0 kroner. Full overview.",
  "bottomCta.subtitle": "Most people find at least one expense they didn't know they were paying.",
  "bottomCta.noLogin": "No login · No data shared · Everything stored locally",

  // Footer
  "footer.tagline": "Get a complete overview of your finances. Free, private and built for Danish conditions.",
  "footer.product": "Product",
  "footer.budgetCalc": "Budget calculator",
  "footer.neighborComp": "Neighbor comparison",
  "footer.info": "Information",
  "footer.privacy": "Privacy policy",
  "footer.terms": "Terms & conditions",
  "footer.contact": "Contact",
  "footer.about": "About",
  "footer.private": "100% private · Data stored locally",
  "footer.tools": "Tools",
  "footer.legal": "Legal",
  "footer.disclaimer": "NemtBudget is a budgeting tool and does not provide financial advice. Talk to your bank or an advisor about specific financial decisions.",
  "footer.based": "Based on Danish averages 2026 · Data stored locally",
  "footer.installApp": "Install app",
  "footer.guides": "Guides & tips",

  // Onboarding — household
  "step.household.title": "Who is in the household?",
  "step.household.subtitle": "We tailor all estimates to your situation.",
  "step.household.solo": "Just me",
  "step.household.soloSub": "Single household",
  "step.household.couple": "Two of us",
  "step.household.coupleSub": "Couple / cohabiting",

  // Onboarding — income
  "step.income.titleSolo": "What is your income?",
  "step.income.titleCouple": "What is your combined income?",
  "step.income.subtitle": "Monthly after-tax payout.",
  "step.income.myIncome": "Monthly income",
  "step.income.myIncomePar": "Your income",
  "step.income.partnerIncome": "Partner's income",
  "step.income.otherIncome": "Other income",
  "step.income.placeholder": "E.g. Bonus, grants, child benefits",
  "step.income.amount": "Amount",
  "step.income.addSource": "Add income source",
  "step.income.total": "Total income",
  "step.income.tipSolo": "Average income for singles in Denmark is approx. 27,000 DKK/mo. after tax.",
  "step.income.tipCouple": "Average household income for couples in Denmark is approx. 52,000 DKK/mo. after tax.",
  "step.income.netTip": "Enter salary after tax (net — what you receive)",
  "step.income.payslip.title": "Have your payslip?",
  "step.income.payslip.hint": "Upload a photo or PDF — we'll read the amount automatically",
  "step.income.payslip.analyzing": "Analyzing payslip...",
  "step.income.payslip.success": "Payslip read!",
  "step.income.payslip.applied": "Income and deductions have been filled in automatically.",
  "step.income.payslip.retry": "Try again",
  "step.income.payslip.clear": "Remove",
  "step.income.payslip.divider": "or enter manually",

  // Onboarding — housing
  "step.housing.title": "Housing situation",
  "step.housing.subtitle": "We estimate based on postal code — adjust freely.",
  "step.housing.renter": "Renter",
  "step.housing.coop": "Co-op",
  "step.housing.owner": "Owner",
  "step.housing.postalCode": "Postal code",
  "step.housing.postalPlaceholder": "E.g. 2100",
  "step.housing.unknownPostal": "Unknown postal code — estimates unavailable",
  "step.housing.rent": "Monthly rent",
  "step.housing.coopFee": "Monthly housing fee",
  "step.housing.coopLoan": "Co-op loan (payments + interest)",
  "step.housing.mortgage": "Monthly mortgage payment",
  "step.housing.propertyValue": "Estimated property value",
  "step.housing.interestRate": "Loan interest rate",

  // Onboarding — children
  "step.children.titleSolo": "Do you have children?",
  "step.children.titleCouple": "Do you have children?",
  "step.children.subtitle": "We find childcare prices automatically.",
  "step.children.no": "No children",
  "step.children.yes": "Yes, we have children",
  "step.children.age": "Age of each child:",
  "step.children.child": "Child",
  "step.children.years": "years",
  "step.children.add": "Add child",
  "step.children.tip": "Childcare prices are national averages 2026 (source: KL/municipalities). Nursery approx. 4,500 DKK, kindergarten approx. 2,600 DKK, after-school care approx. 2,300 DKK/mo. Your municipality may differ — adjust in the dashboard.",
  "step.children.benefitTitle": "Child benefits (automatically included)",
  "step.children.benefitTotal": "Total child benefits",

  // Onboarding — expenses
  "step.expenses.title": "Fixed expenses",
  "step.expenses.subtitle": "Select what applies — we pre-fill the prices.",
  "step.expenses.streaming": "Streaming & music",
  "step.expenses.transport": "Transport",
  "step.expenses.car": "Car",
  "step.expenses.carLoan": "Car loan / leasing",
  "step.expenses.fuel": "Fuel / charging",
  "step.expenses.carInsurance": "Car insurance",
  "step.expenses.carTax": "Vehicle tax / green owner tax",
  "step.expenses.carService": "Service / workshop",
  "step.expenses.insuranceUnion": "Insurance & union",
  "step.expenses.insurance": "Insurance",
  "step.expenses.insuranceSub": "Contents, accident, etc.",
  "step.expenses.union": "Union & unemployment fund",
  "step.expenses.fitness": "Fitness / sports",
  "step.expenses.petsLoans": "Pets, loans & savings",
  "step.expenses.pet": "Pet",
  "step.expenses.petSub": "Food, vet, insurance",
  "step.expenses.loan": "Loan",
  "step.expenses.loanSub": "Student loan, consumer loan",
  "step.expenses.savings": "Savings / investment",
  "step.expenses.savingsSub": "Monthly fixed savings",
  "step.everyday.title": "Everyday expenses",
  "step.everyday.subtitle": "Adjust your daily expenses — we've filled in averages",
  "step.everyday.smartDefaults": "We've estimated your everyday budget — adjust what doesn't fit.",
  "step.fixed.title": "Fixed expenses",
  "step.fixed.subtitle": "Subscriptions, insurance and other recurring costs.",
  "step.fixed.smartDefaults": "Fixed expenses — we've filled in typical Danish prices.",
  "step.expenses.custom": "Custom expenses",
  "step.expenses.customPlaceholder": "E.g. Contact lenses",
  "step.expenses.seeOverview": "See overview",
  "step.expenses.utilities": "Phone, internet & utilities",
  "step.expenses.internet": "Internet",
  "step.expenses.mobileSolo": "Mobile",
  "step.expenses.mobilePar": "Mobile (2 pers.)",
  "step.expenses.electricity": "Electricity",
  "step.expenses.heating": "Heating & water",
  "step.expenses.drLicens": "DR (media license)",
  "step.expenses.included": "(included)",
  "step.expenses.utilitiesNote": "These expenses are automatically included in your budget.",

  // Onboarding — review
  "step.review.title": "Review & adjust",
  "step.review.subtitle": "Adjust all numbers before continuing.",
  "step.review.disposable": "Disposable income per month",
  "step.review.good": "Good finances",
  "step.review.tight": "Tight margin",
  "step.review.warning": "Below recommendation",
  "step.review.income": "Income",
  "step.review.expenses": "Expenses",
  "step.review.share": "Share",
  "step.review.variableExpenses": "Variable expenses — adjust to your spending",
  "step.review.food": "Food & groceries",
  "step.review.restaurant": "Restaurant & takeaway",
  "step.review.leisure": "Leisure & experiences",
  "step.review.clothing": "Clothing & personal care",
  "step.review.health": "Health (doctor, dentist)",
  "step.review.fixedExpenses": "Fixed expenses",
  "step.review.seeDashboard": "See full dashboard",
  "step.review.zeroIncomeWarning": "Your income is set to 0. Is that correct?",

  // Dashboard
  "dash.title": "Your budget — NemtBudget",
  "dash.charts": "Charts",
  "dash.chartsShort": "Charts",
  "dash.report": "Report",
  "dash.newCalc": "New calculation",
  "dash.resetShort": "Reset",
  "dash.shareResult": "Share your result",
  "dash.close": "Close",
  "dash.editInfo": "Edit info",
  "dash.logOut": "Log out",
  "dash.logIn": "Log in",
  "dash.cloudSync": "Log in to save your budget across devices",
  "dash.subscriptions": "Subscriptions",

  // Sections
  "section.cockpit": "Overview",
  "section.cockpitSub": "Your financial overview — everything in one place.",
  "section.overview": "Overview",
  "section.overviewSub": "Where does your money go? See it all at a glance.",
  "section.action": "Action",
  "section.actionSub": "Concrete savings suggestions based on your numbers.",
  "section.future": "Future",
  "section.futureSub": "Look ahead — wealth, goals and timeline.",
  "section.advanced": "In-depth",
  "section.advancedSub": "Advanced analyses and simulations.",

  // Tabs
  "tab.cockpit": "Cockpit",
  "tab.forward": "Forward",
  "tab.whatIf": "What if",
  "tab.stressTest": "Stress test",
  "tab.calendar": "Calendar",
  "tab.optimize": "Optimize",
  "tab.compare": "Compare",
  "tab.history": "History",
  "tab.coupleSplit": "Couple split",

  // Health
  "health.freedom": "Freedom number",
  "health.freedomSub": "Actually left per month",
  "health.baseline": "Baseline",
  "health.baselineSub": "Fixed expenses per month",
  "health.buffer": "Buffer",
  "health.bufferSub": "mo. without income",

  // Frequencies
  "freq.monthly": "Monthly",
  "freq.quarterly": "Quarterly",
  "freq.biannual": "Biannual",
  "freq.annual": "Annual",
  "freq.monthlyShort": "Mo.",
  "freq.quarterShort": "Quarter",
  "freq.halfYearShort": "Half year",
  "freq.yearShort": "Year",

  // Stress test
  "stress.resilience": "Resilience score",
  "stress.resilienceGood": "Your finances can withstand most economic shocks. Strong position.",
  "stress.resilienceOk": "Your finances are vulnerable to certain scenarios. Consider strengthening your buffer.",
  "stress.resilienceBad": "Your finances are fragile. Even small changes can cause problems. Prioritize savings.",
  "stress.inflation": "Inflation",
  "stress.inflationDesc": "What happens if prices rise? Variable expenses are hit hardest.",
  "stress.moderate": "Moderate",
  "stress.severe": "Severe",
  "stress.extreme": "Extreme",
  "stress.newDisposable": "New disposable",
  "stress.impact": "Impact",
  "stress.rateHike": "Rate hike",
  "stress.rateHikeDesc": "What happens if interest rates rise? Directly affects your mortgage.",
  "stress.mortgageUp": "Mortgage increase",
  "stress.jobLoss": "Job loss",
  "stress.jobLossDesc": "What happens if your income drops? We calculate with and without unemployment benefits.",
  "stress.withoutHelp": "Without benefits",
  "stress.withDagpenge": "With benefits",
  "stress.personalDagpenge": "Your personal benefit rate",
  "stress.survivalTime": "Survival time",
  "stress.months": "months",
  "stress.monthsShort": "mo.",
  "stress.withSavings": "with current savings",
  "stress.worstCase": "Worst case: Everything at once",
  "stress.worstCaseDesc": "Inflation + rate hike + income drop. Your budget under maximum pressure.",
  "stress.disclaimer": "The stress test is an estimate. Contact your bank for exact calculations.",

  // Årshjul
  "wheel.annual": "Annual expenses",
  "wheel.annualSub": "Large expenses you need to prepare for throughout the year",
  "wheel.monthlyOverview": "Monthly overview",
  "wheel.upcoming": "Upcoming expenses",
  "wheel.fullYear": "Full year",
  "wheel.now": "Now",
  "wheel.carInsurance": "Car insurance",
  "wheel.carTax": "Vehicle tax",
  "wheel.carService": "Car service",
  "wheel.propertyTax": "Property tax",
  "wheel.insuranceRenewal": "Insurance (renewal)",
  "wheel.christmas": "Christmas & gifts",
  "wheel.summerVacation": "Summer vacation",
  "wheel.taxSettlement": "Tax settlement",
  "wheel.backToSchool": "Back to school",
  "wheel.birthdays": "Birthdays",
  "wheel.disclaimer": "Amounts are estimates based on Danish averages.",

  // Nudges
  "nudge.savingsAbove": "Your savings rate ({pct}) is above average ({avg}) for similar households 💪",
  "nudge.savingsBelow": "Most similar households save at least {avg} of their income",
  "nudge.streaming": "You have {count} streaming services — 67% of Danish households have max 2",
  "nudge.foodAbove": "Your food budget is {pct}% above average for similar households",
  "nudge.foodBelow": "Your food budget is below average — well done! 🥗",
  "nudge.topPercentile": "Your disposable income is in the top {pct}% among similar households",
  "nudge.housingHigh": "Your housing cost is {pct}% of income — experts recommend max 33%",
  "nudge.healthTop": "Your health score is in the top 25 — you're better off than most",

  // Scenarios
  "scenario.buyHome.title": "Buy home",
  "scenario.buyHome.desc": "What happens if you switch from renting to owning?",
  "scenario.haveChild.title": "Have a child",
  "scenario.haveChild.desc": "How does a child affect your finances?",
  "scenario.newJob.title": "Change job",
  "scenario.newJob.desc": "Simulate a new salary and see the effect.",
  "scenario.intro": "Toggle scenarios and see how they affect your finances in real time.",
  "scenario.monthlyImpact": "Monthly impact",
  "scenario.newDisposable": "New disposable",
  "scenario.mortgagePayment": "Monthly mortgage payment",
  "scenario.salaryChange": "Salary change",
  "scenario.before": "Before vs. after",
  "scenario.now": "Now",
  "scenario.label": "Scenario",
  "scenario.disposablePerMonth": "available per month",
  "scenario.scoreLabel": "Score",

  // Page meta
  "page.lastUpdated": "Last updated",
  "page.updatedDate": "March 2026",

  // Actions
  "action.goToDashboard": "Go to your budget",

  // Cookie
  "cookie.text": "We use cookies to store your preferences locally. No data is sent to third parties.",
  "cookie.readMore": "Read more",
  "cookie.accept": "Accept",
  "cookie.decline": "Decline",

  // Generic
  "continue": "Continue",
  "currency": "DKK",
  "perMonth": "DKK/mo.",
  "perYear": "DKK/yr.",
  "perHalfYear": "DKK/half yr.",

  // Report
  "report.title": "Financial report",
  "report.solo": "Solo budget",
  "report.couple": "Couple budget",
  "report.postalCode": "Postal",
  "report.back": "Back",
  "report.share": "Share",
  "report.print": "Print / PDF",
  "report.health": "Financial health",
  "report.buffer": "Buffer",
  "report.monthlyIncome": "Monthly income",
  "report.totalExpenses": "Total expenses",
  "report.savingsRate": "Savings rate",
  "report.housingRatio": "Housing ratio",
  "report.expenseBreakdown": "Expense breakdown",
  "report.fixedExpenses": "Fixed expenses",
  "report.variableExpenses": "Variable expenses",
  "report.incomeDist": "Income distribution",
  "report.you": "You",
  "report.partner": "Partner",
  "report.generated": "Generated {date} · Based on Danish averages 2026",
  "report.disclaimer": "Budget tool — not financial advice",
  "report.bufferMonths": "{n} mo.",

  // Cockpit
  "cockpit.income": "Income",
  "cockpit.partner": "Partner",
  "cockpit.expenses": "Expenses",
  "cockpit.disposable": "Disposable",
  "cockpit.total": "Total",
  "cockpit.distribution": "Money distribution",
  "cockpit.savingsPotential": "Savings potential",
  "cockpit.seePlan": "See plan ↓",
  "cockpit.insights": "How are you doing?",
  "cockpit.bucket.drift": "Fixed",
  "cockpit.bucket.driftTip": "Fixed costs: housing, food, transport, insurance",
  "cockpit.bucket.frihed": "Freedom",
  "cockpit.bucket.frihedTip": "Left after fixed costs — your disposable amount",
  "cockpit.bucket.fremtid": "Future",
  "cockpit.bucket.fremtidTip": "Savings and pension contributions",
  "cockpit.bucket.risiko": "Risk",
  "cockpit.bucket.risikoTip": "Debt and variable expenses",
  "cockpit.alert.overBudget": "You spend {amount} more than you earn",
  "cockpit.alert.housingHigh": "Housing is {pct}% of income — above recommended 35%",
  "cockpit.alert.streamingMany": "{count} streaming services — average person has 2",
  "cockpit.alert.savingsStrong": "Strong savings rate of {pct}%",
  "cockpit.live.electricity": "Power: {price} DKK/kWh",
  "cockpit.live.rate": "Rate: {rate}%",
  "cockpit.live.income": "Avg. income: {amount}",

  // Categories
  "cat.Bolig": "Housing",
  "cat.Forsyning": "Utilities",
  "cat.Transport": "Transport",
  "cat.Abonnementer": "Subscriptions",
  "cat.Forsikring": "Insurance",
  "cat.Fagforening": "Union",
  "cat.Børn": "Children",
  "cat.Kæledyr": "Pets",
  "cat.Lån": "Loans",
  "cat.Fitness": "Fitness",
  "cat.Opsparing": "Savings",
  "cat.Mad & dagligvarer": "Food & groceries",
  "cat.Fritid": "Leisure",
  "cat.Tøj": "Clothing",
  "cat.Sundhed": "Health",
  "cat.Restaurant": "Restaurant",
  "cat.Andet": "Other",

  // Sankey / overview
  "sankey.incomeDistribution": "Income distributed across expenses",
  "sankey.leftOver": "Left over",
  "sankey.salary": "Salary",
  "sankey.partner": "Partner",
  "sankey.otherIncome": "Other",
  "sankey.income": "Income",
  "sankey.expenses": "Expenses",
  "sankey.whatIf": "What if?",
  "sankey.reset": "Reset",
  "sankey.perMonth": "DKK/mo.",
  "sankey.saved": "saved",
  "sankey.extra": "extra",
  // V2 features
  "sankey.privacy": "Private",
  "sankey.privacyTip": "Hide amounts — show only percentages",
  "sankey.benchmark": "50/30/20",
  "sankey.benchmarkTip": "Compare your budget to the rule of thumb",
  "sankey.projection": "Savings goal",
  "sankey.projectionTip": "What can you save with this budget?",
  "sankey.share": "Share",
  "sankey.shareTip": "Copy diagram as image",
  "sankey.needs": "Needs",
  "sankey.wants": "Wants",
  "sankey.savingsLabel": "Savings",
  "sankey.recommended": "Recommended",
  "sankey.actual": "Actual",
  "sankey.projMonths": "{n} mo.",
  "sankey.projSaved": "Savings potential",
  "sankey.projTotal": "With this budget after {n} mo.",
  "sankey.projDisclaimer": "Based on your current budget — not historical data",
  "sankey.ofIncome": "of income",
  "sankey.dkAvg": "DK avg.",
  "sankey.items": "items",
  "sankey.drillDown": "Click for details",
  "sankey.collapse": "Close",
  "sankey.copied": "Copied!",
  "sankey.export": "Export",
  "sankey.exportTip": "Save as image — perfect for sharing",
  "sankey.exportBrand": "nemtbudget.nu",
  "sankey.exportMadeWith": "Made with",
  "sankey.milestone.saver": "Great saver! You save {pct}%",
  "sankey.milestone.balanced": "Balanced budget!",
  "sankey.insight.highHousing": "Housing is {pct}% — above recommended 30%",
  "sankey.insight.goodSavings": "Your savings rate of {pct}% is above average",
  "sankey.insight.lowFree": "Only {amount} left over — consider cutting back",
  "sankey.insight.streaming": "{count} streaming services — consider bundling",
  "sankey.insight.topCat": "{cat} is your biggest expense ({pct}%)",

  // Dashboard misc
  "dash.startOver": "Start over",
  "dash.reset": "Reset",
  "dash.disclaimer": "NemtBudget is a budgeting tool — not financial advice.",
  "dash.aiTitle": "Let AI find your savings",
  "dash.aiSubtitle": "Guided walkthrough — you decide what to do",
  "dash.useDefaults": "Use defaults and see my result →",
  "dash.hideDetails": "Hide details",
  "dash.showCarDetails": "Break down car expenses",

  // Neighbor comparison
  "neighbor.comparedWith": "Compared with your income group",
  "neighbor.pair": "couples",
  "neighbor.single": "singles",
  "neighbor.housingCost": "Housing cost:",
  "neighbor.categoryByCategory": "Category by category",
  "neighbor.onPar": "On par",
  "neighbor.savingsIfLowered": "If you lower to typical level, you save",
  "neighbor.food": "Food & groceries",
  "neighbor.restaurant": "Restaurant & takeaway",
  "neighbor.transportCar": "Transport (car)",
  "neighbor.transport": "Transport",
  "neighbor.streaming": "Streaming & subscriptions",
  "neighbor.leisure": "Leisure & experiences",

  // Optimization
  "optimize.totalPotential": "Total potential",
  "optimize.lookingGood": "Your finances look strong",
  "optimize.noSavings": "We found no obvious savings — well done!",
  "optimize.doItNow": "Do it now — ",
  "optimize.dstBenchmark": "Statistics Denmark benchmark",
  "optimize.dkAverage": "DK average",
  "optimize.yourDisposable": "Your disposable income",

  // Couple split
  "couple.incomeBasedSplit": "Income-based",
  "couple.partnerIncome": "Partner's income",
  "couple.partnerPays": "Partner pays",
  "couple.expenses": "Expenses",
  "couple.remaining": "Remaining",

  // Profile edit
  "profile.householdIncome": "Household & Income",
  "profile.partnerIncomeNet": "Partner's income (net)",
  "profile.housing": "Housing",
  "profile.housingType": "Housing type",
  "profile.food": "Food & groceries",
  "profile.leisure": "Leisure & experiences",
  "profile.clothing": "Clothing & shoes",

  // Forward view
  "forward.propertyValue": "Property value",
  "forward.propertyEstimate": "Property value is an estimate — adjust in your profile",
  "forward.emergencyBuffer": "Emergency buffer (3 mo.)",
  "forward.savingsRate": "Savings rate",

  // Charts
  "charts.disposable": "Disposable income",
  "charts.average": "Average",
  "charts.lowest": "Lowest",
  "charts.highest": "Highest",
  "charts.monthNames": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
  "charts.seasonalTitle": "Expected disposable income",
  "charts.seasonalSubtitle": "Estimated based on seasonal patterns in Danish households",
  "charts.seasonalDisclaimer": "Based on average seasonal patterns — not your actual figures",

  // AI chat
  "ai.askAbout": "Ask AI about your finances",
  "ai.askShort": "Ask AI",
  "ai.limitReached": "Monthly limit reached. Resets automatically next month.",

  // Guided saving
  "guided.title": "Guided savings session",
  "guided.found": "Found",
  "guided.totalFreed": "Total freed up",

  // Share card
  "share.economyCheck": "Finance check",
  "share.freedomNumber": "Freedom number",
  "share.savingsRate": "Savings rate",
  "share.buffer": "Buffer",
  "share.footer": "Calculated with NemtBudget · 2026",

  // Subscriptions
  "subs.warning": "Over 2,000 DKK/mo. on subscriptions — consider cutting back",
  "subs.foundInBudget": "Found in your budget",

  // Profile edit (extra)
  "profile.title": "Edit your details",
  "profile.saved": "Changes saved",
  "profile.savedDesc": "Your budget has been updated.",
  "profile.householdType": "Household type",
  "profile.solo": "Single",
  "profile.couple": "Couple",
  "profile.yourIncome": "Your income (net)",
  "profile.postalCode": "Postal code",
  "profile.rentPayment": "Rent/payment",
  "profile.monthlyPayment": "Monthly housing payment",
  "profile.interestRate": "Interest rate (%)",
  "profile.spending": "Spending",
  "profile.restaurantTakeaway": "Restaurant & takeaway",
  "profile.healthMedicine": "Health & medicine",
  "profile.transport": "Transport",
  "profile.hasCar": "Has car",
  "profile.carLoan": "Car loan (mo.)",
  "profile.carFuel": "Fuel/charging (mo.)",
  "profile.carInsurance": "Car insurance (mo.)",
  "profile.subscriptions": "Subscriptions",
  "profile.loansAndSavings": "Loans & Savings",
  "profile.hasLoan": "Has loan",
  "profile.loanPayment": "Loan payment (mo.)",
  "profile.savesUp": "Saves",
  "profile.savingsMonthly": "Savings (mo.)",
  "profile.insurances": "Insurance",
  "profile.insuranceMonthly": "Insurance (mo.)",
  "profile.saveChanges": "Save changes",

  // Subscriptions (extra)
  "subs.title": "Subscriptions",
  "subs.addedManually": "Added manually",
  "subs.namePlaceholder": "Name (e.g. ChatGPT Plus)",
  "subs.pricePlaceholder": "Price per month",
  "subs.add": "Add",
  "subs.cancel": "Cancel",
  "subs.addSubscription": "Add subscription",

  // GuidedSaving (extra)
  "guided.goalReached": "You reached your goal!",
  "guided.goalReachedDesc": "You freed up {amount} DKK/mo. in total.",
  "guided.skipped": "Skipped: {label}",
  "guided.whatIsYourGoal": "What is your goal?",
  "guided.goalDesc": "I'll review your budget and find the easiest savings — you decide what to do.",
  "guided.currentDisposable": "Your current disposable income is {amount} DKK/mo.",
  "guided.skip": "Skip",
  "guided.apply": "Apply",
  "guided.goalReachedTitle": "Goal reached!",
  "guided.sessionDone": "Session complete",
  "guided.reviewedAll": "You've reviewed all suggestions.",
  "guided.acceptedChanges": "Accepted changes",
  "guided.noChanges": "No changes selected.",
  "guided.seeUpdated": "See updated budget",
  "guided.undo": "Undo",
  "guided.undoLast": "Undo last change",
  "guided.undone": "Undone: {label}",
  "guided.noResponse": "No response",
  "guided.errorRetry": "Something went wrong. Try again.",
  "guided.goalExtra": "— with {amount} more you'll have",
  "guided.findGoal": "Find {amount}",
  "guided.progressLabel": "{found} / {goal}",
  "guided.withThis": "With this: {found} / {goal} found",

  // Forward view (extra)
  "forward.wealthProjection": "Wealth projection",
  "forward.years": "years",
  "forward.estimatedWealth": "Estimated wealth (property)",
  "forward.estDebt": "Est. debt (~70%)",
  "forward.netWorth": "Net worth",
  "forward.goalsProgress": "Goals & progress",
  "forward.rateShockSim": "Rate shock simulator",
  "forward.vulnerableEconomy": "Vulnerable finances",
  "forward.refinanceAdvice": "Refinancing could reduce your exposure.",
  "forward.timeline": "Timeline — next 10 years",
  "forward.noEvents": "No major events found based on your profile.",

  // ParSplit (extra)
  "couple.desc": "See how your shared expenses can be split fairly.",
  "couple.yourIncome": "Your income",
  "couple.expenseDistribution": "Expense distribution",
  "couple.youPay": "You pay",
  "couple.evenSplit": "Even split — both have roughly the same disposable income",
  "couple.youHaveMore": "You have {amount} DKK more disposable than your partner",
  "couple.partnerHasMore": "Your partner has {amount} DKK more disposable than you",
  "couple.visualization": "Visualization",
  "couple.tip": "With income-based split, you each pay relative to your salary — try it!",

  // AI chat (extra)
  "ai.personalAdvisor": "Your personal advisor",
  "ai.analyzing": "AI is analyzing your finances...",
  "ai.usedFreeAnswers": "You've used your 5 free AI answers",
  "ai.createAccount": "Create account — watch for premium",
  "ai.answersLeft": "AI answers left this month",
  "ai.placeholder": "Ask a question about your finances...",

  // History
  "history.noHistory": "No history yet",
  "history.noHistoryDesc": "Your history will appear here once you've used NemtBudget for more than a month. Each time you update your budget, we save a snapshot — so you can track your progress over time.",
  "history.oneSnapshot": "1 snapshot saved · Update your budget again to see a chart",
  "history.disposableSinceStart": "Disposable income since start",
  "history.healthSinceStart": "Health score since start",
  "history.disposableOverTime": "Disposable income over time",
  "history.healthOverTime": "Health score over time",
  "history.calculationsSaved": "{count} calculations saved",
  "history.first": "First",
  "history.latest": "Latest",

  // Editable amount
  "edit.clickToEdit": "Click to edit",
  "edit.cancel": "Cancel",
  "edit.save": "Save",

  // Onboarding UI
  "onboarding.leftOver": "Left over",
  "onboarding.seeOverview": "See overview",
  "onboarding.stepOf": "Step {current} of {total}",

  // Optimize (extra)
  "optimize.opensExternal": "Opens external page",
  "optimize.savePerMonth": "Save {amount} DKK/mo.",

  // Auth page
  "auth.pageTitle": "Log in — NemtBudget",
  "auth.pageDesc": "Log in or create a free account to sync your budget across devices.",
  "auth.enterEmail": "Enter email",
  "auth.enterEmailDesc": "Enter your email above and we'll send you a reset link.",
  "auth.error": "Error",
  "auth.checkEmail": "Check your email",
  "auth.checkEmailDesc": "We've sent you a password reset link.",
  "auth.loginSubtitle": "Log in to sync your budget",
  "auth.signupSubtitle": "Create an account and save your budget in the cloud",
  "auth.emailPlaceholder": "Email",
  "auth.passwordPlaceholder": "Password",
  "auth.waiting": "Wait...",
  "auth.login": "Log in",
  "auth.signup": "Create account",
  "auth.forgotPassword": "Forgot password?",
  "auth.noAccount": "Don't have an account? Sign up free",
  "auth.hasAccount": "Already have an account? Log in",
  "auth.continueWithout": "← Continue without login",
  "auth.newPasswordSubtitle": "Choose a new password",
  "auth.newPasswordPlaceholder": "New password",
  "auth.resetPassword": "Reset password",
  "auth.passwordMinLength": "Password must be at least 6 characters.",
  "auth.passwordResetSuccess": "Password updated",
  "auth.passwordResetSuccessDesc": "Your password has been changed. You can now log in.",
  "auth.sessionExpired": "Session expired",
  "auth.sessionExpiredDesc": "Your session has expired. Log in again to sync.",

  // Install page
  "install.pageTitle": "Install NemtBudget — Free budget app",
  "install.pageDesc": "Install NemtBudget as an app on your phone — no app store needed. Get a quick overview of your budget.",
  "install.installed": "NemtBudget is installed!",
  "install.title": "Install NemtBudget",
  "install.installedDesc": "Open the app from your home screen for the best experience.",
  "install.desc": "Get NemtBudget as an app on your phone — no app store needed.",
  "install.goToApp": "Go to NemtBudget →",
  "install.installNow": "Install now",
  "install.iosTitle": "How to install on iPhone:",
  "install.iosStep1": "Tap",
  "install.iosStep1Share": "Share ↑",
  "install.iosStep1Suffix": "in Safari",
  "install.iosStep2": "Choose \"Add to Home Screen\"",
  "install.iosStep3": "Tap \"Add\"",
  "install.openInBrowser": "Open this page in Chrome or Safari to install the app.",
  "install.back": "← Back to NemtBudget",

  // NotFound page
  "notFound.title": "404",
  "notFound.message": "Oops! Page not found",
  "notFound.link": "Return to Home",

  // AI Welcome Insight
  "ai.insightLabel": "AI Insight",
  "ai.fallback": "Your finances are ready for analysis. Continue to your dashboard for the full overview.",

  // NaboeffektView
  "neighbor.aheadOfAvgPar": "You are ahead of the average",
  "neighbor.aheadOfAvgSolo": "You are ahead of the average",
  "neighbor.moreLeftPar": "You have",
  "neighbor.moreLeftSolo": "You have",
  "neighbor.moreLeftSuffix": "DKK more left over than others with your profile.",
  "neighbor.potentialSaving": "Potential saving:",
  "neighbor.biggestOpportunity": "Biggest opportunity:",
  "neighbor.overTypical": "DKK above typical",
  "neighbor.ofIncome": "of income",
  "neighbor.expertsRecommend": "Experts recommend max 33% —",
  "neighbor.youUsePar": "you use",
  "neighbor.youUseSolo": "you use",
  "neighbor.percentPointMore": "percentage points more",
  "neighbor.adjustFood": "Adjust food budget",
  "neighbor.seeSavings": "See savings suggestions",
  "neighbor.seeTransport": "See transport optimization",
  "neighbor.reviewSubs": "Review subscriptions",
  "neighbor.seeLeisure": "See leisure budget",
  "neighbor.optimize": "Optimize",
  "neighbor.youLabel": "You",
  "neighbor.youLabelPar": "You",
  "neighbor.typicalLabel": "Typical",
  "neighbor.industryLabel": "Typical ({industry})",
  "neighbor.benchmarkIndustry": "Adjusted for industry.",
  "neighbor.perYear": "DKK per year",
  "neighbor.benchmarkFootnote": "Benchmarks based on Statistics Denmark —",
  "neighbor.benchmarkSingles": "singles",
  "neighbor.benchmarkCouples": "couples",
  "neighbor.benchmarkSuffix": "in your income group · 2025",

  // ProfileEditSheet housing types
  "profile.housingLeje": "Renter",
  "profile.housingEjer": "Owner",
  "profile.housingAndel": "Co-op",
  "profile.housingUngdomsbolig": "Student housing",
  "profile.netflix": "Netflix (149 DKK)",
  "profile.spotify": "Spotify (109 DKK)",
  "profile.hboMax": "HBO Max (99 DKK)",
  "profile.viaplay": "Viaplay (99 DKK)",
  "profile.disneyPlus": "Disney+ (99 DKK)",
  "profile.appleTvPlus": "Apple TV+ (59 DKK)",
  "profile.amazonPrime": "Amazon Prime (89 DKK)",

  // FremadView extras
  "forward.expectedWealth": "Expected wealth",
  "forward.interestLabel": "Rate:",
  "forward.ofGoal": "of goal",
  "forward.goalLabel": "goal",
  "forward.exceedsRecommendation": "You exceed the recommendation!",
  "forward.currentLabel": "Current",
  "forward.leftAfter": "DKK left",
  "forward.mortgageSearch": "Mortgage",
  "forward.seeRefinance": "See what refinancing can do →",

  // ShareCard
  "share.brandName": "NemtBudget",
  "share.brandUrl": "nemtbudget.nu",
  "share.bucketDrift": "Fixed",
  "share.bucketFrihed": "Freedom",
  "share.bucketFremtid": "Future",
  "share.bucketRisiko": "Risk",

  // Units (extra)
  "unit.krKwh": "DKK/kWh",
  "unit.possible": "possible",

  // LossAversionInsights
  "insights.heading": "Insights based on your numbers",
  "insights.incomeBadge": "Income vs. neighbors",
  "insights.neighborLabel": "your postal code",
  "insights.incomeBelow": "You earn {amount} DKK/mo. below the average in {postal}",
  "insights.incomeBelowValue": "−{amount} {unit}/yr.",
  "insights.incomeBelowSub": "Average income in {neighborLabel} is {avg} DKK/mo. after tax. Not necessarily a problem — but good to know. (Source: {source})",
  "insights.incomeAbove": "You earn {amount} DKK/mo. above the average in {postal}",
  "insights.incomeAboveValue": "+{amount} {unit}/yr.",
  "insights.incomeAboveSub": "Average income in {neighborLabel} is {avg} DKK/mo. after tax. You're above the median — is your budget making the most of it? (Source: {source})",
  "insights.subsBadge": "Subscriptions per year",
  "insights.subsTitle": "{count} streaming services cost {amount} DKK per year",
  "insights.subsSub": "Most people actively use 1-2. Individual costs: Netflix {netflix}, Viaplay {viaplay}, HBO {hbo} DKK/yr. Rotating can save money.",
  "insights.savingsBadge": "Savings opportunity",
  "insights.savingsTitle": "You have {amount} DKK/mo. left — but save nothing",
  "insights.savingsSub": "{monthly} DKK/mo. in a global index fund (historical ~7%/yr) gives {total} DKK in 15 years with compound interest. Every month without saving, you lose this potential.",
  "insights.elCheapNowBadge": "Power cheapest now ⚡",
  "insights.elCheapBadge": "Cheapest power today",
  "insights.elCheapNowTitle": "Electricity is cheapest now ({price} DKK/kWh) — run dishwasher and dryer",
  "insights.elScheduleTitle": "Run dishwasher and washing machine at {hours}",
  "insights.elSavingSub": "{saving} DKK/kWh cheaper than the most expensive time today. Running a dryer (2 kWh) at {cheap} vs {expensive} DKK/kWh saves {total} DKK. (Live data: Energi Data Service)",
  "insights.elLiveSub": "Based on live Elspot data from Energi Data Service, updated today.",

  // B2B page
  "b2b.heroTag": "B2B Partnership",
  "b2b.heroTitle": "Give your customers Denmark's smartest",
  "b2b.heroTitleHighlight": "budget tool",
  "b2b.heroTitleSuffix": "— under your own brand",
  "b2b.heroSubtitle": "NemtBudget is an AI-powered budget platform ready for white-label. Integrate it into your customer experience in under 2 weeks — no bank connection required.",
  "b2b.liveDemo": "See live demo",
  "b2b.contactUs": "Contact us",
  "b2b.whyTitle": "Why banks choose NemtBudget",
  "b2b.whiteLabelReady": "White-label ready",
  "b2b.whiteLabelDesc": "Your logo, colors and branding. Customers experience it as your own product. No visible reference to NemtBudget.",
  "b2b.aiPowered": "AI-powered",
  "b2b.aiPoweredDesc": "Personal recommendations, optimization suggestions and intelligent chat. Powered by Claude — the world's most advanced AI.",
  "b2b.privacyFirst": "Privacy-first",
  "b2b.privacyFirstDesc": "No bank connection needed. Users enter data themselves — full control, no compliance headaches.",
  "b2b.featureTitle": "Everything your customers need",
  "b2b.featureSubtitle": "Cockpit overview, Sankey flow, AI optimization, future projection and much more.",
  "b2b.feat.cockpit": "Budget cockpit",
  "b2b.feat.cockpitDesc": "Overview of income, expenses and disposable on one dashboard.",
  "b2b.feat.sankey": "Sankey diagram",
  "b2b.feat.sankeyDesc": "Visualize money flows from income to expenses.",
  "b2b.feat.aiOpt": "AI optimization",
  "b2b.feat.aiOptDesc": "Personal savings suggestions based on the user's profile.",
  "b2b.feat.projection": "Future projection",
  "b2b.feat.projectionDesc": "See how finances develop over 1-5 years.",
  "b2b.feat.stress": "Stress test",
  "b2b.feat.stressDesc": "What happens with rate hikes or job change?",
  "b2b.feat.neighbor": "Neighbor effect",
  "b2b.feat.neighborDesc": "Compare with others in the same postal code.",
  "b2b.brandTitle": "See it in your brand",
  "b2b.brandSubtitle": "Try our live demos with Nordea and Danske Bank branding.",
  "b2b.pricingTitle": "Simple and transparent pricing",
  "b2b.pricingSubtitle": "All plans include setup, white-label design, operations and support.",
  "b2b.mostPopular": "Most popular",
  "b2b.getStarted": "Get started",
  "b2b.starter.users": "Up to 10,000 users",
  "b2b.starter.f1": "White-label design",
  "b2b.starter.f2": "Setup & onboarding",
  "b2b.starter.f3": "Operations & hosting",
  "b2b.starter.f4": "Email support",
  "b2b.starter.f5": "Monthly report",
  "b2b.growth.users": "Up to 50,000 users",
  "b2b.growth.f1": "Everything in Starter",
  "b2b.growth.f2": "AI advisory",
  "b2b.growth.f3": "Priority support",
  "b2b.growth.f4": "Custom integrations",
  "b2b.growth.f5": "Quarterly review meetings",
  "b2b.enterprise.price": "Contact us",
  "b2b.enterprise.users": "Unlimited users",
  "b2b.enterprise.f1": "Everything in Growth",
  "b2b.enterprise.f2": "Dedicated account manager",
  "b2b.enterprise.f3": "SLA guarantee",
  "b2b.enterprise.f4": "On-premise option",
  "b2b.enterprise.f5": "API access",
  "b2b.testimonialTitle": "What our partners say",
  "b2b.testimonialQuote": "We are onboarding our first bank partners. Contact us for references.",
  "b2b.testimonialLink": "Contact us for references",
  "b2b.contactTitle": "Contact us",
  "b2b.contactSubtitle": "Fill out the form and we'll get back to you within 24 hours.",
  "b2b.thankYou": "Thank you for your inquiry!",
  "b2b.thankYouDesc": "Your email client is now opening with a pre-filled message. We'll get back to you as soon as possible.",
  "b2b.labelName": "Name",
  "b2b.labelCompany": "Company",
  "b2b.labelEmail": "Email",
  "b2b.labelMessage": "Message",
  "b2b.placeholderName": "Your name",
  "b2b.placeholderCompany": "Company name",
  "b2b.placeholderMessage": "Tell us about your needs...",
  "b2b.submit": "Send inquiry",
  "b2b.emailSubject": "B2B inquiry from {company}",

  // Partner page
  "partner.noToken": "No token",
  "partner.invalidToken": "Invalid token",
  "partner.contactEmail": "Contact hej@nemtbudget.nu",
  "partner.noActivity": "No activity yet",
  "partner.noEvents": "No events yet",
  "partner.uniqueSessions": "Unique sessions",
  "partner.uniqueSessionsSub": "Unique users who opened the tool",
  "partner.budgetsCreated": "Budgets created",
  "partner.conversion": "{pct}% conversion",
  "partner.aiQuestions": "AI questions",
  "partner.aiQuestionsSub": "Questions to the AI advisor",
  "partner.reports": "Reports",
  "partner.reportsSub": "Downloaded financial reports",
  "partner.dailyActivity": "Daily activity — last 30 days",
  "partner.memberUsage": "What do your members use?",
  "partner.event.onboarding_start": "Started onboarding",
  "partner.event.onboarding_complete": "Completed budget calculation",
  "partner.event.dashboard_view": "Opened dashboard",
  "partner.event.ai_chat_open": "Opened AI advisor",
  "partner.event.ai_message_sent": "Asked AI a question",
  "partner.event.report_generated": "Generated financial report",
  "partner.embedTitle": "Integration — embed code",
  "partner.embedSub": "Works in any web portal in 5 minutes",
  "partner.copyCode": "Copy code",
  "partner.dashboard": "Partner Dashboard",

  // Blog page
  "blog.searchPlaceholder": "Search guides...",
  "blog.readTime": "read",
  "blog.headerTitle": "Guides & tips",
  "blog.heroTitle": "Get smarter about your finances",
  "blog.heroSubtitle": "Practical guides, savings tips and calculations built for Danish personal finance.",
  "blog.ctaTitle": "Try {brand} for free",
  "blog.ctaSubtitle": "Calculate your disposable income in 3 minutes",
  "blog.ctaButton": "Get started →",

  // Article page
  "article.guides": "Guides",
  "article.ctaTitle": "Calculate your own disposable income",
  "article.ctaSubtitle": "Free · 3 minutes · No login",
  "article.ctaButton": "Try {brand} →",

  // Onboarding extras
  "onboarding.perMonthAfterExpenses": "per month after all expenses",
  "onboarding.estimatedAdjust": "We have estimated these — adjust if they don't match",
  "onboarding.everydayExpenses": "Everyday expenses",
  "onboarding.ofIncome": "of income",

  // Dashboard extras
  "dash.sectionTabs": "Section tabs",

  // FremadView timeline events
  "forward.childN": "Child",
  "forward.yourChild": "Your child",
  "forward.startsSFO": "starts SFO",
  "forward.sfoDesc": "SFO cost 2,100 DKK/mo.",
  "forward.leavesKindergarten": "leaves kindergarten",
  "forward.kindergartenDesc": "Childcare cost drops 2,600 DKK/mo.",
  "forward.turns7": "turns 7 – child benefit drops",
  "forward.turns7Desc": "Reduced by 1,130 DKK/mo.",
  "forward.leavesSFO": "leaves SFO",
  "forward.leavesSFODesc": "SFO cost ends.",
  "forward.turns18": "turns 18",
  "forward.childBenefitEnds": "Child benefit ends.",
  "forward.checkInterestOnly": "Check interest-only period",
  "forward.checkInterestOnlyDesc": "Many loans from 2018–2020 have 10-year interest-only periods.",
  "forward.basedOnInvested": "Based on {amount} invested",
  "forward.projectionPrefix": "at 7% annual return gives approx.",
  "forward.projectionMid": "in 5 years and",
  "forward.projectionSuffix": "in 10 years. Investment involves risk.",
  "forward.increaseToReach20": "Increase by {amount} to reach 20%",
  "unit.krMonth": "DKK/mo.",
  "unit.krYear": "DKK/yr.",
  "unit.krHalfYear": "DKK/half yr.",
  "unit.currency": "DKK",

  // AIChatPanel suggestion questions
  "ai.q.christmasBudget": "How does my budget handle Christmas?",
  "ai.q.summerSavings": "Can I save for summer vacation?",
  "ai.q.switchInsurance": "Should I switch insurance at renewal?",
  "ai.q.cutMost": "Where can I cut the most?",
  "ai.q.carCost": "What does my car really cost?",
  "ai.q.dropStreaming": "Which streaming can I drop?",
  "ai.q.rateRise": "What if rates rise 2%?",
  "ai.q.startSaving": "How do I start saving?",

  // Dashboard terms link
  "dash.termsLink": "Terms",

  // Subscriptions (units)
  "subs.activeCount": "active subscriptions",

  // Optimization (units)
  "optimize.perYearFollowPlan": "by following the plan",

  // Couple split
  "couple.remaining.suffix": "remaining",

  // History
  "history.points": "points",
  "history.tooltipDisposable": "Disposable",

  // Onboarding
  "onboarding.adjustAmount": "Adjust the amount above if it doesn't match.",
  "onboarding.emailReminder": "Yes, send me a quarterly reminder to review my budget.",
  "onboarding.emailUnsubscribe": "You can unsubscribe at any time.",
  "onboarding.expenseShare": "Expense share",
  "step.income.minWarning": "Enter at least 1,000 kr. combined income to continue.",
  "onboarding.encourage.income": "Great! Now we know who you are 🎯",
  "onboarding.encourage.housing": "Nice — let's sort out housing 🏠",
  "onboarding.encourage.everyday": "Halfway there! Housing is locked in ✅",
  "onboarding.encourage.fixed": "Almost done — just the fixed expenses 📋",
  "onboarding.encourage.review": "Last step — you're almost done! 🏁",

  // Error boundary
  "error.somethingWrong": "Something went wrong",
  "error.unexpectedError": "An unexpected error occurred. Try reloading the page.",
  "error.reloadPage": "Reload page",

  // Section error boundary
  "error.sectionFailed": "could not be displayed",
  "error.tryReload": "Try reloading the page",
  "error.tryAgain": "Try again",

  // Page loader
  "loader.loading": "Loading...",

  // Demo banner
  "demo.text": "Demo — NemtBudget white-label for {brand}. All data is sample data.",
  "demo.bookPresentation": "Book presentation",
  "demo.trySelf": "Try it yourself",
  "demo.closeBanner": "Close demo banner",

  // Suite nav
  "nav.comingSoon": "Soon",

  // Dark mode toggle
  "darkMode.switchToLight": "Switch to light mode",
  "darkMode.switchToDark": "Switch to dark mode",

  // Cookie banner
  "cookie.consent": "Cookie consent",
  "cookie.acceptAnalytics": "Accept analytics cookies",
  "cookie.declineAnalytics": "Decline analytics cookies",

  // Cockpit
  "cockpit.alertsLabel": "Alerts",
  "cockpit.critical": "Critical",
  "cockpit.warning": "Warning",
  "cockpit.insight": "Insight",

  // Share card
  "share.bufferUnit": "mo.",

  // Share budget deep-link
  "share.title": "Share your budget",
  "share.description": "Add context so others understand your situation",
  "share.copyLink": "Copy",
  "share.copied": "Copied!",
  "share.privacyNote": "The link only contains the numbers and context you choose — no postal code, email or personal data is shared.",
  "share.reddit": "Share on r/dkfinance",
  "share.chars": "chars",
  "share.autoContext": "Your profile shows automatically",
  "share.addContext": "Add context (optional)",
  "share.agePlaceholder": "Age",
  "share.jobPlaceholder": "Job title",
  "share.cityPlaceholder": "City",
  "share.questionPlaceholder": "What would you like feedback on?",
  "share.generateLink": "Generate share link",
  "share.generating": "Generating...",
  "share.tagSolo": "Single",
  "share.tagCouple": "Couple",
  "share.tagChildren": "{count} kids ({ages})",
  "share.tagRenter": "Renter",
  "share.tagOwner": "Homeowner",
  "share.tagCoop": "Co-op",
  "share.tagCar": "Car",
  "share.tagSaves": "Saving",
  "share.tagYears": "y/o",
  "share.preview": "This is what the recipient sees",
  "share.q.canBuyHome": "Can I/we afford to buy a home?",
  "share.q.refinance": "Should I refinance my mortgage?",
  "share.q.tooMuchStreaming": "Am I spending too much on streaming?",
  "share.q.carWorth": "Is my car budget reasonable?",
  "share.q.canAffordCar": "Can I afford a car?",
  "share.q.howToSave": "How do I start saving?",
  "share.q.savingsEnough": "Am I saving enough?",
  "share.q.maternity": "Can we manage on parental leave?",
  "share.q.generalFeedback": "Rate my budget!",
  "share.payslipToggle": "Add payslip",
  "share.payslipTitle": "Payslip",
  "share.payslipHint": "Add your gross salary to show what happens to your pay before it hits your account.",
  "share.ps.gross": "Gross salary",
  "share.ps.grossLabel": "Gross (kr/mo)",
  "share.ps.amBidrag": "Labour contrib. (8%)",
  "share.ps.pension": "Pension",
  "share.ps.pensionLabel": "Pension",
  "share.ps.tax": "Income tax",
  "share.ps.taxLabel": "Tax rate",
  "share.ps.atp": "ATP",
  "share.ps.net": "Take-home",
  "share.ps.netShort": "net",
  "share.modeLink": "Link",
  "share.modeImage": "Image",
  "share.nativeShare": "Share...",
  "share.shareImage": "Share image",
  "share.copyText": "Copy as text",
  "share.copiedText": "Text copied!",
  "share.textHeader": "My budget",
  "share.textFooter": "Calculated with nemtbudget.nu",
  "shared.banner": "Shared budget",
  "shared.bannerCta": "Create your own budget",
  "shared.closeBanner": "Close banner",
  "dash.share": "Share",

  // Payslip upload
  "payslip.title": "Upload your payslip",
  "payslip.subtitle": "Take a photo or upload a PDF — the AI reads it and anonymizes everything automatically",
  "payslip.dropzone": "Drag file here, click to select, or paste with Ctrl+V",
  "payslip.pasteHint": "Tip: You can also just press Ctrl+V with a screenshot in your clipboard",
  "payslip.acceptedFormats": "JPG, PNG or PDF (max 5 MB)",
  "payslip.privacy": "Your image is sent encrypted for analysis and deleted immediately after. We store nothing.",
  "payslip.journey.title": "What happens to your payslip?",
  "payslip.journey.step1": "Your phone",
  "payslip.journey.step1Detail": "Image is compressed in your browser",
  "payslip.journey.step2": "AI reads the numbers",
  "payslip.journey.step2Detail": "Encrypted. No humans see it.",
  "payslip.journey.step3": "Deleted instantly",
  "payslip.journey.step3Detail": "Only numbers are sent back. The image is gone.",
  "payslip.journey.honest": "Honestly: While the AI reads (3-8 sec), it can see the full image — including personal ID and name. It runs on a locked server, no humans have access, and the image is deleted right after. We store nothing.",
  "payslip.journey.disclaimer": "NemtBudget is a free budget tool, not an advisor. Payslip analysis may contain errors — always double-check. Upload = acceptance of AI processing as described.",
  "payslip.processing": "Reading your payslip...",
  "payslip.processingHint": "The AI is analyzing numbers, deductions and context",
  "payslip.step1": "Upload image or PDF",
  "payslip.step2": "AI reads all numbers",
  "payslip.step3": "Anonymized and ready to share",
  "payslip.result.title": "Your payslip",
  "payslip.result.employer": "Employer",
  "payslip.result.municipality": "Municipality",
  "payslip.result.payrollSystem": "Payroll system",
  "payslip.result.confidenceHigh": "High confidence",
  "payslip.result.confidenceMedium": "Medium confidence",
  "payslip.result.confidenceLow": "Low confidence",
  "payslip.privateInfo": "Private info (not shared)",
  "payslip.privateNote": "This information is only shown to you and is never included when sharing",
  "payslip.cta.share": "Share anonymously",
  "payslip.cta.budget": "Create full budget",
  "payslip.crossPromo.title": "Want to see where your money actually goes?",
  "payslip.crossPromo.desc": "Upload your bank statement and combine it with your payslip — we'll pre-fill your budget with both your income AND your actual spending.",
  "payslip.crossPromo.cta": "Try the Money Check",
  "payslip.cta.retry": "Try again",
  "payslip.error.tooLarge": "File is too large (max 5 MB)",
  "payslip.error.invalidType": "Invalid file type — use JPG, PNG or PDF",
  "payslip.error.readFailed": "Could not read the payslip — try a clearer image",
  "payslip.deductions.gross": "Gross salary",
  "payslip.deductions.net": "Net pay",
  "payslip.deductions.amBidrag": "Labour market contribution (8%)",
  "payslip.deductions.pension": "Pension",
  "payslip.deductions.aSkat": "Income tax",
  "payslip.deductions.atp": "ATP",
  "payslip.deductions.union": "Union dues",
  "payslip.deductions.healthIns": "Health insurance",
  "payslip.deductions.fritvalg": "Flexible benefits",
  "payslip.deductions.feriepenge": "Holiday pay",
  "payslip.deductions.other": "Other deductions",
  "payslip.shareHeader": "My payslip",
  "payslip.shareKeepPct": "I keep {pct}% of my gross salary",
  "payslip.welcomeCta": "Have a payslip? Upload it and see your budget in 10 seconds",

  // Index page
  "confirm.resetBudget": "Are you sure? This will delete your current budget and start over.",
  "confirm.editProfile": "Do you want to edit your details? Your current data will be used as a starting point.",

  // Admin
  "admin.title": "SEO Content Queue",
  "admin.draftsAwait": "drafts awaiting approval",
  "admin.refresh": "Refresh",
  "admin.emptyQueue": "No drafts in queue. Next article will be generated automatically.",
  "admin.readTime": "read time",
  "admin.approve": "Approve",
  "admin.reject": "Reject",
  "admin.published": "Article published!",
  "admin.rejected": "Draft rejected",
  "admin.error": "Error",

  // Salary comparison (payslip result page)
  "salary.comparison": "Salary comparison",
  "salary.yourGross": "Your gross salary",
  "salary.industryMedian": "Median for {industry}",
  "salary.percentile": "You're in the {pct}th percentile",
  "salary.aboveMedian": "above median",
  "salary.belowMedian": "below median",
  "salary.atMedian": "around the median",
  "salary.fewObservations": "Based on few observations — treat with caution",
  "salary.contributeTitle": "Help others with salary transparency",
  "salary.contributeDesc": "Share your anonymous salary data so others can compare. No personal data is shared.",
  "salary.contributed": "Thanks! Your anonymous salary data has been recorded.",
  "salary.noData": "Not enough data for your industry yet",

  // Payslip image export
  "payslip.exportImage": "Share as image",
  "payslip.downloadImage": "Download image",
  "payslip.exportImageDesc": "Perfect for Reddit",
  "payslip.keepPct": "I keep {pct}% of my gross salary",
  "payslip.imageCopied": "Image copied!",
  "payslip.imageDownloaded": "Image downloaded!",
  "payslip.shareToReddit": "Share on r/dkloenseddel",
  "payslip.card.grossPay": "Gross pay",
  "payslip.card.totalDeductions": "Total deductions",
  "payslip.card.netPay": "Net pay",
  "payslip.card.deductionBreakdown": "Deductions",
  "payslip.card.madeWith": "Made with",
  "payslip.card.cta": "Make your own for free",
  "payslip.card.rankBadge": "Top {pct}% in {industry}",
  "payslip.card.heroSubtitle": "paid out of your gross salary",
  "payslip.card.budgetSection": "My budget",
  "payslip.share.sectionTitle": "Share on Reddit",
  "payslip.share.step1": "Copy image",
  "payslip.share.step2": "Open Reddit",
  "payslip.share.step2Hint": "Paste the image with Ctrl+V in the Reddit post",
  "payslip.share.includeBudget": "Include my budget in the image",
  "salary.autoContributed": "Your anonymous salary data helps others compare",
  "salary.consentLabel": "Yes, contribute my anonymous salary to the shared salary statistics. Only industry, region, and rounded gross/net salary are shared — no personal data.",
  "payslip.meta.title": "Scan your payslip — find hidden benefits and compare your salary",
  "payslip.meta.description": "Upload your payslip and see exactly what you pay in tax, what your employer pays for you, and whether your salary is above or below the median in your industry.",
  "payslip.landing.headline": "Scan your payslip — see what you're missing",
  "payslip.landing.subheadline": "Upload an image or PDF. We find hidden benefits, compare your salary to your industry, and create a budget in 10 seconds.",
  "payslip.landing.socialProof": "Share anonymously on r/dkloenseddel, r/dkfinance or other forums",

  "payslip.explain.amBidrag": "AM-bidrag (labour market contribution) is an 8% tax that funds unemployment benefits, sick pay and labour market training. All employees pay it — it's the first thing deducted from your salary.",
  "payslip.explain.pension": "Your pension savings typically consist of an employee contribution + an employer contribution. The money is invested and paid out when you retire. The higher the pension %, the more you save.",
  "payslip.explain.aSkat": "A-skat is your income tax calculated from your tax card rate and personal allowance. The rate depends on your municipality, church tax, and interest deductions. Check your preliminary assessment at skat.dk.",
  "payslip.explain.atp": "ATP (Supplementary Labour Market Pension) is a mandatory pension scheme. You pay 1/3 and your employer 2/3. It provides a small guaranteed pension on top of the state pension.",
  "payslip.explain.fagforening": "Union membership covers your professional organisation. They negotiate your collective agreement (salary, holidays, termination terms) and can help with workplace issues.",
  "payslip.explain.sundhedsforsikring": "A health insurance paid through your salary — typically a company policy. Provides faster access to specialists, physiotherapy and psychologists without public system waiting times.",
  "payslip.explain.fritvalg": "Fritvalg is a savings account from your collective agreement. You can typically use it for extra holiday, pension or cash payout. The percentage is set in your agreement.",
  "payslip.explain.feriepenge": "Holiday pay is 12.5% of your salary set aside for holidays. You receive it when you take time off. Since 2020, holiday pay follows the concurrent holiday act.",

  "payslip.range.amBidrag": "Always 8% of the income base — this is fixed for everyone",
  "payslip.range.pension": "Typically 12-17% total (your + employer share). Below 8% is low.",
  "payslip.range.aSkat": "Normal tax rate: 35-42%. Lower with large interest deductions, higher in expensive municipalities.",
  "payslip.range.atp": "Fixed at 99.45 DKK/month for full-time (your share). Always the same amount.",
  "payslip.range.fagforening": "Typically 300-600 DKK/month. Varies by union and insurance options.",
  "payslip.range.sundhedsforsikring": "Typically 50-200 DKK/month. Employer-paid benefit.",
  "payslip.range.fritvalg": "Typically 1-7% of salary depending on collective agreement.",
  "payslip.range.feriepenge": "12.5% of holiday-eligible salary. Statutory rate.",

  // Hero section
  "payslip.hero.youKeep": "You keep",
  "payslip.hero.paidOut": "paid out",
  "payslip.hero.annual": "That's {amount} per year",
  "payslip.hero.gross": "Gross: {monthly}/mo · {annual}/yr",
  "payslip.hero.atypicalMonth": "This month is atypical (one-time payments)",
  "payslip.hero.normalGross": "Normal gross: approx. {amount}/mo · {annual}/yr",

  // Section headers
  "payslip.section.breakdown": "From gross to take-home",
  "payslip.section.insights": "3 things to know",

  // Insight status labels
  "payslip.insight.aboveNormal": "above normal",
  "payslip.insight.belowNormal": "below normal",

  // Detailed insights
  "payslip.insight.effectiveTax": "Effective tax rate",
  "payslip.insight.effectiveTaxDetail": "Your tax card rate is {marginal}%, but your effective tax rate is {effective}% of gross (AM contribution + income tax + ATP). Personal allowance: {personfradrag}/mo.",
  "payslip.insight.pensionTitle": "Pension health",
  "payslip.insight.pensionDetail": "Your pension is {pct}% (you: {employee} + employer: {employer}). Average is 12-17%.",
  "payslip.insight.pensionLow": "Below average — consider increasing your pension contribution.",
  "payslip.insight.pensionGood": "Great! Your pension is above average.",
  "payslip.insight.annualTitle": "Annual overview",
  "payslip.insight.annualTitleNormal": "Typical annual salary",
  "payslip.insight.annualDetail": "Over 12 months: {gross} gross → {deductions} in tax/deductions → {net} paid out.",
  "payslip.insight.annualNormalDetail": "Based on your base salary: approx. {gross}/yr ({monthly}/mo). This month's one-time payments are excluded.",

  // What does SKAT see?
  "payslip.section.hiddenBenefits": "Hidden benefits from your employer",
  "payslip.benefits.intro": "Beyond your salary, your employer pays for benefits you don't see in your account — but that work for you.",
  "payslip.benefits.pension": "Employer pension",
  "payslip.benefits.health": "Health insurance",
  "payslip.benefits.feriepenge": "Vacation pay (accrued)",
  "payslip.benefits.fritvalg": "Flexible benefit account",
  "payslip.benefits.total": "Total annual value",
  "payslip.benefits.healthHint": "You have health insurance through your employer. Check if your private insurance overlaps — you may be able to save.",
  "payslip.section.skatView": "What does SKAT see?",
  "payslip.skat.intro": "SKAT doesn't see your gross salary directly. Pension and ATP are deducted first — that's why SKAT's numbers are lower than you'd expect.",
  "payslip.skat.step.brutto": "Gross salary",
  "payslip.skat.step.pension": "Pension (your share)",
  "payslip.skat.step.atp": "ATP",
  "payslip.skat.step.amGrundlag": "AM base",
  "payslip.skat.step.amGrundlagNote": "The 8% AM contribution is calculated on this amount",
  "payslip.skat.step.amBidrag": "AM contribution (8%)",
  "payslip.skat.step.aIndkomst": "Taxable income",
  "payslip.skat.step.aIndkomstNote": "Income tax is calculated on this amount (minus personal allowance)",
  "payslip.skat.annual.title": "Annual reporting",
  "payslip.skat.annual.naive": "Gross × 12 = {naive}",
  "payslip.skat.annual.real": "SKAT sees approx. {real}/year (AM base × 12)",
  "payslip.skat.annual.diff": "Difference: {diff} — pension + ATP deducted first",
  "payslip.skat.opsparing.title": "Accrued amounts",
  "payslip.skat.opsparing.detail": "Holiday supplement, flex pay etc. ({amount}/mo) are accrued on your payslip but only taxed when paid out. This means SKAT's annual figure may be even lower than AM base × 12.",

  // Pension & tax details
  "payslip.pension.employerContrib": "You: {employee} + Employer: {employer}",
  "payslip.tax.traekprocent": "Tax card rate",
  "payslip.tax.personfradrag": "Personal allowance",

  // Teaser card
  "payslip.teaser.title": "Your sharing card is ready",
  "payslip.teaser.subtitle": "Share anonymously on Reddit — no personal data",

  // Verification screen
  "payslip.verify.title": "We found these items on your payslip",
  "payslip.verify.subtitle": "Do the numbers look right? Tap the pencil to correct.",
  "payslip.verify.confirm": "Looks correct",
  "payslip.verify.retry": "Upload again",
  "payslip.verify.rawLines": "Raw lines from payslip",

  // Salary comparison
  "payslip.salary.dstSource": "Based on Statistics Denmark 2025",
  "payslip.salary.yourGross": "Your gross salary",
  "payslip.salary.difference": "Difference",
  "payslip.salary.showAll": "Show all industries",
  "payslip.salary.showFewer": "Show fewer",
  "payslip.salary.normalMonth": "typical month",
  "payslip.ctaTitle": "Have a payslip?",
  "payslip.ctaDesc": "Upload your payslip image and get a full analysis with deductions, salary comparison and a shareable image.",

  // Accessibility
  "a11y.chartSummary": "Chart summary",
  "a11y.sankeyTable": "Budget flow",
  "a11y.historyDisposable": "Disposable income over time",
  "a11y.historyScore": "Health score over time",
  "a11y.partnerSplit": "Expense distribution between partners",
  "a11y.bucketChart": "Budget distribution by category",
  "a11y.skipToContent": "Skip to content",

  // Consent & dropzone accessibility
  "salary.consentLabel": "Help others: Share your anonymous salary data (industry + region + salary level) so others can compare. We never store your name or personal ID.",
  "payslip.dropzone.ariaLabel": "Upload payslip — drag and drop or click",
  "pengetjek.dropzone.ariaLabel": "Upload bank statement — drag and drop or click",

  // Homepage meta
  "meta.title": "Free budget calculator — Calculate your disposable income | NemtBudget",

  // ── Money Check ──
  "pengetjek.meta.title": "Money Check — See where your money goes | NemtBudget.nu",
  "pengetjek.meta.description": "Upload your bank statement and get an overview of your spending in 30 seconds. Free and anonymous.",
  "pengetjek.landing.headline": "Money Check",
  "pengetjek.landing.subheadline": "See where your money really goes — upload a bank statement or screenshot from your banking app",
  "pengetjek.dropzone": "Upload bank statement or screenshot from your banking app",
  "pengetjek.pasteHint": "You can also paste a screenshot (Ctrl+V)",
  "pengetjek.acceptedFormats": "PDF, image or CSV file",
  "pengetjek.processing": "Analyzing your bank statement...",
  "pengetjek.processingHint": "We're categorizing all transactions — this takes 10-20 seconds",
  "pengetjek.step1": "Upload statement, screenshot or CSV",
  "pengetjek.step2": "AI categorizes all transactions",
  "pengetjek.step3": "See where the money goes — no data stored",
  "pengetjek.privacy.summary": "CSV is analyzed in your browser — nothing is sent. Images/PDFs are encrypted, analyzed by AI, and deleted instantly.",
  "pengetjek.journey.title": "What happens to your data?",
  "pengetjek.journey.step1": "Your browser",
  "pengetjek.journey.step1Detail": "CSV? Everything happens here. Nothing sent.",
  "pengetjek.journey.step2": "AI categorizes",
  "pengetjek.journey.step2Detail": "Only images/PDFs. Encrypted. No one sees it.",
  "pengetjek.journey.step3": "Deleted instantly",
  "pengetjek.journey.step3Detail": "Only categories sent back. The file is gone.",
  "pengetjek.journey.honest": "CSV files never leave your browser. Images and PDFs are sent encrypted to AI, analyzed on a locked server with no human access, and deleted right after. No login, no account, no tracking.",
  "pengetjek.cta.retry": "Upload new statement",
  "pengetjek.crossPromo.title": "Make your budget even more precise",
  "pengetjek.crossPromo.desc": "Upload your payslip to add exact income, tax details, and pension data to your budget.",
  "pengetjek.crossPromo.cta": "Upload payslip",
  "pengetjek.error.tooLarge": "File is too large (max 10 MB)",
  "pengetjek.error.invalidType": "File type not supported. Use PDF, image (JPG/PNG) or CSV.",
  "pengetjek.error.csvParseFailed": "Could not read the CSV file. Make sure it's a bank statement export.",
  "pengetjek.error.readFailed": "Could not read the statement — try a clearer image or CSV.",
  "pengetjek.result.hero.spent": "Total spending",
  "pengetjek.result.hero.transactions": "transactions",
  "pengetjek.result.pengeslugere.title": "Your money drains",
  "pengetjek.result.pengeslugere.subtitle": "This is where your money goes",
  "pengetjek.result.subscriptions.title": "Subscriptions found",
  "pengetjek.result.subscriptions.total": "You pay {amount} kr/mo in recurring subscriptions",
  "pengetjek.result.categories.title": "All categories",
  "pengetjek.result.budget.title": "Budget vs. reality",
  "pengetjek.result.cta": "Create a budget based on your actual spending",
  "pengetjek.result.truncated": "The statement was too long to read completely. Some transactions may be missing.",
  "pengetjek.result.transactions.toggle": "Show all transactions",
  "pengetjek.result.transactions.unknownDate": "Unknown date",
  "pengetjek.currency": "kr",
  "pengetjek.perMonth": "mo",
  "pengetjek.result.hero.income": "Income in period: {amount} kr",
  "pengetjek.result.hero.aboveAverage": "That's above the average for a Danish household",
  "pengetjek.result.hero.belowAverage": "That's below the average — well done!",
  "pengetjek.result.hero.nearAverage": "That's close to the average for a Danish household",
  "pengetjek.result.pengeslugere.ofSpending": "of your spending",
  "pengetjek.result.budget.budgeted": "Budget",
  "pengetjek.result.budget.actual": "Actual",
  "pengetjek.result.copied": "Copied!",
  "pengetjek.result.copyShare": "Copy summary",
  "pengetjek.share.title": "My Money Check — NemtBudget.nu",
  "pengetjek.share.period": "Period",
  "pengetjek.share.totalSpending": "Total spending",
  "pengetjek.share.transactionCount": "Number of transactions",
  "pengetjek.share.topCategories": "Top 5 categories",
  "pengetjek.share.subscriptions": "Subscriptions found",
};
