import { useMemo, useState, useEffect, useCallback, useRef } from "react";
import {
  Shield, Briefcase, MapPin, Calendar, Check, FileText, ArrowRight,
  Eye, EyeOff, AlertTriangle, Image, ExternalLink, TrendingUp, TrendingDown,
  Heart, Download, Clipboard, ChevronDown, ChevronUp, Info,
  Calculator, X, Share2,
} from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { useLocale } from "@/lib/locale";
import { formatKr } from "@/lib/budgetCalculator";
import {
  getDeductionLines, payslipToProfile,
  calculatePayslipInsights,
  type ExtractedPayslip,
} from "@/lib/payslipTypes";
import { exportPayslipCard, type CardPercentile } from "@/lib/payslipCard";
import { getSalaryPercentiles, getPercentileRank, submitSalaryObservation, getDSTFallback, DST_INDUSTRIES } from "@/lib/salaryData";
import type { ReconciliationDiagnostics } from "@/lib/payslipReconciler";
import type { BudgetProfile } from "@/lib/types";

interface Props {
  payslip: ExtractedPayslip;
  diagnostics?: ReconciliationDiagnostics | null;
  onCreateBudget: (partial: Partial<BudgetProfile>) => void;
}

/** Generate a text summary of the payslip for sharing (anonymous) */
function generatePayslipText(
  payslip: ExtractedPayslip,
  t: (key: string) => string,
  lc: string,
): string {
  const lines: string[] = [];

  lines.push(`📊 ${t("payslip.shareHeader")}${payslip.anonDescription ? ` — ${payslip.anonDescription}` : ""}`);
  lines.push("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

  const pad = (label: string) => " ".repeat(Math.max(1, 22 - label.length));
  const brutLabel = t("payslip.deductions.gross");
  lines.push(`${brutLabel}:${pad(brutLabel)}${formatKr(payslip.bruttolon, lc)}`);
  lines.push("───────────────────────────────");

  const deductions = getDeductionLines(payslip);
  for (const d of deductions) {
    const label = d.i18nKey.startsWith("__raw:") ? d.i18nKey.slice(6) : t(d.i18nKey);
    lines.push(`${label}:${pad(label)}-${formatKr(d.amount, lc)}`);
  }

  lines.push("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  const netLabel = t("payslip.deductions.net");
  lines.push(`${netLabel}:${pad(netLabel)}${formatKr(payslip.nettolon, lc)}`);
  lines.push("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

  const pct = payslip.bruttolon > 0 ? Math.round((payslip.nettolon / payslip.bruttolon) * 100) : 0;
  lines.push(`${t("payslip.shareKeepPct").replace("{pct}", String(pct))}`);

  lines.push("");
  lines.push(t("share.textFooter"));

  return lines.join("\n");
}

function canCopyImage(): boolean {
  return typeof ClipboardItem !== "undefined" && typeof navigator?.clipboard?.write === "function";
}

export function PayslipResult({ payslip, diagnostics, onCreateBudget }: Props) {
  const { t } = useI18n();
  const locale = useLocale();
  const lc = locale.currencyLocale;
  const [copied, setCopied] = useState(false);
  const [privacyMode, setPrivacyMode] = useState(false);
  const [shareStep, setShareStep] = useState<"idle" | "copying" | "ready" | "done">("idle");
  const [imageCopied, setImageCopied] = useState(false);
  const [includeBudget, setIncludeBudget] = useState(false);
  const [salaryData, setSalaryData] = useState<{
    percentile: number;
    median: number;
    p25: number;
    p75: number;
    industry: string;
    source: string;
  } | null>(null);
  const [selectedDSTIndustry, setSelectedDSTIndustry] = useState<string | null>(null);
  const [showAllIndustries, setShowAllIndustries] = useState(false);
  const [salaryConsent, setSalaryConsent] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [previewBlob, setPreviewBlob] = useState<Blob | null>(null);
  const [teaserUrl, setTeaserUrl] = useState<string | null>(null);
  const shareSectionRef = useRef<HTMLDivElement>(null);
  const autoGenerated = useRef(false);

  const hasBudget = useMemo(() => {
    try {
      return !!localStorage.getItem("nb-budget");
    } catch { return false; }
  }, []);

  const isAtypical = diagnostics?.isAtypicalMonth ?? false;
  const normalBrutto = isAtypical && diagnostics?.estimatedNormalBrutto
    ? diagnostics.estimatedNormalBrutto
    : payslip.bruttolon;

  const deductions = useMemo(() => getDeductionLines(payslip), [payslip]);
  const insights = useMemo(() => calculatePayslipInsights(payslip), [payslip]);
  const netPct = insights.retentionPct;

  // For atypical months, recalculate key metrics using normal brutto
  const annualGross = isAtypical ? normalBrutto * 12 : insights.annualGross;
  const pensionPctNormalized = normalBrutto > 0
    ? Math.round(((payslip.pensionEmployee + payslip.pensionEmployer) / normalBrutto) * 1000) / 10
    : insights.pensionPct;
  const pensionHealthNormalized: "low" | "ok" | "good" =
    pensionPctNormalized < 12 ? "low" : pensionPctNormalized >= 15 ? "good" : "ok";
  // For salary comparison, use normalBrutto
  const salaryCompBrutto = normalBrutto;

  const fmt = (v: number) => privacyMode ? `${payslip.bruttolon > 0 ? Math.round((v / payslip.bruttolon) * 100) : 0}%` : formatKr(v, lc);
  const fmtAbs = (v: number) => formatKr(v, lc);
  const tLabel = (key: string) => key.startsWith("__raw:") ? key.slice(6) : t(key);

  const isMobile = typeof window !== "undefined" && /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
  const isMac = typeof navigator !== "undefined" && /Mac/i.test(navigator.platform);

  // Fetch salary comparison data — use normalBrutto for atypical months
  useEffect(() => {
    if (!payslip.anonIndustry) {
      const dst = getDSTFallback("Alle");
      const pctRank = getPercentileRank(salaryCompBrutto, dst.p25, dst.median, dst.p75);
      setSalaryData({
        percentile: Math.round(pctRank),
        median: dst.median,
        p25: dst.p25,
        p75: dst.p75,
        industry: "Alle brancher",
        source: dst.source,
      });
      return;
    }

    getSalaryPercentiles(payslip.anonIndustry, payslip.anonRegion).then((data) => {
      if (data && data.sample_size >= 5) {
        const pctRank = getPercentileRank(salaryCompBrutto, data.gross_p25, data.gross_median, data.gross_p75);
        setSalaryData({
          percentile: Math.round(pctRank),
          median: Math.round(data.gross_median),
          p25: Math.round(data.gross_p25),
          p75: Math.round(data.gross_p75),
          industry: payslip.anonIndustry!,
          source: "nemtbudget.nu",
        });
      } else {
        const dst = getDSTFallback(payslip.anonIndustry!);
        const pctRank = getPercentileRank(salaryCompBrutto, dst.p25, dst.median, dst.p75);
        setSalaryData({
          percentile: Math.round(pctRank),
          median: dst.median,
          p25: dst.p25,
          p75: dst.p75,
          industry: payslip.anonIndustry!,
          source: dst.source,
        });
      }
    });
  }, [payslip, salaryCompBrutto]);

  // Handle DST industry selector change
  useEffect(() => {
    if (!selectedDSTIndustry) return;
    const dst = getDSTFallback(selectedDSTIndustry);
    const pctRank = getPercentileRank(salaryCompBrutto, dst.p25, dst.median, dst.p75);
    setSalaryData({
      percentile: Math.round(pctRank),
      median: dst.median,
      p25: dst.p25,
      p75: dst.p75,
      industry: selectedDSTIndustry,
      source: dst.source,
    });
  }, [selectedDSTIndustry, salaryCompBrutto]);

  // Contribute anonymized salary data only after explicit consent
  useEffect(() => {
    if (!salaryConsent || !payslip.anonIndustry || !payslip.anonRegion || isAtypical) return;
    submitSalaryObservation({
      industry: payslip.anonIndustry,
      region: payslip.anonRegion,
      gross_monthly: payslip.bruttolon,
      net_monthly: payslip.nettolon,
    });
  }, [payslip, isAtypical, salaryConsent]);

  const handleCopyText = async () => {
    const text = generatePayslipText(payslip, t, lc);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  };

  // Build optional sankey canvas for budget inclusion
  const buildSankeyCanvas = useCallback(async (): Promise<HTMLCanvasElement | undefined> => {
    if (!includeBudget) return undefined;
    const sankeyEl = document.querySelector<SVGSVGElement>("#sankey-svg");
    if (!sankeyEl) return undefined;
    try {
      const svgData = new XMLSerializer().serializeToString(sankeyEl);
      const img = new window.Image();
      const blob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      await new Promise<void>((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = () => { URL.revokeObjectURL(url); reject(); };
        img.src = url;
      });
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      canvas.getContext("2d")!.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);
      return canvas;
    } catch { return undefined; }
  }, [includeBudget]);

  const cardPercentile: CardPercentile | undefined = salaryData
    ? { rank: 100 - salaryData.percentile, industry: salaryData.industry }
    : undefined;

  // Auto-generate teaser card on mount (fires once when salaryData resolves)
  useEffect(() => {
    if (autoGenerated.current || !salaryData) return;
    autoGenerated.current = true;
    const pctl: CardPercentile = { rank: 100 - salaryData.percentile, industry: salaryData.industry };
    exportPayslipCard(payslip, t, lc, "blob", undefined, pctl).then((result) => {
      if (result instanceof Blob) {
        const url = URL.createObjectURL(result);
        setTeaserUrl(url);
        // Also pre-fill the share preview so it's ready
        setPreviewUrl(url);
        setPreviewBlob(result);
        setShareStep("ready");
      }
    });
  }, [salaryData, payslip, t, lc]);

  // Generate preview
  const handleStep1 = useCallback(async () => {
    setShareStep("copying");
    const sankeyCanvas = await buildSankeyCanvas();
    const result = await exportPayslipCard(payslip, t, lc, "blob", sankeyCanvas, cardPercentile);
    if (result instanceof Blob) {
      if (previewUrl) URL.revokeObjectURL(previewUrl);
      const url = URL.createObjectURL(result);
      setPreviewUrl(url);
      setPreviewBlob(result);
      setShareStep("ready");
    } else {
      setShareStep("idle");
    }
  }, [payslip, t, lc, cardPercentile, buildSankeyCanvas, previewUrl]);

  // Confirm share: copy to clipboard or download
  const handleConfirmShare = useCallback(async () => {
    if (!previewBlob) return;
    const useClipboard = !isMobile && canCopyImage();
    if (useClipboard) {
      try {
        await navigator.clipboard.write([new ClipboardItem({ "image/png": previewBlob })]);
        setImageCopied(true);
        setTimeout(() => setImageCopied(false), 2500);
        return;
      } catch { /* fall through to download */ }
    }
    const a = document.createElement("a");
    a.href = URL.createObjectURL(previewBlob);
    a.download = "min-lonseddel-nemtbudget.png";
    a.click();
    URL.revokeObjectURL(a.href);
    setImageCopied(true);
    setTimeout(() => setImageCopied(false), 2500);
  }, [previewBlob, isMobile]);

  const handleClosePreview = useCallback(() => {
    if (previewUrl) URL.revokeObjectURL(previewUrl);
    setPreviewUrl(null);
    setPreviewBlob(null);
    setShareStep("idle");
    setImageCopied(false);
  }, [previewUrl]);

  // Reddit
  const redditTitle = `${payslip.anonDescription || "Min lønseddel"} — ${Math.round(netPct)}% udbetalt | nemtbudget.nu`;
  const subreddits = [
    { name: "r/dkloenseddel", sub: "dkloenseddel" },
    { name: "r/dkfinance", sub: "dkfinance" },
  ];
  const [selectedSub, setSelectedSub] = useState(0);
  const redditUrl = `https://www.reddit.com/r/${subreddits[selectedSub].sub}/submit?type=IMAGE&title=${encodeURIComponent(redditTitle)}`;

  const handleStep2 = useCallback(() => {
    const win = window.open(redditUrl, "_blank", "noopener,noreferrer");
    if (win) {
      setShareStep("done");
      setTimeout(() => setShareStep("idle"), 5000);
    }
  }, [redditUrl]);

  const handleCreateBudget = () => {
    onCreateBudget(payslipToProfile(payslip));
  };

  return (
    <div className="space-y-4">
      {/* ── SECTION 1: Hero ── */}
      <div className="rounded-xl border border-border bg-card overflow-hidden">
        <div className="p-5 text-center">
          <div className="flex items-center justify-end mb-3">
            <button
              onClick={() => setPrivacyMode((p) => !p)}
              className={`inline-flex items-center gap-1 px-2 py-1 rounded-md text-[10px] font-semibold transition-all ${privacyMode ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:bg-muted/80"}`}
              title={privacyMode ? "Vis beløb" : "Skjul beløb"}
            >
              {privacyMode ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
              <span>{privacyMode ? "%" : "kr"}</span>
            </button>
          </div>

          <p className="text-xs text-muted-foreground mb-1">{t("payslip.hero.youKeep")}</p>
          <div className="text-4xl font-black tracking-tight text-foreground">{Math.round(netPct)}%</div>
          <p className="text-lg font-bold text-foreground mt-1">
            {fmt(payslip.nettolon)} <span className="text-sm font-normal text-muted-foreground">{t("payslip.hero.paidOut")}</span>
          </p>
          {isAtypical ? (
            <>
              <div className="mt-3 inline-flex items-center gap-1.5 rounded-full bg-blue-100 dark:bg-blue-900/30 px-3 py-1 text-xs text-blue-700 dark:text-blue-400">
                <Info className="w-3 h-3" />
                {t("payslip.hero.atypicalMonth")}
              </div>
              <p className="text-[10px] text-muted-foreground/60 mt-1.5">
                {t("payslip.hero.normalGross").replace("{amount}", fmtAbs(normalBrutto)).replace("{annual}", fmtAbs(annualGross))}
              </p>
            </>
          ) : (
            <>
              <div className="mt-3 inline-flex items-center gap-1.5 rounded-full bg-muted/50 px-3 py-1 text-xs text-muted-foreground">
                <Calculator className="w-3 h-3" />
                {t("payslip.hero.annual").replace("{amount}", fmtAbs(insights.annualNet))}
              </div>
              <p className="text-[10px] text-muted-foreground/60 mt-1.5">
                {t("payslip.hero.gross").replace("{monthly}", fmtAbs(payslip.bruttolon)).replace("{annual}", fmtAbs(insights.annualGross))}
              </p>
            </>
          )}

          {/* Pay components */}
          {payslip.payComponents.length > 1 && (
            <div className="mt-3 space-y-0.5">
              {payslip.payComponents.map((pc, i) => (
                <div key={i} className="flex justify-between text-[10px] max-w-[200px] mx-auto">
                  <span className="text-muted-foreground">{pc.name}</span>
                  <span className="text-foreground/80 tabular-nums">{fmtAbs(pc.amount)}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Context chips */}
        {(payslip.anonJobTitle || payslip.anonIndustry || payslip.anonRegion || payslip.payPeriod) && (
          <div className="flex flex-wrap gap-1.5 px-5 pb-4 justify-center">
            {payslip.anonJobTitle && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-primary/10 text-primary text-[10px] font-medium">
                <Briefcase className="w-2.5 h-2.5" />{payslip.anonJobTitle}
              </span>
            )}
            {payslip.anonIndustry && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-[10px] font-medium dark:bg-blue-900/30 dark:text-blue-300">
                {payslip.anonIndustry}
              </span>
            )}
            {payslip.anonRegion && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-muted text-muted-foreground text-[10px] font-medium">
                <MapPin className="w-2.5 h-2.5" />{payslip.anonRegion}
              </span>
            )}
            {payslip.payPeriod && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-muted text-muted-foreground text-[10px] font-medium">
                <Calendar className="w-2.5 h-2.5" />{payslip.payPeriod}
              </span>
            )}
          </div>
        )}
      </div>

      {/* ── TEASER: Mini card preview ── */}
      {teaserUrl && (
        <div
          className="rounded-xl border border-border bg-card overflow-hidden cursor-pointer group transition-all hover:border-[#FF4500]/40 hover:shadow-md"
          onClick={() => shareSectionRef.current?.scrollIntoView({ behavior: "smooth", block: "center" })}
        >
          <div className="flex items-center gap-3 p-3">
            <div className="w-20 h-14 rounded-lg overflow-hidden border border-border/50 shrink-0 bg-[#1a1d23]">
              <img src={teaserUrl} alt="" className="w-full h-full object-cover object-top" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-xs font-semibold text-foreground">{t("payslip.teaser.title")}</p>
              <p className="text-[10px] text-muted-foreground mt-0.5">{t("payslip.teaser.subtitle")}</p>
            </div>
            <div className="shrink-0">
              <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-[#FF4500] text-white text-xs font-semibold group-hover:bg-[#FF4500]/90 transition-colors">
                <Share2 className="w-3 h-3" />
                Del
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── SECTION 2: Deduction breakdown ── */}
      <div className="rounded-xl border border-border bg-card overflow-hidden">
        <div className="px-4 py-3 border-b border-border bg-muted/30">
          <span className="text-sm font-semibold">{t("payslip.section.breakdown")}</span>
        </div>

        {/* Stacked bar */}
        <div className="px-4 pt-3 pb-1">
          <div className="h-5 rounded-full overflow-hidden flex bg-muted/30">
            {deductions.map((d) => {
              const w = payslip.bruttolon > 0 ? (d.amount / payslip.bruttolon) * 100 : 0;
              return <div key={d.key} style={{ width: `${w}%`, backgroundColor: d.color }} className="h-full" />;
            })}
            <div className="h-full bg-emerald-500 flex-1" />
          </div>
        </div>

        {/* Deduction rows */}
        <div className="px-4 py-3 space-y-1">
          {deductions.map((d) => {
            const rawPct = payslip.bruttolon > 0 ? (d.amount / payslip.bruttolon) * 100 : 0;
            const pctLabel = rawPct > 0 && rawPct < 1 ? "<1" : String(Math.round(rawPct));
            const isOther = d.key === "other";

            return (
              <div key={d.key}>
                <div className="flex items-center justify-between py-1.5">
                  <div className="flex items-center gap-2 min-w-0 flex-1">
                    <div className="w-2 h-2 rounded-sm shrink-0" style={{ backgroundColor: d.color }} />
                    <span className="text-xs text-foreground">{tLabel(d.i18nKey)}</span>
                    {d.key === "aSkat" && payslip.traekkort > 0 && (
                      <span className="text-[10px] text-muted-foreground">({payslip.traekkort}%)</span>
                    )}
                  </div>
                  <div className="text-right shrink-0 ml-2">
                    <span className="text-xs font-semibold tabular-nums">-{fmt(d.amount)}</span>
                    <span className="text-[10px] text-muted-foreground/50 ml-1.5">{pctLabel}%</span>
                  </div>
                </div>

                {d.key === "pension" && payslip.pensionEmployer > 0 && (
                  <div className="ml-4 mb-1 flex items-center gap-1.5 text-[10px] text-primary/80">
                    <Heart className="w-2.5 h-2.5" />
                    <span>+ {fmtAbs(payslip.pensionEmployer)} fra arbejdsgiver</span>
                  </div>
                )}

                {d.key === "aSkat" && payslip.personfradrag > 0 && (
                  <div className="ml-4 mb-1 text-[10px] text-muted-foreground">
                    {t("payslip.tax.personfradrag")}: {fmtAbs(payslip.personfradrag)} kr/md
                  </div>
                )}

                {isOther && payslip.otherDeductions.length > 0 && (
                  <div className="ml-4 mb-1 space-y-0.5">
                    {payslip.otherDeductions.map((od, i) => (
                      <div key={i} className="flex justify-between text-[10px] text-muted-foreground">
                        <span>{od.name}</span>
                        <span className="tabular-nums">-{fmtAbs(od.amount)}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Net row */}
        <div className="flex items-center justify-between px-4 py-3 bg-emerald-50 dark:bg-emerald-950/20 border-t border-border">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-sm bg-emerald-500 shrink-0" />
            <span className="text-sm font-semibold text-emerald-700 dark:text-emerald-400">{t("payslip.deductions.net")}</span>
          </div>
          <div className="text-right">
            <span className="text-sm font-bold text-emerald-700 dark:text-emerald-400 tabular-nums">{fmt(payslip.nettolon)}</span>
            <span className="text-[10px] text-emerald-600/60 dark:text-emerald-400/60 ml-1.5">{Math.round(netPct)}%</span>
          </div>
        </div>
      </div>

      {/* ── SECTION 3: Insights ── */}
      <div className="rounded-xl border border-border bg-card overflow-hidden">
        <div className="px-4 py-3 border-b border-border bg-muted/30 flex items-center gap-2">
          <Info className="w-3.5 h-3.5 text-primary" />
          <span className="text-sm font-semibold">{t("payslip.section.insights")}</span>
        </div>
        <div className="p-4 space-y-3">
          {/* Effective tax rate */}
          <div className="rounded-lg bg-background/50 border border-border/30 p-3">
            <div className="flex items-center gap-1.5 mb-1.5 text-blue-600 dark:text-blue-400">
              <TrendingDown className="w-3.5 h-3.5" />
              <span className="text-xs font-semibold">{t("payslip.insight.effectiveTax")}</span>
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              {t("payslip.insight.effectiveTaxDetail")
                .replace("{marginal}", String(insights.marginalTaxRate || "~37"))
                .replace("{effective}", String(insights.effectiveTaxRate))
                .replace("{personfradrag}", fmtAbs(insights.personfradragMonthly))}
            </p>
          </div>

          {/* Pension health — use normalized values for atypical months */}
          <div className="rounded-lg bg-background/50 border border-border/30 p-3">
            <div className={`flex items-center gap-1.5 mb-1.5 ${
              pensionHealthNormalized === "low" ? "text-amber-500" : pensionHealthNormalized === "good" ? "text-emerald-500" : "text-blue-600 dark:text-blue-400"
            }`}>
              <Heart className="w-3.5 h-3.5" />
              <span className="text-xs font-semibold">{t("payslip.insight.pensionTitle")}</span>
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              {t("payslip.insight.pensionDetail")
                .replace("{pct}", String(pensionPctNormalized))
                .replace("{employee}", fmtAbs(payslip.pensionEmployee))
                .replace("{employer}", fmtAbs(payslip.pensionEmployer))}
            </p>
            {pensionHealthNormalized === "low" && (
              <p className="text-[10px] text-amber-600 dark:text-amber-400 mt-1 font-medium">{t("payslip.insight.pensionLow")}</p>
            )}
            {pensionHealthNormalized === "good" && (
              <p className="text-[10px] text-emerald-600 dark:text-emerald-400 mt-1 font-medium">{t("payslip.insight.pensionGood")}</p>
            )}
          </div>

          {/* Annual projection — use normalized values for atypical months */}
          <div className="rounded-lg bg-background/50 border border-border/30 p-3">
            <div className="flex items-center gap-1.5 mb-1.5 text-primary">
              <Calculator className="w-3.5 h-3.5" />
              <span className="text-xs font-semibold">{isAtypical ? t("payslip.insight.annualTitleNormal") : t("payslip.insight.annualTitle")}</span>
            </div>
            {isAtypical ? (
              <p className="text-xs text-muted-foreground leading-relaxed">
                {t("payslip.insight.annualNormalDetail")
                  .replace("{gross}", fmtAbs(annualGross))
                  .replace("{monthly}", fmtAbs(normalBrutto))}
              </p>
            ) : (
              <p className="text-xs text-muted-foreground leading-relaxed">
                {t("payslip.insight.annualDetail")
                  .replace("{gross}", fmtAbs(insights.annualGross))
                  .replace("{deductions}", fmtAbs(insights.annualDeductions))
                  .replace("{net}", fmtAbs(insights.annualNet))}
              </p>
            )}
          </div>
        </div>
      </div>

      {/* ── SECTION 3.5: Hvad ser SKAT? ── */}
      {insights.amGrundlag < payslip.bruttolon && (
        <div className="rounded-xl border border-border bg-card overflow-hidden">
          <div className="px-4 py-3 border-b border-border bg-muted/30 flex items-center gap-2">
            <FileText className="w-3.5 h-3.5 text-primary" />
            <span className="text-sm font-semibold">{t("payslip.section.skatView")}</span>
          </div>
          <div className="p-4 space-y-3">
            <p className="text-xs text-muted-foreground leading-relaxed">{t("payslip.skat.intro")}</p>

            {/* Waterfall flow */}
            <div className="rounded-lg bg-background/50 border border-border/30 p-3">
              {/* Start: Bruttoløn */}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-emerald-500 shrink-0" />
                  <span className="text-xs font-medium text-foreground">{t("payslip.skat.step.brutto")}</span>
                </div>
                <span className="text-xs font-semibold text-foreground tabular-nums">{fmt(payslip.bruttolon)}</span>
              </div>

              {/* Subtract: Pension */}
              {payslip.pensionEmployee > 0 && (
                <div className="flex items-center justify-between ml-1 border-l-2 border-red-300 dark:border-red-800 pl-3 py-1.5">
                  <span className="text-[11px] text-muted-foreground">− {t("payslip.skat.step.pension")}</span>
                  <span className="text-[11px] text-red-600 dark:text-red-400 tabular-nums font-medium">−{fmt(payslip.pensionEmployee)}</span>
                </div>
              )}

              {/* Subtract: ATP */}
              {payslip.atp > 0 && (
                <div className="flex items-center justify-between ml-1 border-l-2 border-red-300 dark:border-red-800 pl-3 py-1.5">
                  <span className="text-[11px] text-muted-foreground">− {t("payslip.skat.step.atp")}</span>
                  <span className="text-[11px] text-red-600 dark:text-red-400 tabular-nums font-medium">−{fmt(payslip.atp)}</span>
                </div>
              )}

              {/* Subtotal: AM-grundlag */}
              <div className="flex items-center justify-between mt-1 pt-1.5 border-t border-border/50">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-sm bg-blue-500 shrink-0" />
                  <span className="text-xs font-semibold text-blue-700 dark:text-blue-300">{t("payslip.skat.step.amGrundlag")}</span>
                </div>
                <span className="text-xs font-bold text-blue-700 dark:text-blue-300 tabular-nums">{fmt(insights.amGrundlag)}</span>
              </div>
              <p className="text-[10px] text-blue-600/60 dark:text-blue-400/50 ml-4 mt-0.5">{t("payslip.skat.step.amGrundlagNote")}</p>

              {/* Subtract: AM-bidrag */}
              <div className="flex items-center justify-between ml-1 border-l-2 border-red-300 dark:border-red-800 pl-3 py-1.5 mt-1">
                <span className="text-[11px] text-muted-foreground">− {t("payslip.skat.step.amBidrag")}</span>
                <span className="text-[11px] text-red-600 dark:text-red-400 tabular-nums font-medium">−{fmt(payslip.amBidrag)}</span>
              </div>

              {/* Result: A-indkomst */}
              <div className="flex items-center justify-between mt-1 pt-1.5 border-t border-border/50">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-sm bg-primary shrink-0" />
                  <span className="text-xs font-semibold text-primary">{t("payslip.skat.step.aIndkomst")}</span>
                </div>
                <span className="text-xs font-bold text-primary tabular-nums">{fmt(insights.aIndkomst)}</span>
              </div>
              <p className="text-[10px] text-primary/50 ml-4 mt-0.5">{t("payslip.skat.step.aIndkomstNote")}</p>
            </div>

            {/* Annual comparison */}
            <div className="rounded-lg bg-background/50 border border-border/30 p-3 space-y-1.5">
              <div className="flex items-center gap-1.5 mb-1">
                <Calculator className="w-3 h-3 text-primary" />
                <span className="text-xs font-semibold text-foreground">{t("payslip.skat.annual.title")}</span>
              </div>
              <p className="text-[11px] text-muted-foreground">
                {t("payslip.skat.annual.naive").replace("{naive}", fmtAbs(annualGross))}
              </p>
              <p className="text-[11px] font-medium text-foreground">
                {t("payslip.skat.annual.real").replace("{real}", fmtAbs(isAtypical ? (normalBrutto - payslip.pensionEmployee - payslip.atp) * 12 : insights.annualAmGrundlag))}
              </p>
              <p className="text-[10px] text-amber-600 dark:text-amber-400 font-medium">
                {t("payslip.skat.annual.diff").replace("{diff}", fmtAbs(annualGross - (isAtypical ? (normalBrutto - payslip.pensionEmployee - payslip.atp) * 12 : insights.annualAmGrundlag)))}
              </p>
            </div>

            {/* Opsparede beløb (conditional) */}
            {insights.hasOpsparingsNote && (
              <div className="rounded-lg bg-amber-50/50 dark:bg-amber-950/10 border border-amber-200/30 dark:border-amber-800/30 p-3">
                <div className="flex items-center gap-1.5 mb-1">
                  <AlertTriangle className="w-3 h-3 text-amber-500" />
                  <span className="text-xs font-semibold text-amber-700 dark:text-amber-300">{t("payslip.skat.opsparing.title")}</span>
                </div>
                <p className="text-[11px] text-amber-700/80 dark:text-amber-300/70 leading-relaxed">
                  {t("payslip.skat.opsparing.detail").replace("{amount}", fmtAbs(insights.opsparetMonthly))}
                </p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Warnings ── */}
      {payslip.warnings.length > 0 && (
        <div className="flex items-start gap-2 p-3 rounded-lg bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800">
          <AlertTriangle className="w-3.5 h-3.5 text-amber-500 mt-0.5 shrink-0" />
          <div className="space-y-0.5">
            {payslip.warnings.map((w, i) => (
              <p key={i} className="text-[10px] text-amber-700 dark:text-amber-300">{w}</p>
            ))}
          </div>
        </div>
      )}

      {/* ── SECTION 3.7: Hidden employer benefits ── */}
      {(payslip.pensionEmployer > 0 || (payslip.sundhedsforsikring && payslip.sundhedsforsikring > 0) || (payslip.fritvalgKonto && payslip.fritvalgKonto > 0)) && (
        <div className="rounded-xl border border-border bg-card overflow-hidden">
          <div className="px-4 py-3 border-b border-border bg-emerald-50/50 dark:bg-emerald-950/20 flex items-center gap-2">
            <Heart className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
            <span className="text-sm font-semibold">{t("payslip.section.hiddenBenefits")}</span>
          </div>
          <div className="p-4 space-y-3">
            <p className="text-xs text-muted-foreground leading-relaxed">{t("payslip.benefits.intro")}</p>
            {(() => {
              const benefits: { label: string; monthly: number; annual: number }[] = [];
              if (payslip.pensionEmployer > 0) benefits.push({ label: t("payslip.benefits.pension"), monthly: payslip.pensionEmployer, annual: payslip.pensionEmployer * 12 });
              if (payslip.sundhedsforsikring && payslip.sundhedsforsikring > 0) benefits.push({ label: t("payslip.benefits.health"), monthly: payslip.sundhedsforsikring, annual: payslip.sundhedsforsikring * 12 });
              if (payslip.fritvalgKonto && payslip.fritvalgKonto > 0) benefits.push({ label: t("payslip.benefits.fritvalg"), monthly: payslip.fritvalgKonto, annual: payslip.fritvalgKonto * 12 });
              const totalAnnual = benefits.reduce((s, b) => s + b.annual, 0);

              return (
                <>
                  <div className="space-y-2">
                    {benefits.map((b, i) => (
                      <div key={i} className="flex items-center justify-between py-1.5 px-3 rounded-lg bg-emerald-50/50 dark:bg-emerald-950/10">
                        <span className="text-xs text-foreground">{b.label}</span>
                        <div className="text-right">
                          <span className="text-xs font-semibold tabular-nums text-emerald-700 dark:text-emerald-400">{fmtAbs(b.monthly)} {t("perMonth")}</span>
                          <span className="text-[10px] text-muted-foreground ml-1.5">({fmtAbs(b.annual)}/år)</span>
                        </div>
                      </div>
                    ))}
                  </div>
                  <div className="flex items-center justify-between px-3 py-2 rounded-lg bg-emerald-100 dark:bg-emerald-900/30 border border-emerald-200 dark:border-emerald-800">
                    <span className="text-xs font-semibold text-emerald-800 dark:text-emerald-300">{t("payslip.benefits.total")}</span>
                    <span className="text-sm font-bold text-emerald-700 dark:text-emerald-400 tabular-nums">{fmtAbs(totalAnnual)} kr/år</span>
                  </div>
                  {payslip.sundhedsforsikring && payslip.sundhedsforsikring > 0 && (
                    <p className="text-[10px] text-muted-foreground leading-relaxed">
                      {t("payslip.benefits.healthHint")}
                    </p>
                  )}
                </>
              );
            })()}
          </div>
        </div>
      )}

      {/* ── SECTION 4: Salary comparison ── */}
      <div className="rounded-xl border border-border bg-card overflow-hidden">
        <div className="px-4 py-3 border-b border-border bg-muted/30">
          <div className="flex items-center gap-2">
            <TrendingUp className="w-3.5 h-3.5 text-primary" />
            <span className="text-sm font-semibold">{t("salary.comparison")}</span>
          </div>
          {salaryData?.source?.startsWith("DST") && (
            <p className="text-[9px] text-muted-foreground/60 mt-0.5">{t("payslip.salary.dstSource")}</p>
          )}
        </div>

        {/* Industry pills */}
        <div className="px-4 pt-3">
          <div className="flex flex-wrap gap-1.5">
            {(showAllIndustries ? DST_INDUSTRIES : DST_INDUSTRIES.slice(0, 8)).map((ind) => (
              <button
                key={ind}
                onClick={() => setSelectedDSTIndustry(ind)}
                className={`px-2 py-0.5 rounded-full text-[10px] transition-colors ${
                  (selectedDSTIndustry || salaryData?.industry || "") === ind
                    ? "bg-primary text-primary-foreground font-semibold"
                    : "bg-muted/50 text-muted-foreground hover:bg-muted"
                }`}
              >
                {ind}
              </button>
            ))}
            <button
              onClick={() => setShowAllIndustries(!showAllIndustries)}
              className="px-2 py-0.5 rounded-full text-[10px] bg-muted/30 text-muted-foreground hover:bg-muted flex items-center gap-0.5"
            >
              {showAllIndustries ? <><ChevronUp className="w-2.5 h-2.5" />{t("payslip.salary.showFewer")}</> : <><ChevronDown className="w-2.5 h-2.5" />{t("payslip.salary.showAll")}</>}
            </button>
          </div>
        </div>

        {salaryData ? (
          <div className="px-4 py-4 space-y-3">
            <div className="flex items-baseline justify-between">
              <span className="text-xs text-muted-foreground">
                {t("salary.percentile").replace("{pct}", String(salaryData.percentile))}
              </span>
              <span className="text-[10px] text-muted-foreground/60">
                {salaryData.percentile > 55
                  ? t("salary.aboveMedian")
                  : salaryData.percentile < 45
                    ? t("salary.belowMedian")
                    : t("salary.atMedian")}
              </span>
            </div>
            <div className="relative h-6 rounded-full bg-muted overflow-hidden">
              <div className="absolute top-0 h-full bg-primary/15 rounded-full" style={{ left: "25%", width: "50%" }} />
              <div className="absolute top-0 h-full w-0.5 bg-muted-foreground/30" style={{ left: "50%" }} />
              <div
                className="absolute top-1 bottom-1 w-3 rounded-full bg-primary shadow-sm transition-all duration-700"
                style={{ left: `calc(${Math.min(95, Math.max(5, salaryData.percentile))}% - 6px)` }}
              />
            </div>
            <div className="flex justify-between text-[9px] text-muted-foreground/50 tabular-nums">
              <span>P25: {fmtAbs(salaryData.p25)}</span>
              <span>Median ({salaryData.industry}): {fmtAbs(salaryData.median)}</span>
              <span>P75: {fmtAbs(salaryData.p75)}</span>
            </div>

            <div className="pt-1 space-y-0.5">
              <div className="flex justify-between text-xs">
                <span className="text-muted-foreground">{t("payslip.salary.yourGross")}{isAtypical ? ` (${t("payslip.salary.normalMonth")})` : ""}</span>
                <span className="font-semibold tabular-nums">{fmtAbs(salaryCompBrutto)}/md</span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-muted-foreground">Median</span>
                <span className="text-muted-foreground tabular-nums">{fmtAbs(salaryData.median)}/md</span>
              </div>
              {salaryCompBrutto !== salaryData.median && (
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">{t("payslip.salary.difference")}</span>
                  <span className={`font-semibold flex items-center gap-0.5 ${salaryCompBrutto > salaryData.median ? "text-emerald-600 dark:text-emerald-400" : "text-amber-600 dark:text-amber-400"}`}>
                    {salaryCompBrutto > salaryData.median ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}
                    {salaryCompBrutto > salaryData.median ? "+" : ""}{fmtAbs(salaryCompBrutto - salaryData.median)}/md
                  </span>
                </div>
              )}
            </div>
          </div>
        ) : (
          <div className="px-4 py-4">
            <div className="h-6 rounded-full bg-muted animate-pulse" />
          </div>
        )}
      </div>

      {/* Salary observation opt-in */}
      {payslip.anonIndustry && payslip.anonRegion && !isAtypical && (
        <div className="flex items-center gap-3 p-3 rounded-lg bg-muted/50 border border-border/50">
          <input
            type="checkbox"
            id="salary-consent"
            checked={salaryConsent}
            onChange={(e) => setSalaryConsent(e.target.checked)}
            className="rounded border-border text-primary focus:ring-primary/30 w-4 h-4 shrink-0"
          />
          <label htmlFor="salary-consent" className="text-[11px] text-muted-foreground leading-relaxed cursor-pointer">
            {t("salary.consentLabel")}
          </label>
        </div>
      )}

      {/* ── SECTION 5: Private info ── */}
      {(payslip.employerName || payslip.municipality) && (
        <div className="flex items-start gap-2 p-3 rounded-lg bg-muted/50 border border-border/50">
          <Shield className="w-3.5 h-3.5 text-muted-foreground mt-0.5 shrink-0" />
          <div>
            <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-1">{t("payslip.privateInfo")}</p>
            <div className="flex flex-wrap gap-x-4 gap-y-0.5 text-xs text-muted-foreground">
              {payslip.employerName && <span>{t("payslip.result.employer")}: {payslip.employerName}</span>}
              {payslip.municipality && <span>{t("payslip.result.municipality")}: {payslip.municipality}</span>}
              {payslip.payrollSystem && <span>{t("payslip.result.payrollSystem")}: {payslip.payrollSystem}</span>}
            </div>
            <p className="text-[9px] text-muted-foreground/60 mt-1">{t("payslip.privateNote")}</p>
          </div>
        </div>
      )}

      {/* ── SECTION 6: Share to Reddit ── */}
      <div ref={shareSectionRef} className="rounded-xl border border-border bg-card overflow-hidden">
        <div className="px-4 py-3 border-b border-border bg-gradient-to-r from-[#FF4500]/10 to-transparent">
          <div className="flex items-center gap-2">
            <Image className="w-3.5 h-3.5 text-[#FF4500]" />
            <span className="text-sm font-semibold">{t("payslip.share.sectionTitle")}</span>
          </div>
        </div>
        <div className="px-4 py-4 space-y-3">
          {hasBudget && (
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={includeBudget}
                onChange={(e) => { setIncludeBudget(e.target.checked); setShareStep("idle"); handleClosePreview(); }}
                className="rounded border-border text-primary focus:ring-primary/30 w-3.5 h-3.5"
              />
              <span className="text-xs text-muted-foreground">{t("payslip.share.includeBudget")}</span>
            </label>
          )}

          {/* Preview image */}
          {previewUrl && (
            <div className="space-y-2">
              <div className="relative rounded-lg overflow-hidden border border-border bg-black/50">
                <button
                  onClick={handleClosePreview}
                  className="absolute top-2 right-2 z-10 p-1 rounded-full bg-black/50 text-white/70 hover:text-white transition-colors"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
                <img src={previewUrl} alt="Preview" className="w-full" />
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handleConfirmShare}
                  className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-semibold transition-all ${
                    imageCopied
                      ? "bg-emerald-600 text-white"
                      : "bg-primary text-primary-foreground hover:bg-primary/90"
                  }`}
                >
                  {imageCopied ? (
                    <><Check className="w-4 h-4" />{isMobile ? t("payslip.imageDownloaded") : t("payslip.imageCopied")}</>
                  ) : (
                    <>{isMobile ? <Download className="w-4 h-4" /> : <Clipboard className="w-4 h-4" />}{isMobile ? t("payslip.downloadImage") : t("payslip.share.step1")}</>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* Generate preview button */}
          {!previewUrl && (
            <button
              onClick={handleStep1}
              disabled={shareStep === "copying"}
              className="flex items-center justify-center gap-2 w-full px-4 py-3 rounded-lg text-sm font-semibold bg-primary text-primary-foreground hover:bg-primary/90 transition-all"
            >
              {shareStep === "copying" ? (
                <><div className="w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin" />Genererer billede...</>
              ) : (
                <><Eye className="w-4 h-4" />Se delingsbillede</>
              )}
            </button>
          )}

          {/* Reddit buttons */}
          <div className="space-y-2">
            <div className="flex gap-1.5">
              {subreddits.map((sr, i) => (
                <button
                  key={sr.sub}
                  onClick={() => setSelectedSub(i)}
                  className={`flex-1 px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                    selectedSub === i
                      ? "bg-[#FF4500]/10 text-[#FF4500] border border-[#FF4500]/30"
                      : "bg-muted/50 text-muted-foreground hover:bg-muted"
                  }`}
                >
                  {sr.name}
                </button>
              ))}
            </div>
            <button
              onClick={() => { handleConfirmShare(); handleStep2(); }}
              disabled={!previewBlob}
              className={`flex items-center justify-center gap-2 w-full px-4 py-3 rounded-lg text-sm font-semibold transition-all ${
                previewBlob
                  ? "bg-[#FF4500] text-white hover:bg-[#FF4500]/90 shadow-sm"
                  : "bg-muted text-muted-foreground/50 cursor-not-allowed"
              }`}
            >
              <ExternalLink className="w-4 h-4" />{t("payslip.share.step2")} → {subreddits[selectedSub].name}
            </button>
          </div>
          {previewBlob && !isMobile && (
            <p className="text-[10px] text-muted-foreground text-center">
              {t("payslip.share.step2Hint").replace("Ctrl+V", isMac ? "⌘V" : "Ctrl+V")}
            </p>
          )}
        </div>
      </div>

      {/* ── SECTION 7: Actions ── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
        <button
          onClick={handleCopyText}
          className="flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-lg text-xs font-semibold border border-border hover:bg-muted transition-colors"
        >
          {copied ? (
            <><Check className="w-3.5 h-3.5" />{t("share.copiedText")}</>
          ) : (
            <><FileText className="w-3.5 h-3.5" />{t("payslip.cta.share")}</>
          )}
        </button>
        <button
          onClick={handleCreateBudget}
          className="flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-lg text-xs font-semibold bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
        >
          {t("payslip.cta.budget")}
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>

      {/* Cross-promote pengetjek for the combo effect */}
      <div className="rounded-xl border border-dashed border-primary/30 bg-primary/5 p-4 text-center space-y-2">
        <p className="text-xs font-semibold text-foreground">{t("payslip.crossPromo.title")}</p>
        <p className="text-[10px] text-muted-foreground leading-relaxed">{t("payslip.crossPromo.desc")}</p>
        <a
          href="/pengetjek"
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-primary hover:bg-primary/10 transition-colors"
        >
          {t("payslip.crossPromo.cta")}
          <ArrowRight className="w-3 h-3" />
        </a>
      </div>
    </div>
  );
}
