-- Seed realistic Danish national price observations (postal_code = NULL = national average).
-- The price_averages view requires ≥5 obs per group; ≥10 for the national fallback used by
-- getCrowdsourcedPrice(). We insert 10 observations per (category, household_type) pair so
-- NaboeffektView shows data immediately for new deployments.
--
-- All amounts are monthly DKK. Values sourced from:
--   Danmarks Statistik, Boliga.dk, Forbrugerrådet Tænk (2025/2026 averages).

INSERT INTO public.price_observations (category, postal_code, household_type, amount, created_at) VALUES

-- ── Rent (lejer) ────────────────────────────────────────────────────────────
('rent', NULL, 'solo',  8000, now() - interval '5 months'),
('rent', NULL, 'solo',  8500, now() - interval '4 months 20 days'),
('rent', NULL, 'solo',  9000, now() - interval '4 months'),
('rent', NULL, 'solo',  7500, now() - interval '3 months 15 days'),
('rent', NULL, 'solo',  8200, now() - interval '3 months'),
('rent', NULL, 'solo',  9500, now() - interval '2 months 20 days'),
('rent', NULL, 'solo', 10000, now() - interval '2 months'),
('rent', NULL, 'solo',  7800, now() - interval '1 month 15 days'),
('rent', NULL, 'solo',  8800, now() - interval '1 month'),
('rent', NULL, 'solo',  9200, now() - interval '15 days'),

('rent', NULL, 'par', 11000, now() - interval '5 months'),
('rent', NULL, 'par', 12000, now() - interval '4 months 20 days'),
('rent', NULL, 'par', 13000, now() - interval '4 months'),
('rent', NULL, 'par', 12500, now() - interval '3 months 15 days'),
('rent', NULL, 'par', 11500, now() - interval '3 months'),
('rent', NULL, 'par', 14000, now() - interval '2 months 20 days'),
('rent', NULL, 'par', 10500, now() - interval '2 months'),
('rent', NULL, 'par', 13500, now() - interval '1 month 15 days'),
('rent', NULL, 'par', 12000, now() - interval '1 month'),
('rent', NULL, 'par', 11000, now() - interval '15 days'),

-- ── Mortgage (ejer) ─────────────────────────────────────────────────────────
('mortgage', NULL, 'solo',  7000, now() - interval '5 months'),
('mortgage', NULL, 'solo',  8000, now() - interval '4 months 20 days'),
('mortgage', NULL, 'solo',  7500, now() - interval '4 months'),
('mortgage', NULL, 'solo',  6500, now() - interval '3 months 15 days'),
('mortgage', NULL, 'solo',  9000, now() - interval '3 months'),
('mortgage', NULL, 'solo',  8500, now() - interval '2 months 20 days'),
('mortgage', NULL, 'solo',  7000, now() - interval '2 months'),
('mortgage', NULL, 'solo',  7800, now() - interval '1 month 15 days'),
('mortgage', NULL, 'solo',  6800, now() - interval '1 month'),
('mortgage', NULL, 'solo',  8200, now() - interval '15 days'),

('mortgage', NULL, 'par', 10000, now() - interval '5 months'),
('mortgage', NULL, 'par', 12000, now() - interval '4 months 20 days'),
('mortgage', NULL, 'par', 11000, now() - interval '4 months'),
('mortgage', NULL, 'par',  9500, now() - interval '3 months 15 days'),
('mortgage', NULL, 'par', 13000, now() - interval '3 months'),
('mortgage', NULL, 'par', 11500, now() - interval '2 months 20 days'),
('mortgage', NULL, 'par', 10500, now() - interval '2 months'),
('mortgage', NULL, 'par', 12500, now() - interval '1 month 15 days'),
('mortgage', NULL, 'par',  9000, now() - interval '1 month'),
('mortgage', NULL, 'par', 11000, now() - interval '15 days'),

-- ── Andelsbolig ─────────────────────────────────────────────────────────────
('andel', NULL, 'solo', 5000, now() - interval '5 months'),
('andel', NULL, 'solo', 5500, now() - interval '4 months 20 days'),
('andel', NULL, 'solo', 6000, now() - interval '4 months'),
('andel', NULL, 'solo', 4800, now() - interval '3 months 15 days'),
('andel', NULL, 'solo', 5200, now() - interval '3 months'),
('andel', NULL, 'solo', 5800, now() - interval '2 months 20 days'),
('andel', NULL, 'solo', 4500, now() - interval '2 months'),
('andel', NULL, 'solo', 6200, now() - interval '1 month 15 days'),
('andel', NULL, 'solo', 5000, now() - interval '1 month'),
('andel', NULL, 'solo', 5500, now() - interval '15 days'),

('andel', NULL, 'par', 7000, now() - interval '5 months'),
('andel', NULL, 'par', 7500, now() - interval '4 months 20 days'),
('andel', NULL, 'par', 8000, now() - interval '4 months'),
('andel', NULL, 'par', 6500, now() - interval '3 months 15 days'),
('andel', NULL, 'par', 7200, now() - interval '3 months'),
('andel', NULL, 'par', 8500, now() - interval '2 months 20 days'),
('andel', NULL, 'par', 6800, now() - interval '2 months'),
('andel', NULL, 'par', 7800, now() - interval '1 month 15 days'),
('andel', NULL, 'par', 7000, now() - interval '1 month'),
('andel', NULL, 'par', 7500, now() - interval '15 days'),

-- ── Insurance (forsikringer) ─────────────────────────────────────────────────
('insurance', NULL, 'solo',  700, now() - interval '5 months'),
('insurance', NULL, 'solo',  800, now() - interval '4 months 20 days'),
('insurance', NULL, 'solo',  650, now() - interval '4 months'),
('insurance', NULL, 'solo',  750, now() - interval '3 months 15 days'),
('insurance', NULL, 'solo',  900, now() - interval '3 months'),
('insurance', NULL, 'solo',  600, now() - interval '2 months 20 days'),
('insurance', NULL, 'solo',  850, now() - interval '2 months'),
('insurance', NULL, 'solo',  720, now() - interval '1 month 15 days'),
('insurance', NULL, 'solo',  780, now() - interval '1 month'),
('insurance', NULL, 'solo',  680, now() - interval '15 days'),

('insurance', NULL, 'par', 1200, now() - interval '5 months'),
('insurance', NULL, 'par', 1400, now() - interval '4 months 20 days'),
('insurance', NULL, 'par', 1100, now() - interval '4 months'),
('insurance', NULL, 'par', 1300, now() - interval '3 months 15 days'),
('insurance', NULL, 'par', 1500, now() - interval '3 months'),
('insurance', NULL, 'par', 1000, now() - interval '2 months 20 days'),
('insurance', NULL, 'par', 1350, now() - interval '2 months'),
('insurance', NULL, 'par', 1250, now() - interval '1 month 15 days'),
('insurance', NULL, 'par', 1150, now() - interval '1 month'),
('insurance', NULL, 'par', 1450, now() - interval '15 days'),

-- ── Car loan ────────────────────────────────────────────────────────────────
('car_loan', NULL, 'solo', 3000, now() - interval '5 months'),
('car_loan', NULL, 'solo', 3500, now() - interval '4 months 20 days'),
('car_loan', NULL, 'solo', 2500, now() - interval '4 months'),
('car_loan', NULL, 'solo', 4000, now() - interval '3 months 15 days'),
('car_loan', NULL, 'solo', 2800, now() - interval '3 months'),
('car_loan', NULL, 'solo', 3200, now() - interval '2 months 20 days'),
('car_loan', NULL, 'solo', 2000, now() - interval '2 months'),
('car_loan', NULL, 'solo', 4500, now() - interval '1 month 15 days'),
('car_loan', NULL, 'solo', 3000, now() - interval '1 month'),
('car_loan', NULL, 'solo', 3800, now() - interval '15 days'),

('car_loan', NULL, 'par', 3500, now() - interval '5 months'),
('car_loan', NULL, 'par', 4000, now() - interval '4 months 20 days'),
('car_loan', NULL, 'par', 3000, now() - interval '4 months'),
('car_loan', NULL, 'par', 4500, now() - interval '3 months 15 days'),
('car_loan', NULL, 'par', 3200, now() - interval '3 months'),
('car_loan', NULL, 'par', 3800, now() - interval '2 months 20 days'),
('car_loan', NULL, 'par', 2800, now() - interval '2 months'),
('car_loan', NULL, 'par', 4200, now() - interval '1 month 15 days'),
('car_loan', NULL, 'par', 3500, now() - interval '1 month'),
('car_loan', NULL, 'par', 4000, now() - interval '15 days'),

-- ── Car fuel (benzin/el) ────────────────────────────────────────────────────
('car_fuel', NULL, 'solo', 1000, now() - interval '5 months'),
('car_fuel', NULL, 'solo', 1200, now() - interval '4 months 20 days'),
('car_fuel', NULL, 'solo',  800, now() - interval '4 months'),
('car_fuel', NULL, 'solo', 1500, now() - interval '3 months 15 days'),
('car_fuel', NULL, 'solo',  900, now() - interval '3 months'),
('car_fuel', NULL, 'solo', 1100, now() - interval '2 months 20 days'),
('car_fuel', NULL, 'solo',  700, now() - interval '2 months'),
('car_fuel', NULL, 'solo', 1400, now() - interval '1 month 15 days'),
('car_fuel', NULL, 'solo', 1000, now() - interval '1 month'),
('car_fuel', NULL, 'solo', 1300, now() - interval '15 days'),

('car_fuel', NULL, 'par', 1500, now() - interval '5 months'),
('car_fuel', NULL, 'par', 1800, now() - interval '4 months 20 days'),
('car_fuel', NULL, 'par', 1200, now() - interval '4 months'),
('car_fuel', NULL, 'par', 2000, now() - interval '3 months 15 days'),
('car_fuel', NULL, 'par', 1400, now() - interval '3 months'),
('car_fuel', NULL, 'par', 1600, now() - interval '2 months 20 days'),
('car_fuel', NULL, 'par', 1000, now() - interval '2 months'),
('car_fuel', NULL, 'par', 1900, now() - interval '1 month 15 days'),
('car_fuel', NULL, 'par', 1500, now() - interval '1 month'),
('car_fuel', NULL, 'par', 1700, now() - interval '15 days'),

-- ── Car insurance ────────────────────────────────────────────────────────────
-- Note: submitPriceObservations stores carInsurance/12 (monthly), so these are monthly values
('car_insurance', NULL, 'solo', 500, now() - interval '5 months'),
('car_insurance', NULL, 'solo', 600, now() - interval '4 months 20 days'),
('car_insurance', NULL, 'solo', 450, now() - interval '4 months'),
('car_insurance', NULL, 'solo', 700, now() - interval '3 months 15 days'),
('car_insurance', NULL, 'solo', 550, now() - interval '3 months'),
('car_insurance', NULL, 'solo', 500, now() - interval '2 months 20 days'),
('car_insurance', NULL, 'solo', 650, now() - interval '2 months'),
('car_insurance', NULL, 'solo', 480, now() - interval '1 month 15 days'),
('car_insurance', NULL, 'solo', 520, now() - interval '1 month'),
('car_insurance', NULL, 'solo', 580, now() - interval '15 days'),

('car_insurance', NULL, 'par', 700, now() - interval '5 months'),
('car_insurance', NULL, 'par', 800, now() - interval '4 months 20 days'),
('car_insurance', NULL, 'par', 650, now() - interval '4 months'),
('car_insurance', NULL, 'par', 900, now() - interval '3 months 15 days'),
('car_insurance', NULL, 'par', 750, now() - interval '3 months'),
('car_insurance', NULL, 'par', 700, now() - interval '2 months 20 days'),
('car_insurance', NULL, 'par', 850, now() - interval '2 months'),
('car_insurance', NULL, 'par', 680, now() - interval '1 month 15 days'),
('car_insurance', NULL, 'par', 720, now() - interval '1 month'),
('car_insurance', NULL, 'par', 780, now() - interval '15 days'),

-- ── Union (fagforening) ──────────────────────────────────────────────────────
('union', NULL, 'solo', 400, now() - interval '5 months'),
('union', NULL, 'solo', 450, now() - interval '4 months 20 days'),
('union', NULL, 'solo', 350, now() - interval '4 months'),
('union', NULL, 'solo', 500, now() - interval '3 months 15 days'),
('union', NULL, 'solo', 380, now() - interval '3 months'),
('union', NULL, 'solo', 420, now() - interval '2 months 20 days'),
('union', NULL, 'solo', 480, now() - interval '2 months'),
('union', NULL, 'solo', 360, now() - interval '1 month 15 days'),
('union', NULL, 'solo', 440, now() - interval '1 month'),
('union', NULL, 'solo', 400, now() - interval '15 days'),

('union', NULL, 'par',  800, now() - interval '5 months'),
('union', NULL, 'par',  900, now() - interval '4 months 20 days'),
('union', NULL, 'par',  700, now() - interval '4 months'),
('union', NULL, 'par', 1000, now() - interval '3 months 15 days'),
('union', NULL, 'par',  760, now() - interval '3 months'),
('union', NULL, 'par',  840, now() - interval '2 months 20 days'),
('union', NULL, 'par',  960, now() - interval '2 months'),
('union', NULL, 'par',  720, now() - interval '1 month 15 days'),
('union', NULL, 'par',  880, now() - interval '1 month'),
('union', NULL, 'par',  800, now() - interval '15 days'),

-- ── Fitness ──────────────────────────────────────────────────────────────────
('fitness', NULL, 'solo', 200, now() - interval '5 months'),
('fitness', NULL, 'solo', 250, now() - interval '4 months 20 days'),
('fitness', NULL, 'solo', 300, now() - interval '4 months'),
('fitness', NULL, 'solo', 180, now() - interval '3 months 15 days'),
('fitness', NULL, 'solo', 220, now() - interval '3 months'),
('fitness', NULL, 'solo', 280, now() - interval '2 months 20 days'),
('fitness', NULL, 'solo', 240, now() - interval '2 months'),
('fitness', NULL, 'solo', 190, now() - interval '1 month 15 days'),
('fitness', NULL, 'solo', 260, now() - interval '1 month'),
('fitness', NULL, 'solo', 210, now() - interval '15 days'),

('fitness', NULL, 'par', 400, now() - interval '5 months'),
('fitness', NULL, 'par', 500, now() - interval '4 months 20 days'),
('fitness', NULL, 'par', 350, now() - interval '4 months'),
('fitness', NULL, 'par', 450, now() - interval '3 months 15 days'),
('fitness', NULL, 'par', 380, now() - interval '3 months'),
('fitness', NULL, 'par', 420, now() - interval '2 months 20 days'),
('fitness', NULL, 'par', 480, now() - interval '2 months'),
('fitness', NULL, 'par', 360, now() - interval '1 month 15 days'),
('fitness', NULL, 'par', 440, now() - interval '1 month'),
('fitness', NULL, 'par', 400, now() - interval '15 days'),

-- ── Pet (kæledyr) ────────────────────────────────────────────────────────────
('pet', NULL, 'solo', 500, now() - interval '5 months'),
('pet', NULL, 'solo', 600, now() - interval '4 months 20 days'),
('pet', NULL, 'solo', 400, now() - interval '4 months'),
('pet', NULL, 'solo', 700, now() - interval '3 months 15 days'),
('pet', NULL, 'solo', 450, now() - interval '3 months'),
('pet', NULL, 'solo', 550, now() - interval '2 months 20 days'),
('pet', NULL, 'solo', 650, now() - interval '2 months'),
('pet', NULL, 'solo', 480, now() - interval '1 month 15 days'),
('pet', NULL, 'solo', 520, now() - interval '1 month'),
('pet', NULL, 'solo', 580, now() - interval '15 days'),

('pet', NULL, 'par', 600, now() - interval '5 months'),
('pet', NULL, 'par', 700, now() - interval '4 months 20 days'),
('pet', NULL, 'par', 500, now() - interval '4 months'),
('pet', NULL, 'par', 800, now() - interval '3 months 15 days'),
('pet', NULL, 'par', 550, now() - interval '3 months'),
('pet', NULL, 'par', 650, now() - interval '2 months 20 days'),
('pet', NULL, 'par', 750, now() - interval '2 months'),
('pet', NULL, 'par', 580, now() - interval '1 month 15 days'),
('pet', NULL, 'par', 620, now() - interval '1 month'),
('pet', NULL, 'par', 680, now() - interval '15 days');
